defmodule KilnCMS.Accounts.ThrottleCounter do
  @moduledoc """
  One fixed-window counter of a shared auth budget (#1619, threat-model
  residual 10).

  The budgets that bound credential guessing — `KilnCMS.Accounts.AccountThrottle`
  (sign-in, the second factor, the mail and alert budgets) and the
  `KilnCMSWeb.RateLimit` buckets in front of the credential forms — used to count
  in ETS, so N nodes multiplied every budget by N and a restart forgave every
  attempt. A row here is the same answer on every node, and survives a deploy.

  This resource owns the **table**: its shape, its migration (generated by
  `mix ash.codegen`), its policies and its pruning. The **hot path** does not go
  through an Ash action. `KilnCMS.Accounts.ThrottleStore` charges a budget with
  one `INSERT ... ON CONFLICT DO UPDATE ... RETURNING` through `KilnCMS.Repo`,
  and its moduledoc says why that one statement is raw SQL.

  ## What a row holds, and what it does not

    * `bucket` — which budget (`"signin"`, `"2fa"`, `"ip:auth"`, …). A short
      constant chosen by the code, never by a caller.
    * `key_hash` — SHA-256 of the budget's key. Keys are attacker-chosen (one
      per distinct address *submitted* at the sign-in form), so the column is
      fixed at 32 bytes whatever was submitted, and no address, email or IP is
      ever written in the clear.
    * `window_index` — which fixed window, computed from the **database's**
      clock so every node agrees on where a window starts.
    * `expires_at` — when that window closes. The prune below deletes every
      row past it.

  Nothing here references a user. Counters on the user row would turn every
  guess into a write to a row the attacker chooses, and leave an address with no
  account nowhere to count — which is what reopens account enumeration.

  ## Bounded and expiring

  A row lives for its window plus at most one prune period, so the table holds
  roughly *(distinct keys charged per window) × (windows alive)*. Every new
  sign-in key costs the server one bcrypt verification (a refusal burns a
  simulated one), so the key rate is bounded by the cluster's hashing throughput
  before it is bounded by anything here. See `docs/threat-model.md`, residual 10.

  ## Authorization

  System-only. No person — admin included — reads or writes a row: `:read` is
  forbidden to everyone, and `:prune` admits only the system actor and the
  AshOban cron that runs it. The budgets themselves are charged by
  `ThrottleStore` under no actor at all, because they run *before* anyone is
  authenticated.
  """
  use Ash.Resource,
    domain: KilnCMS.Accounts,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer],
    extensions: [AshOban]

  postgres do
    table "throttle_counters"
    repo KilnCMS.Repo

    custom_indexes do
      # The prune's scan.
      index [:expires_at], name: "throttle_counters_expires_at_index"
    end
  end

  oban do
    scheduled_actions do
      # Every five minutes: the shortest window here is one minute and the
      # longest six hours, so a closed window waits at most five minutes to go.
      # Oban's cron runs it once per cluster, not once per node.
      schedule :prune, "*/5 * * * *" do
        action :prune
        queue :default
        worker_module_name KilnCMS.Accounts.ThrottleCounter.Workers.Prune
      end
    end
  end

  actions do
    defaults [:read]

    # Deletes every row whose window has closed, in bounded batches (see
    # `ThrottleStore.prune/0`). Returns how many went.
    action :prune, :integer do
      run fn _input, _context -> {:ok, KilnCMS.Accounts.ThrottleStore.prune()} end
    end
  end

  policies do
    # The scheduled prune.
    bypass AshOban.Checks.AshObanInteraction do
      authorize_if always()
    end

    policy action(:prune) do
      authorize_if KilnCMS.Checks.SystemActor
    end

    # Nobody reads a counter. A row names nothing on its own, but "this key was
    # charged N times" is still an oracle nobody needs.
    policy action_type(:read) do
      forbid_if always()
    end
  end

  attributes do
    attribute :bucket, :string do
      primary_key? true
      allow_nil? false
      public? false
      constraints max_length: 64
    end

    attribute :key_hash, :binary do
      primary_key? true
      allow_nil? false
      public? false
    end

    attribute :window_index, :integer do
      primary_key? true
      allow_nil? false
      public? false
    end

    attribute :count, :integer do
      allow_nil? false
      public? false
    end

    attribute :expires_at, :utc_datetime_usec do
      allow_nil? false
      public? false
    end
  end
end
