defmodule KilnCMS.Accounts.Token do
  @moduledoc """
  Stores AshAuthentication tokens (sign-in/confirmation/reset JWTs) so they
  can be verified and revoked.

  Almost entirely AshAuthentication's — every action but one is theirs, and the
  attributes are theirs. The exception is `:spend_jti` (#743), which records a
  redeemed headless two-factor blob; see its comment for why it rides here
  rather than on a table of its own. **If this resource is ever regenerated by
  the AshAuthentication installer, that action has to be put back** — without it
  `KilnCMS.Accounts.PendingSignIn` cannot make a pending sign-in single-use.
  """
  use Ash.Resource,
    otp_app: :kiln_cms,
    domain: KilnCMS.Accounts,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer],
    extensions: [AshAuthentication.TokenResource, AshOban]

  postgres do
    table "tokens"
    repo KilnCMS.Repo
  end

  # The purpose and lifetime of a `:spend_jti` row, bound once and read by
  # `KilnCMS.Accounts.PendingSignIn` (#743). Two independent copies of a magic
  # string that must agree is how a single-use check degrades to a no-op that
  # nothing fails on.
  @pending_sign_in_purpose "pending_sign_in"
  # One second beyond the blob's own `max_age`, so there is no window in which a
  # blob is still redeemable but the record of its use has expired.
  @pending_sign_in_ttl 301

  @doc "The `purpose` a redeemed pending-sign-in blob is recorded under (#743)."
  @spec pending_sign_in_purpose() :: String.t()
  def pending_sign_in_purpose, do: @pending_sign_in_purpose

  @doc "How long a redeemed pending-sign-in record is kept, in seconds (#743)."
  @spec pending_sign_in_ttl() :: pos_integer()
  def pending_sign_in_ttl, do: @pending_sign_in_ttl

  # Privacy retention (#224): expired auth tokens (sign-in/reset/magic/confirm
  # JWTs) carry a subject + jti and otherwise accumulate forever. A nightly
  # AshOban trigger runs `:expunge_expired`, so an expired token is purged within
  # ~24h of expiry. See docs/data-flows.md and config `:token_retention`.
  oban do
    triggers do
      trigger :expunge_expired do
        action :expunge_expired
        read_action :expired
        worker_read_action :expired
        queue :default
        scheduler_cron "0 4 * * *"
        where expr(expires_at < now())

        worker_module_name KilnCMS.Accounts.Token.AshOban.Worker.ExpungeExpired
        scheduler_module_name KilnCMS.Accounts.Token.AshOban.Scheduler.ExpungeExpired
      end
    end
  end

  actions do
    defaults [:read]

    read :expired do
      description "Look up all expired tokens."
      # Keyset pagination is required for the AshOban `:expunge_expired` trigger;
      # `required?: false` keeps any direct callers returning a plain list.
      pagination keyset?: true, required?: false
      filter expr(expires_at < now())
    end

    read :get_token do
      description "Look up a token by JTI or token, and an optional purpose."
      get? true
      argument :token, :string, sensitive?: true
      argument :jti, :string, sensitive?: true
      argument :purpose, :string, sensitive?: false

      prepare AshAuthentication.TokenResource.GetTokenPreparation
    end

    action :revoked?, :boolean do
      description "Returns true if a revocation token is found for the provided token"
      argument :token, :string, sensitive?: true
      argument :jti, :string, sensitive?: true

      run AshAuthentication.TokenResource.IsRevoked
    end

    create :revoke_token do
      description "Revoke a token. Creates a revocation token corresponding to the provided token."
      accept [:extra_data]
      argument :token, :string, allow_nil?: false, sensitive?: true

      change AshAuthentication.TokenResource.RevokeTokenChange
    end

    create :revoke_jti do
      description "Revoke a token by JTI. Creates a revocation token corresponding to the provided jti."
      accept [:extra_data]
      argument :subject, :string, allow_nil?: false, sensitive?: true
      argument :jti, :string, allow_nil?: false, sensitive?: true

      change AshAuthentication.TokenResource.RevokeJtiChange
    end

    create :store_token do
      description "Stores a token used for the provided purpose."
      accept [:extra_data, :purpose]
      argument :token, :string, allow_nil?: false, sensitive?: true
      change AshAuthentication.TokenResource.StoreTokenChange
    end

    # Not an AshAuthentication action (#743). `KilnCMS.Accounts.PendingSignIn`
    # needs "this attempt is now spent, exactly once, across every node", and
    # `jti` is this table's primary key — so the INSERT *is* the check. A second
    # redemption of the same blob, on any node, loses the race at Postgres
    # rather than at a cache each node keeps its own copy of.
    #
    # It rides on this resource rather than a table of its own because the shape
    # is already right (jti, subject, expires_at, purpose) and the nightly
    # `:expunge_expired` trigger above already sweeps it. The purpose is its own
    # string, so `AshAuthentication.TokenResource.IsRevoked` — which looks for
    # `"revocation"` — never sees these rows.
    create :spend_jti do
      description "Record a pending sign-in blob as redeemed. Fails if already spent."
      accept [:jti, :subject]

      change set_attribute(:purpose, @pending_sign_in_purpose)

      # Computed here, not accepted. `expires_at` is what the `:expunge_expired`
      # destroy below deletes by AND what `GetTokenPreparation` filters reads on,
      # so a caller passing a past timestamp would write a claim that is
      # invisible and immediately collectable — and the blob it was meant to
      # retire becomes redeemable again. `purpose` is pinned for the same reason;
      # neither belongs in `accept`.
      change fn changeset, _context ->
        Ash.Changeset.force_change_attribute(
          changeset,
          :expires_at,
          DateTime.add(DateTime.utc_now(), @pending_sign_in_ttl, :second)
        )
      end
    end

    destroy :expunge_expired do
      description "Deletes expired tokens."
      change filter(expr(expires_at < now()))
    end

    update :revoke_all_stored_for_subject do
      description "Revokes all stored tokens for a specific subject."
      accept [:extra_data]
      argument :subject, :string, allow_nil?: false, sensitive?: true
      change AshAuthentication.TokenResource.RevokeAllStoredForSubjectChange
    end
  end

  policies do
    bypass AshAuthentication.Checks.AshAuthenticationInteraction do
      description "AshAuthentication can interact with the token resource"
      authorize_if always()
    end

    # The nightly `:expunge_expired` trigger reads + destroys as a trusted system
    # job (no actor); let AshOban's scheduler/worker through.
    bypass AshOban.Checks.AshObanInteraction do
      description "AshOban can run the expired-token expunge trigger"
      authorize_if always()
    end

    # `:spend_jti` (#743) is system-only and says so here rather than only at its
    # one call site. There is no actor to authorize — the whole point of the step
    # is that the caller has *not* finished signing in — so `PendingSignIn` calls
    # it with `authorize?: false`. Forbidding it outright means any *other*
    # caller, including anything reached through an API extension, is refused
    # rather than quietly inheriting a bypass above.
    policy action(:spend_jti) do
      forbid_if always()
    end
  end

  attributes do
    attribute :jti, :string do
      primary_key? true
      public? true
      allow_nil? false
      sensitive? true
    end

    attribute :subject, :string do
      allow_nil? false
      public? true
    end

    attribute :expires_at, :utc_datetime do
      allow_nil? false
      public? true
    end

    attribute :purpose, :string do
      allow_nil? false
      public? true
    end

    attribute :extra_data, :map do
      public? true
    end

    create_timestamp :created_at
    update_timestamp :updated_at
  end
end
