defmodule KilnCMS.Accounts.Token do
  @moduledoc """
  Stores AshAuthentication tokens (sign-in/confirmation/reset JWTs) so they
  can be verified and revoked.

  Almost entirely AshAuthentication's — every action but three is theirs, and the
  attributes are theirs. The exceptions are `:spend_jti` (#743), which records a
  redeemed headless two-factor blob, and the `:hold_for_second_factor` /
  `:release_second_factor_hold` pair (#742), which park a first-factor token for
  as long as its account owes a code. See each one's comment for what it is for.
  **If this resource is ever regenerated by the AshAuthentication installer,
  those three have to be put back** — without them
  `KilnCMS.Accounts.PendingSignIn` can neither make a pending sign-in single-use
  nor withhold the token it carries.
  """
  use Ash.Resource,
    otp_app: :kiln_cms,
    domain: KilnCMS.Accounts,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer],
    extensions: [AshAuthentication.TokenResource, AshOban]

  postgres do
    table "tokens"
    repo KilnCMS.Repo
  end

  # The purpose and lifetime of a `:spend_jti` row, bound once and read by
  # `KilnCMS.Accounts.PendingSignIn` (#743). Two independent copies of a magic
  # string that must agree is how a single-use check degrades to a no-op that
  # nothing fails on.
  @pending_sign_in_purpose "pending_sign_in"
  # One second beyond the blob's own `max_age`, so there is no window in which a
  # blob is still redeemable but the record of its use has expired.
  @pending_sign_in_ttl 301

  @doc "The `purpose` a redeemed pending-sign-in blob is recorded under (#743)."
  @spec pending_sign_in_purpose() :: String.t()
  def pending_sign_in_purpose, do: @pending_sign_in_purpose

  @doc "How long a redeemed pending-sign-in record is kept, in seconds (#743)."
  @spec pending_sign_in_ttl() :: pos_integer()
  def pending_sign_in_ttl, do: @pending_sign_in_ttl

  # The purpose a first-factor token is parked under while its account owes a
  # second factor (#742), and the purpose it is returned to once the code lands.
  #
  # `"user"` is not ours to choose: `AshAuthentication.Plug.Helpers.validate_token/3`
  # looks the row up with exactly that purpose when
  # `require_token_presence_for_authentication?` is set, which it is. So moving a
  # row off `"user"` is what makes the JWT naming it unusable, and moving it back
  # is what makes it usable again. The hold purpose only has to be *something
  # else* — it is deliberately not `"revocation"`, which
  # `AshAuthentication.TokenResource.IsRevoked` reads as a permanent verdict.
  @user_purpose "user"
  @second_factor_hold_purpose "pending_second_factor"

  # Long enough that a code submitted at the last redeemable instant of the blob
  # can still be verified and released — `GetTokenPreparation` filters
  # `expires_at > now()`, so a hold that lapses mid-request is a token nobody can
  # put back. The blob's own five minutes plus a minute of slack. Short enough
  # that an abandoned exchange leaves nothing worth collecting: the row is inert
  # from the instant it is held and gone within a day of expiring, rather than
  # sitting live for the JWT's own fourteen days.
  @second_factor_hold_ttl 360

  @doc "The `purpose` a live, usable stored token carries — AshAuthentication's (#742)."
  @spec user_purpose() :: String.t()
  def user_purpose, do: @user_purpose

  @doc "The `purpose` a first-factor token is parked under while a code is owed (#742)."
  @spec second_factor_hold_purpose() :: String.t()
  def second_factor_hold_purpose, do: @second_factor_hold_purpose

  @doc "How long a first-factor hold lasts, in seconds (#742)."
  @spec second_factor_hold_ttl() :: pos_integer()
  def second_factor_hold_ttl, do: @second_factor_hold_ttl

  @doc false
  # The jti a token claims, or `nil` if it claims none.
  #
  # `AshAuthentication.Jwt.peek/1` is `Joken.peek_claims/1`, which returns
  # `{:error, :token_malformed}` for most rubbish but **raises** for the one
  # shape that gets far enough to be decoded: three dot-separated segments whose
  # middle one is not base64-encoded JSON. `"stub.jwt.token"` is exactly that,
  # and it is what the fixtures used to pass. Callers here want an answer rather
  # than an exception, so the raise is caught rather than left to travel.
  @spec peeked_jti(term()) :: String.t() | nil
  def peeked_jti(token) when is_binary(token) do
    case AshAuthentication.Jwt.peek(token) do
      {:ok, %{"jti" => jti}} when is_binary(jti) -> jti
      _ -> nil
    end
  rescue
    _ -> nil
  end

  def peeked_jti(_token), do: nil

  @doc false
  # The `exp` claim as a DateTime, or `nil`. Used by the atomic release (#1173)
  # so `PendingSignIn` peeks once rather than once here and again inside
  # `StoreTokenChange`.
  @spec peeked_expires_at(term()) :: DateTime.t() | nil
  def peeked_expires_at(token) when is_binary(token) do
    case AshAuthentication.Jwt.peek(token) do
      {:ok, %{"exp" => exp}} when is_integer(exp) ->
        case DateTime.from_unix(exp) do
          {:ok, expires_at} -> expires_at
          _ -> nil
        end

      _ ->
        nil
    end
  rescue
    _ -> nil
  end

  def peeked_expires_at(_token), do: nil

  # Privacy retention (#224): expired auth tokens (sign-in/reset/magic/confirm
  # JWTs) carry a subject + jti and otherwise accumulate forever. A nightly
  # AshOban trigger runs `:expunge_expired`, so an expired token is purged within
  # ~24h of expiry. See docs/data-flows.md and config `:token_retention`.
  oban do
    triggers do
      trigger :expunge_expired do
        action :expunge_expired
        read_action :expired
        worker_read_action :expired
        queue :default
        scheduler_cron "0 4 * * *"
        where expr(expires_at < now())

        worker_module_name KilnCMS.Accounts.Token.AshOban.Worker.ExpungeExpired
        scheduler_module_name KilnCMS.Accounts.Token.AshOban.Scheduler.ExpungeExpired
      end
    end
  end

  actions do
    defaults [:read]

    read :expired do
      description "Look up all expired tokens."
      # Keyset pagination is required for the AshOban `:expunge_expired` trigger;
      # `required?: false` keeps any direct callers returning a plain list.
      pagination keyset?: true, required?: false
      filter expr(expires_at < now())
    end

    read :get_token do
      description "Look up a token by JTI or token, and an optional purpose."
      get? true
      argument :token, :string, sensitive?: true
      argument :jti, :string, sensitive?: true
      argument :purpose, :string, sensitive?: false

      prepare AshAuthentication.TokenResource.GetTokenPreparation
    end

    action :revoked?, :boolean do
      description "Returns true if a revocation token is found for the provided token"
      argument :token, :string, sensitive?: true
      argument :jti, :string, sensitive?: true

      run AshAuthentication.TokenResource.IsRevoked
    end

    create :revoke_token do
      description "Revoke a token. Creates a revocation token corresponding to the provided token."
      accept [:extra_data]
      argument :token, :string, allow_nil?: false, sensitive?: true

      change AshAuthentication.TokenResource.RevokeTokenChange
    end

    create :revoke_jti do
      description "Revoke a token by JTI. Creates a revocation token corresponding to the provided jti."
      accept [:extra_data]
      argument :subject, :string, allow_nil?: false, sensitive?: true
      argument :jti, :string, allow_nil?: false, sensitive?: true

      change AshAuthentication.TokenResource.RevokeJtiChange
    end

    create :store_token do
      description "Stores a token used for the provided purpose."
      accept [:extra_data, :purpose]
      argument :token, :string, allow_nil?: false, sensitive?: true
      change AshAuthentication.TokenResource.StoreTokenChange
    end

    # Not an AshAuthentication action (#743). `KilnCMS.Accounts.PendingSignIn`
    # needs "this attempt is now spent, exactly once, across every node", and
    # `jti` is this table's primary key — so the INSERT *is* the check. A second
    # redemption of the same blob, on any node, loses the race at Postgres
    # rather than at a cache each node keeps its own copy of.
    #
    # It rides on this resource rather than a table of its own because the shape
    # is already right (jti, subject, expires_at, purpose) and the nightly
    # `:expunge_expired` trigger above already sweeps it. The purpose is its own
    # string, so `AshAuthentication.TokenResource.IsRevoked` — which looks for
    # `"revocation"` — never sees these rows.
    create :spend_jti do
      description "Record a pending sign-in blob as redeemed. Fails if already spent."
      accept [:jti, :subject]

      change set_attribute(:purpose, @pending_sign_in_purpose)

      # Computed here, not accepted. `expires_at` is what the `:expunge_expired`
      # destroy below deletes by AND what `GetTokenPreparation` filters reads on,
      # so a caller passing a past timestamp would write a claim that is
      # invisible and immediately collectable — and the blob it was meant to
      # retire becomes redeemable again. `purpose` is pinned for the same reason;
      # neither belongs in `accept`.
      change fn changeset, _context ->
        Ash.Changeset.force_change_attribute(
          changeset,
          :expires_at,
          DateTime.add(DateTime.utc_now(), @pending_sign_in_ttl, :second)
        )
      end
    end

    # The other half of the two-factor story (#742), and the other pair that is
    # ours rather than AshAuthentication's.
    #
    # `store_all_tokens?` mints AND stores the first-factor JWT before either
    # controller learns the account owes a code, so a sign-in abandoned at the
    # prompt used to leave a live, usable token row that nobody holds — for the
    # JWT's full lifetime. #761 bounded how many an attacker could cause; these
    # two stop them being usable at all.
    #
    # Held, not revoked, because the exchange may still complete: a hold is
    # reversible and `:revoke_jti`'s thousand-year `"revocation"` row is not.
    #
    # Both actions are atomic (#1173): `PendingSignIn` filters by jti and runs a
    # single UPDATE, so a completed two-factor sign-in is two statements rather
    # than four. The purpose predicates below stay in the UPDATE's WHERE — that
    # is what makes the single-statement form safe against a revocation landing
    # between a would-be read and write.
    update :hold_for_second_factor do
      description "Park a first-factor token for as long as its account owes a second factor."
      accept []

      # Either purpose, so a re-mint re-takes the hold rather than silently
      # leaving the first one to lapse under a blob whose window has restarted.
      # `"revocation"` is not in the list, and that is the whole point of listing.
      change filter(expr(purpose in ^[@user_purpose, @second_factor_hold_purpose]))

      change set_attribute(:purpose, @second_factor_hold_purpose)

      # Database clock, not the app's: `from_now` evaluates in SQL, so a skewed
      # BEAM clock cannot write a hold that `GetTokenPreparation`'s `expires_at >
      # now()` (also SQL) would already consider lapsed.
      change atomic_update(:expires_at, expr(from_now(^@second_factor_hold_ttl, :second)))
    end

    update :release_second_factor_hold do
      description "Return a held first-factor token to use, now that the second factor has landed."
      accept []
      # The JWT's own `exp`, peeked once by the caller. Replaces
      # `StoreTokenChange`, which also rewrote `jti`/`subject` to values already
      # identical to the row and left the primary key in the UPDATE's SET —
      # and had no `atomic/3`, which forced the read-then-update shape (#1173).
      argument :expires_at, :utc_datetime, allow_nil?: false

      # The direction that grants use: without this in the UPDATE's WHERE, a
      # revocation landing between calls would be overwritten and a revoked
      # credential would go back to `"user"` with its full natural expiry.
      change filter(expr(purpose == ^@second_factor_hold_purpose))

      change set_attribute(:purpose, @user_purpose)
      change set_attribute(:expires_at, arg(:expires_at))
    end

    destroy :expunge_expired do
      description "Deletes expired tokens."
      change filter(expr(expires_at < now()))
    end

    update :revoke_all_stored_for_subject do
      description "Revokes all stored tokens for a specific subject."
      accept [:extra_data]
      argument :subject, :string, allow_nil?: false, sensitive?: true
      change AshAuthentication.TokenResource.RevokeAllStoredForSubjectChange
    end
  end

  policies do
    bypass AshAuthentication.Checks.AshAuthenticationInteraction do
      description "AshAuthentication can interact with the token resource"
      authorize_if always()
    end

    # The nightly `:expunge_expired` trigger reads + destroys as a trusted system
    # job (no actor); let AshOban's scheduler/worker through.
    bypass AshOban.Checks.AshObanInteraction do
      description "AshOban can run the expired-token expunge trigger"
      authorize_if always()
    end

    # `:spend_jti` (#743) is system-only and says so here rather than only at its
    # one call site. There is no actor to authorize — the whole point of the step
    # is that the caller has *not* finished signing in — so `PendingSignIn` calls
    # it with `authorize?: false`. Forbidding it outright means any *other*
    # caller, including anything reached through an API extension, is refused
    # rather than quietly inheriting a bypass above.
    policy action(:spend_jti) do
      forbid_if always()
    end

    # Same reasoning for the #742 pair. There is no actor at either point — the
    # hold is taken *because* the caller has not finished signing in, and the
    # release happens one step before they have — so `PendingSignIn` calls both
    # with `authorize?: false`, and everything else is refused by name.
    policy action([:hold_for_second_factor, :release_second_factor_hold]) do
      forbid_if always()
    end
  end

  attributes do
    attribute :jti, :string do
      primary_key? true
      public? true
      allow_nil? false
      sensitive? true
    end

    attribute :subject, :string do
      allow_nil? false
      public? true
    end

    attribute :expires_at, :utc_datetime do
      allow_nil? false
      public? true
    end

    attribute :purpose, :string do
      allow_nil? false
      public? true
    end

    attribute :extra_data, :map do
      public? true
    end

    create_timestamp :created_at
    update_timestamp :updated_at
  end
end
