defmodule KilnCMSWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :kiln_cms
  use Absinthe.Phoenix.Endpoint

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_kiln_cms_key",
    signing_salt: "Dsoh9oKb",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/ws/gql", KilnCMSWeb.GraphqlSocket, websocket: true, longpoll: true

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :kiln_cms,
    gzip: not code_reloading?,
    only: KilnCMSWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # User-uploaded media (KilnCMS.Storage.Local). Served from priv/uploads,
  # which the Local adapter writes to (the app-dir paths stay in sync). In
  # production a remote adapter (S3/MinIO) would serve these instead.
  plug :secure_upload_headers

  plug Plug.Static,
    at: "/uploads",
    from: {:kiln_cms, "priv/uploads"},
    gzip: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :kiln_cms
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  # Resolve the real client IP from X-Forwarded-For when behind a trusted proxy,
  # before anything (rate limiting, logging) reads conn.remote_ip.
  plug KilnCMSWeb.Plugs.ClientIp

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, AshJsonApi.Plug.Parser, Absinthe.Plug.Parser],
    pass: ["*/*"],
    # Explicit request-body cap (Plug's default is 8MB). Bounds the memory a
    # single request can force us to buffer; raise per-endpoint if large uploads
    # are ever needed.
    length: 8_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # Strip a `/<locale>/…` prefix and set the locale before routing.
  plug KilnCMSWeb.Plugs.SetLocale
  plug KilnCMSWeb.Router

  # Force user-uploaded media to download rather than render inline, and disable
  # content-type sniffing — defense-in-depth against a stored file being
  # interpreted as active content in the app origin. (Content-Disposition is
  # ignored for <img>/subresource loads, so legitimate images still render.)
  defp secure_upload_headers(%{path_info: ["uploads" | _]} = conn, _opts) do
    conn
    |> Plug.Conn.put_resp_header("content-disposition", "attachment")
    |> Plug.Conn.put_resp_header("x-content-type-options", "nosniff")
  end

  defp secure_upload_headers(conn, _opts), do: conn
end
