defmodule KilnCMSWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :kiln_cms
  # Absinthe.Phoenix.Endpoint + AshGraphql's run_docset override, which routes
  # subscription resolution through the Batcher (skipping data the subscriber
  # isn't allowed to see instead of erroring).
  use AshGraphql.Subscription.Endpoint

  # The session is stored in the cookie, signed (tamper-proof) and encrypted
  # (`encryption_salt`) so its contents aren't readable client-side either —
  # defense-in-depth for anything we put in the session (#217). Both salts derive
  # keys from `secret_key_base`; rotating that invalidates existing sessions.
  @session_options [
    store: :cookie,
    key: "_kiln_cms_key",
    signing_salt: "Dsoh9oKb",
    encryption_salt: "8fso5iqxDfI",
    same_site: "Lax",
    http_only: true,
    # Mark the cookie `Secure` in production (served over HTTPS via `force_ssl`);
    # left off in dev/test/e2e, which run over plain HTTP where a Secure cookie
    # would never be sent. Config-driven so each env opts in explicitly.
    secure: Application.compile_env(:kiln_cms, :secure_session_cookie, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/ws/gql", KilnCMSWeb.GraphqlSocket, websocket: true, longpoll: true

  # Collaborative-editing CRDT prototype (token-authenticated; joins refuse
  # unless :collab_prototype is enabled — see KilnCMSWeb.CollabChannel).
  socket "/ws/collab", KilnCMSWeb.CollabSocket, websocket: true, longpoll: false

  # Visual-editing bridge live-preview push (#355). A raw transport socket (plain
  # JSON frames) so the dependency-free `bridge.js` consumes it without a Phoenix
  # JS client. Deliberately cross-origin (an external front end), so origin is
  # gated by the shared `KilnCMSWeb.CORS.check_socket_origin?/1` allowlist rather
  # than the endpoint host, and every connection additionally authorizes the API
  # key against the document's read policy. It carries no ambient credentials
  # (auth is the explicit `api_key` param, never a cookie), so Sobelow's CSWH
  # finding here is a false positive — ignored with rationale in `.sobelow-conf`.
  socket "/ws/bridge", KilnCMSWeb.BridgeSocket,
    websocket: [check_origin: {KilnCMSWeb.CORS, :check_socket_origin?, []}],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :kiln_cms,
    gzip: not code_reloading?,
    only: KilnCMSWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # User-uploaded media (KilnCMS.Storage.Local). Served from priv/uploads,
  # which the Local adapter writes to (the app-dir paths stay in sync). In
  # production a remote adapter (S3/MinIO) would serve these instead.
  plug :secure_upload_headers

  # Storage keys are UUIDs, so a blob never changes under its URL — mark the
  # responses immutable. Without this, Plug.Static's default forces a
  # revalidation round-trip per image per page view on media-heavy pages.
  plug Plug.Static,
    at: "/uploads",
    from: {:kiln_cms, "priv/uploads"},
    gzip: false,
    cache_control_for_etags: "public, max-age=31536000, immutable"

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :kiln_cms
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  # Resolve the real client IP from X-Forwarded-For when behind a trusted proxy,
  # before anything (rate limiting, logging) reads conn.remote_ip.
  plug KilnCMSWeb.Plugs.ClientIp

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, AshJsonApi.Plug.Parser, Absinthe.Plug.Parser],
    pass: ["*/*"],
    # Explicit request-body cap (Plug's default is 8MB). Bounds the memory a
    # single request can force us to buffer; raise per-endpoint if large uploads
    # are ever needed.
    length: 8_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # Strip a `/<locale>/…` prefix and set the locale before routing.
  plug KilnCMSWeb.Plugs.SetLocale

  # Resolve the request's organization from its host and set it as the Ash tenant
  # (epic #336), so every pipeline — delivery controllers, GraphQL, JSON:API — is
  # scoped to the right site. Bare-host/localhost requests resolve to the default org.
  plug KilnCMSWeb.Plugs.SetTenant

  # Attach request context (method, path, scrubbed headers/params) to any Sentry
  # event raised while handling this request. No-op without a configured DSN.
  # Sensitive params/headers are scrubbed by Sentry's defaults. On Bandit this is
  # the capture path — `Sentry.PlugCapture` is deliberately omitted (it would
  # double-report). See KilnCMS.Application.setup_observability/0.
  plug Sentry.PlugContext

  # CORS for the headless API surfaces (`/api/*`, `/gql`). Ahead of the router so
  # it can answer preflight `OPTIONS` requests, which never match a `get`/`post`
  # route. Scoped to API paths — browser pages stay same-origin.
  plug KilnCMSWeb.Plugs.ApiCORS

  plug KilnCMSWeb.Router

  # Force user-uploaded media to download rather than render inline, and disable
  # content-type sniffing — defense-in-depth against a stored file being
  # interpreted as active content in the app origin. (Content-Disposition is
  # ignored for <img>/subresource loads, so legitimate images still render.)
  defp secure_upload_headers(%{path_info: ["uploads" | _]} = conn, _opts) do
    conn
    |> Plug.Conn.put_resp_header("content-disposition", "attachment")
    |> Plug.Conn.put_resp_header("x-content-type-options", "nosniff")
  end

  defp secure_upload_headers(conn, _opts), do: conn
end
