defmodule KilnCMSWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :kiln_cms
  use Absinthe.Phoenix.Endpoint

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_kiln_cms_key",
    signing_salt: "Dsoh9oKb",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/ws/gql", KilnCMSWeb.GraphqlSocket, websocket: true, longpoll: true

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :kiln_cms,
    gzip: not code_reloading?,
    only: KilnCMSWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # User-uploaded media (KilnCMS.Storage.Local). Served from priv/uploads,
  # which the Local adapter writes to (the app-dir paths stay in sync). In
  # production a remote adapter (S3/MinIO) would serve these instead.
  plug Plug.Static,
    at: "/uploads",
    from: {:kiln_cms, "priv/uploads"},
    gzip: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :kiln_cms
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, AshJsonApi.Plug.Parser, Absinthe.Plug.Parser],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # Strip a `/<locale>/…` prefix and set the locale before routing.
  plug KilnCMSWeb.Plugs.SetLocale
  plug KilnCMSWeb.Router
end
