defmodule KilnCMS.Repo.Migrations.AcupunctureNextOccurrenceIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:team_members) do
      add :next_occurrence_at, :utc_datetime_usec
    end

    create index(:team_members, [:org_id, :next_occurrence_at],
             name: "team_members_next_occurrence_index",
             where: "next_occurrence_at IS NOT NULL"
           )

    alter table(:testimonials) do
      add :next_occurrence_at, :utc_datetime_usec
    end

    create index(:testimonials, [:org_id, :next_occurrence_at],
             name: "testimonials_next_occurrence_index",
             where: "next_occurrence_at IS NOT NULL"
           )

    alter table(:conditions) do
      add :next_occurrence_at, :utc_datetime_usec
    end

    create index(:conditions, [:org_id, :next_occurrence_at],
             name: "conditions_next_occurrence_index",
             where: "next_occurrence_at IS NOT NULL"
           )

    alter table(:faqs) do
      add :next_occurrence_at, :utc_datetime_usec
    end

    create index(:faqs, [:org_id, :next_occurrence_at],
             name: "faqs_next_occurrence_index",
             where: "next_occurrence_at IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:faqs, [:org_id, :next_occurrence_at],
                     name: "faqs_next_occurrence_index"
                   )

    alter table(:faqs) do
      remove :next_occurrence_at
    end

    drop_if_exists index(:conditions, [:org_id, :next_occurrence_at],
                     name: "conditions_next_occurrence_index"
                   )

    alter table(:conditions) do
      remove :next_occurrence_at
    end

    drop_if_exists index(:testimonials, [:org_id, :next_occurrence_at],
                     name: "testimonials_next_occurrence_index"
                   )

    alter table(:testimonials) do
      remove :next_occurrence_at
    end

    drop_if_exists index(:team_members, [:org_id, :next_occurrence_at],
                     name: "team_members_next_occurrence_index"
                   )

    alter table(:team_members) do
      remove :next_occurrence_at
    end
  end
end
