defmodule KilnCMS.Repo.Migrations.AddAcupunctureContentTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:team_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "team_members_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :unpublish_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "team_members_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "team_members_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "team_members_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:team_members, [:slug, :locale], name: "team_members_slug_locale_lookup_index")

    create index(:team_members, ["title gin_trgm_ops"],
             name: "team_members_title_trgm_index",
             using: "gin"
           )

    create index(:team_members, ["embedding vector_cosine_ops"],
             name: "team_members_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:team_members, [:org_id, :slug, :locale],
             name: "team_members_unique_slug_index"
           )

    create table(:testimonials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "testimonials_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :unpublish_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "testimonials_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "testimonials_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "testimonials_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:testimonials, [:slug, :locale], name: "testimonials_slug_locale_lookup_index")

    create index(:testimonials, ["title gin_trgm_ops"],
             name: "testimonials_title_trgm_index",
             using: "gin"
           )

    create index(:testimonials, ["embedding vector_cosine_ops"],
             name: "testimonials_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:testimonials, [:org_id, :slug, :locale],
             name: "testimonials_unique_slug_index"
           )

    create table(:faqs_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :org_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "faqs_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create table(:conditions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "conditions_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :unpublish_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "conditions_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "conditions_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "conditions_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:conditions, [:slug, :locale], name: "conditions_slug_locale_lookup_index")

    create index(:conditions, ["title gin_trgm_ops"],
             name: "conditions_title_trgm_index",
             using: "gin"
           )

    create index(:conditions, ["embedding vector_cosine_ops"],
             name: "conditions_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:conditions, [:org_id, :slug, :locale],
             name: "conditions_unique_slug_index"
           )

    create table(:testimonials_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :org_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "testimonials_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create table(:faqs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "faqs_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :title, :text, null: false
      add :slug, :text, null: false
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :unpublish_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "faqs_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "faqs_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "faqs_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:faqs, [:slug, :locale], name: "faqs_slug_locale_lookup_index")

    create index(:faqs, ["title gin_trgm_ops"], name: "faqs_title_trgm_index", using: "gin")

    create index(:faqs, ["embedding vector_cosine_ops"],
             name: "faqs_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:faqs, [:org_id, :slug, :locale], name: "faqs_unique_slug_index")

    create table(:conditions_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :org_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "conditions_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create table(:team_members_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :org_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "team_members_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:team_members_versions, "team_members_versions_user_id_fkey")

    drop table(:team_members_versions)

    drop constraint(:conditions_versions, "conditions_versions_user_id_fkey")

    drop table(:conditions_versions)

    drop constraint(:faqs, "faqs_org_id_fkey")

    drop constraint(:faqs, "faqs_author_id_fkey")

    drop constraint(:faqs, "faqs_category_id_fkey")

    drop constraint(:faqs, "faqs_featured_image_id_fkey")

    drop_if_exists unique_index(:faqs, [:org_id, :slug, :locale], name: "faqs_unique_slug_index")

    drop_if_exists index(:faqs, ["embedding vector_cosine_ops"],
                     name: "faqs_embedding_hnsw_index"
                   )

    drop_if_exists index(:faqs, ["title gin_trgm_ops"], name: "faqs_title_trgm_index")

    drop_if_exists index(:faqs, [:slug, :locale], name: "faqs_slug_locale_lookup_index")

    drop table(:faqs)

    drop constraint(:testimonials_versions, "testimonials_versions_user_id_fkey")

    drop table(:testimonials_versions)

    drop constraint(:conditions, "conditions_org_id_fkey")

    drop constraint(:conditions, "conditions_author_id_fkey")

    drop constraint(:conditions, "conditions_category_id_fkey")

    drop constraint(:conditions, "conditions_featured_image_id_fkey")

    drop_if_exists unique_index(:conditions, [:org_id, :slug, :locale],
                     name: "conditions_unique_slug_index"
                   )

    drop_if_exists index(:conditions, ["embedding vector_cosine_ops"],
                     name: "conditions_embedding_hnsw_index"
                   )

    drop_if_exists index(:conditions, ["title gin_trgm_ops"], name: "conditions_title_trgm_index")

    drop_if_exists index(:conditions, [:slug, :locale],
                     name: "conditions_slug_locale_lookup_index"
                   )

    drop table(:conditions)

    drop constraint(:faqs_versions, "faqs_versions_user_id_fkey")

    drop table(:faqs_versions)

    drop constraint(:testimonials, "testimonials_org_id_fkey")

    drop constraint(:testimonials, "testimonials_author_id_fkey")

    drop constraint(:testimonials, "testimonials_category_id_fkey")

    drop constraint(:testimonials, "testimonials_featured_image_id_fkey")

    drop_if_exists unique_index(:testimonials, [:org_id, :slug, :locale],
                     name: "testimonials_unique_slug_index"
                   )

    drop_if_exists index(:testimonials, ["embedding vector_cosine_ops"],
                     name: "testimonials_embedding_hnsw_index"
                   )

    drop_if_exists index(:testimonials, ["title gin_trgm_ops"],
                     name: "testimonials_title_trgm_index"
                   )

    drop_if_exists index(:testimonials, [:slug, :locale],
                     name: "testimonials_slug_locale_lookup_index"
                   )

    drop table(:testimonials)

    drop constraint(:team_members, "team_members_org_id_fkey")

    drop constraint(:team_members, "team_members_author_id_fkey")

    drop constraint(:team_members, "team_members_category_id_fkey")

    drop constraint(:team_members, "team_members_featured_image_id_fkey")

    drop_if_exists unique_index(:team_members, [:org_id, :slug, :locale],
                     name: "team_members_unique_slug_index"
                   )

    drop_if_exists index(:team_members, ["embedding vector_cosine_ops"],
                     name: "team_members_embedding_hnsw_index"
                   )

    drop_if_exists index(:team_members, ["title gin_trgm_ops"],
                     name: "team_members_title_trgm_index"
                   )

    drop_if_exists index(:team_members, [:slug, :locale],
                     name: "team_members_slug_locale_lookup_index"
                   )

    drop table(:team_members)
  end
end
