defmodule KilnCMS.Repo.Migrations.AddAcupunctureSeoKeywords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:team_members) do
      add :seo_keywords, :text
    end

    alter table(:testimonials) do
      add :seo_keywords, :text
    end

    alter table(:conditions) do
      add :seo_keywords, :text
    end

    alter table(:faqs) do
      add :seo_keywords, :text
    end
  end

  def down do
    alter table(:faqs) do
      remove :seo_keywords
    end

    alter table(:conditions) do
      remove :seo_keywords
    end

    alter table(:testimonials) do
      remove :seo_keywords
    end

    alter table(:team_members) do
      remove :seo_keywords
    end
  end
end
