defmodule KilnCMS.Repo.Migrations.AddAcupuncturePathAlias do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:team_members) do
      add :path_alias, :text
    end

    create index(:team_members, [:path_alias],
             name: "team_members_path_alias_index",
             where: "path_alias IS NOT NULL"
           )

    alter table(:testimonials) do
      add :path_alias, :text
    end

    create index(:testimonials, [:path_alias],
             name: "testimonials_path_alias_index",
             where: "path_alias IS NOT NULL"
           )

    alter table(:conditions) do
      add :path_alias, :text
    end

    create index(:conditions, [:path_alias],
             name: "conditions_path_alias_index",
             where: "path_alias IS NOT NULL"
           )

    alter table(:faqs) do
      add :path_alias, :text
    end

    create index(:faqs, [:path_alias],
             name: "faqs_path_alias_index",
             where: "path_alias IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:faqs, [:path_alias], name: "faqs_path_alias_index")

    alter table(:faqs) do
      remove :path_alias
    end

    drop_if_exists index(:conditions, [:path_alias], name: "conditions_path_alias_index")

    alter table(:conditions) do
      remove :path_alias
    end

    drop_if_exists index(:testimonials, [:path_alias], name: "testimonials_path_alias_index")

    alter table(:testimonials) do
      remove :path_alias
    end

    drop_if_exists index(:team_members, [:path_alias], name: "team_members_path_alias_index")

    alter table(:team_members) do
      remove :path_alias
    end
  end
end
