defmodule KilnCMSWeb.Plugs.ApiDocs do
  @moduledoc """
  Serves the API documentation surface only where it is turned on (#567).

  Two routes describe the whole headless API:

    * `GET /api/json/open_api` — the OpenAPI 3 document, generated by
      `KilnCMSWeb.AshJsonApiRouter`;
    * `GET /api/json/swaggerui` — the interactive explorer over it.

  Both shipped unauthenticated in **every** environment, production included.
  Unlike `/dev/dashboard`, `/dev/mailbox`, `/admin` and the GraphQL playground
  they are not behind `dev_routes`, so they were live on every deployment.

  ## Disclosure, not access

  Every route the spec documents is still enforced by the Ash policies and the
  API key's access scope, so serving it grants nothing. What it does is remove
  the guesswork: since #330 the described surface includes the **write** routes,
  so the document is a complete, machine-readable map of the mutation API —
  which actions exist, what they accept, what they return.

  That is the same argument that already disabled GraphQL introspection in
  production (`KilnCMSWeb.GraphqlLimits.NoIntrospection`), and leaving a
  full OpenAPI document next to a disabled introspection endpoint was the
  inconsistency. The explorer carries a second, smaller reason: it needs a
  relaxed CSP allowing `https://cdnjs.cloudflare.com` for its bundle, and that
  policy is worth not shipping to production at all.

  ## Off in production, on everywhere else, and an operator can say otherwise

  `config :kiln_cms, :api_docs` — `true` by default, `false` in `:prod`,
  overridable at runtime with `API_DOCS_ENABLED`. An operator publishing a
  public API wants these on; the default should not assume they are.

  ## An API key opens the document, not the explorer

  With the flag off, a request to the spec path that carries a valid API key
  (`Authorization: Bearer kiln_…`, authenticated by `KilnCMSWeb.Plugs.ApiKeyAuth`
  earlier in the `:api` pipeline) is served anyway. That is what a client
  author needs to point codegen at their own production site — which has their
  own content types in it, unlike the stock copy committed at
  `docs/api/openapi.json` — and the disclosure argument above does not apply to
  someone an admin has already issued a credential to (minting keys is
  admin-only, see `KilnCMS.Accounts.ApiKey`). Any key will do, `read` or
  `read_write`: the document describes routes, and each route still answers to
  the key's own scope.

  A JWT does not open it. Open registration hands one to anybody who signs up
  as a viewer, so holding one says nothing about being an integration the site
  chose.

  The explorer stays closed either way. It is a browser page that cannot send
  an `Authorization` header on its own navigation, and its relaxed CSP is the
  part worth not shipping.

  ## 404, not 403

  A 403 confirms the route exists and is merely closed, which is the one bit of
  information a disabled docs endpoint should not volunteer. 404 is what any
  other unrouted path answers, so a disabled instance is indistinguishable from
  one built without the surface.

  The refusal is JSON for the spec and HTML for the explorer, matching what a
  caller asked for rather than what the plug happens to find convenient.
  """
  import Plug.Conn

  @doc false
  def init(opts), do: opts

  # The two paths this gates, as Phoenix splits them.
  #
  # Matched here rather than on a route of their own, because the spec is
  # served from *inside* the `forward` to `KilnCMSWeb.AshJsonApiRouter` — there
  # is no route in this application to hang a pipeline on. One plug that knows
  # both paths beats a second mechanism for the second route.
  @spec_path ~w(api json open_api)
  @explorer_path ~w(api json swaggerui)

  @doc false
  def call(%{path_info: path} = conn, _opts) do
    cond do
      enabled?() or not gated?(path) -> conn
      not explorer?(path) and KilnCMSWeb.ApiSpecs.api_key_caller?(conn) -> conn
      true -> refuse(conn, path)
    end
  end

  # Compared **decoded**, because that is what the router matched on and the two
  # must agree. `Phoenix.Router` decodes each segment to pick a route but leaves
  # `conn.path_info` raw, so a literal comparison here sees `%73waggerui` while
  # the `forward "/swaggerui"` sees `swaggerui` — and the gate is walked past by
  # percent-encoding a single character. Verified: with the flag off,
  # `/api/json/%73waggerui` served the whole explorer, relaxed CSP and all.
  defp gated?(path) do
    decoded = Enum.map(path, &URI.decode/1)
    decoded == @spec_path or match?(@explorer_path ++ _, decoded)
  rescue
    # `URI.decode/1` raises on malformed input like `%ZZ`. A path this plug
    # cannot read is a path it cannot clear, so it refuses — and refusing is
    # also what keeps a bad escape from 500ing a public route (#751).
    ArgumentError -> true
  end

  @doc """
  Whether the API documentation routes are served.

  Exported so the router and the tests read one answer rather than two
  spellings of the same `Application.get_env/3` — the drift that makes a
  security flag mean different things in different files.
  """
  @spec enabled?() :: boolean()
  def enabled?, do: Application.get_env(:kiln_cms, :api_docs, true)

  # `path_info` rather than the `accept` header: the explorer is a browser
  # document and the spec is JSON, and a caller who sends neither should still
  # get something parseable.
  defp refuse(conn, path) do
    if explorer?(path) do
      conn
      |> put_resp_content_type("text/html")
      |> send_resp(404, "<!DOCTYPE html><html><body><h1>Not Found</h1></body></html>")
      |> halt()
    else
      KilnCMSWeb.ApiError.send(conn, :not_found, "not_found", "Not found.") |> halt()
    end
  end

  defp explorer?(path) do
    match?(@explorer_path ++ _, Enum.map(path, &URI.decode/1))
  rescue
    ArgumentError -> false
  end
end
