defmodule KilnCMS.Repo.Migrations.ContentTreeParentAndPosition do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:faqs) do
      add :position, :bigint, null: false, default: 0

      add :parent_id,
          references(:faqs,
            column: :id,
            name: "faqs_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:testimonials) do
      add :position, :bigint, null: false, default: 0

      add :parent_id,
          references(:testimonials,
            column: :id,
            name: "testimonials_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:team_members) do
      add :position, :bigint, null: false, default: 0

      add :parent_id,
          references(:team_members,
            column: :id,
            name: "team_members_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:products) do
      add :position, :bigint, null: false, default: 0

      add :parent_id,
          references(:products,
            column: :id,
            name: "products_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:products, "products_parent_id_fkey")

    alter table(:products) do
      remove :parent_id
      remove :position
    end

    drop constraint(:team_members, "team_members_parent_id_fkey")

    alter table(:team_members) do
      remove :parent_id
      remove :position
    end

    drop constraint(:testimonials, "testimonials_parent_id_fkey")

    alter table(:testimonials) do
      remove :parent_id
      remove :position
    end

    drop constraint(:faqs, "faqs_parent_id_fkey")

    alter table(:faqs) do
      remove :parent_id
      remove :position
    end
  end
end
