defmodule KilnCMS.Repo.Migrations.ConsoleContentListIndexesOverlay do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:faqs, [:org_id, :updated_at, :id],
             name: "faqs_console_updated_index",
             concurrently: true
           )

    create index(:faqs, [:org_id, :title, :id],
             name: "faqs_console_title_index",
             concurrently: true
           )

    create index(:faqs, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
             name: "faqs_console_published_index",
             concurrently: true
           )

    create index(:testimonials, [:org_id, :updated_at, :id],
             name: "testimonials_console_updated_index",
             concurrently: true
           )

    create index(:testimonials, [:org_id, :title, :id],
             name: "testimonials_console_title_index",
             concurrently: true
           )

    create index(:testimonials, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
             name: "testimonials_console_published_index",
             concurrently: true
           )

    create index(:team_members, [:org_id, :updated_at, :id],
             name: "team_members_console_updated_index",
             concurrently: true
           )

    create index(:team_members, [:org_id, :title, :id],
             name: "team_members_console_title_index",
             concurrently: true
           )

    create index(:team_members, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
             name: "team_members_console_published_index",
             concurrently: true
           )

    create index(:products, [:org_id, :updated_at, :id],
             name: "products_console_updated_index",
             concurrently: true
           )

    create index(:products, [:org_id, :title, :id],
             name: "products_console_title_index",
             concurrently: true
           )

    create index(:products, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
             name: "products_console_published_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists index(:products, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
                     name: "products_console_published_index"
                   )

    drop_if_exists index(:products, [:org_id, :title, :id], name: "products_console_title_index")

    drop_if_exists index(:products, [:org_id, :updated_at, :id],
                     name: "products_console_updated_index"
                   )

    drop_if_exists index(:team_members, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
                     name: "team_members_console_published_index"
                   )

    drop_if_exists index(:team_members, [:org_id, :title, :id],
                     name: "team_members_console_title_index"
                   )

    drop_if_exists index(:team_members, [:org_id, :updated_at, :id],
                     name: "team_members_console_updated_index"
                   )

    drop_if_exists index(:testimonials, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
                     name: "testimonials_console_published_index"
                   )

    drop_if_exists index(:testimonials, [:org_id, :title, :id],
                     name: "testimonials_console_title_index"
                   )

    drop_if_exists index(:testimonials, [:org_id, :updated_at, :id],
                     name: "testimonials_console_updated_index"
                   )

    drop_if_exists index(:faqs, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
                     name: "faqs_console_published_index"
                   )

    drop_if_exists index(:faqs, [:org_id, :title, :id], name: "faqs_console_title_index")

    drop_if_exists index(:faqs, [:org_id, :updated_at, :id], name: "faqs_console_updated_index")
  end
end
