defmodule KilnCMS.Repo.Migrations.ContentTreeParentAndPositionOverlay1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:faqs, [:parent_id], name: "faqs_parent_lookup_index", concurrently: true)

    create index(:testimonials, [:parent_id],
             name: "testimonials_parent_lookup_index",
             concurrently: true
           )

    create index(:team_members, [:parent_id],
             name: "team_members_parent_lookup_index",
             concurrently: true
           )

    create index(:products, [:parent_id],
             name: "products_parent_lookup_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists index(:products, [:parent_id], name: "products_parent_lookup_index")

    drop_if_exists index(:team_members, [:parent_id], name: "team_members_parent_lookup_index")

    drop_if_exists index(:testimonials, [:parent_id], name: "testimonials_parent_lookup_index")

    drop_if_exists index(:faqs, [:parent_id], name: "faqs_parent_lookup_index")
  end
end
