defmodule KilnCMS.Repo.Migrations.AddSyncVersionIndexOverlay do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:team_members_versions, [:org_id, :version_inserted_at])

    create index(:testimonials_versions, [:org_id, :version_inserted_at])

    create index(:faqs_versions, [:org_id, :version_inserted_at])

    create index(:products_versions, [:org_id, :version_inserted_at])
  end

  def down do
    drop_if_exists index(:products_versions, [:org_id, :version_inserted_at])

    drop_if_exists index(:faqs_versions, [:org_id, :version_inserted_at])

    drop_if_exists index(:testimonials_versions, [:org_id, :version_inserted_at])

    drop_if_exists index(:team_members_versions, [:org_id, :version_inserted_at])
  end
end
