defmodule KilnCMS.Repo.Migrations.ContentAccessPassword do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:team_members) do
      add :access_password_hash, :text
      add :password_fingerprint, :text
    end

    alter table(:testimonials) do
      add :access_password_hash, :text
      add :password_fingerprint, :text
    end

    alter table(:conditions) do
      add :access_password_hash, :text
      add :password_fingerprint, :text
    end

    alter table(:faqs) do
      add :access_password_hash, :text
      add :password_fingerprint, :text
    end
  end

  def down do
    alter table(:faqs) do
      remove :password_fingerprint
      remove :access_password_hash
    end

    alter table(:conditions) do
      remove :password_fingerprint
      remove :access_password_hash
    end

    alter table(:testimonials) do
      remove :password_fingerprint
      remove :access_password_hash
    end

    alter table(:team_members) do
      remove :password_fingerprint
      remove :access_password_hash
    end
  end
end
