defmodule KilnCMS.Repo.Migrations.AddProposedPublishAtExample do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:faqs) do
      add :proposed_publish_at, :utc_datetime_usec
    end

    alter table(:testimonials) do
      add :proposed_publish_at, :utc_datetime_usec
    end

    alter table(:team_members) do
      add :proposed_publish_at, :utc_datetime_usec
    end

    alter table(:products) do
      add :proposed_publish_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:products) do
      remove :proposed_publish_at
    end

    alter table(:team_members) do
      remove :proposed_publish_at
    end

    alter table(:testimonials) do
      remove :proposed_publish_at
    end

    alter table(:faqs) do
      remove :proposed_publish_at
    end
  end
end
