defmodule KilnCMS.Repo.Migrations.ChainFoldOrder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:faqs_versions) do
      add :chain_signature, :text
      add :chain_key_id, :text
    end

    alter table(:testimonials_versions) do
      add :chain_signature, :text
      add :chain_key_id, :text
    end

    alter table(:products_versions) do
      add :chain_signature, :text
      add :chain_key_id, :text
    end

    alter table(:team_members_versions) do
      add :chain_signature, :text
      add :chain_key_id, :text
    end
  end

  def down do
    alter table(:team_members_versions) do
      remove :chain_key_id
      remove :chain_signature
    end

    alter table(:products_versions) do
      remove :chain_key_id
      remove :chain_signature
    end

    alter table(:testimonials_versions) do
      remove :chain_key_id
      remove :chain_signature
    end

    alter table(:faqs_versions) do
      remove :chain_key_id
      remove :chain_signature
    end
  end
end
