defmodule KilnCMS.Repo.Migrations.AddWorkingCopyOverlay do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :working_title, :text
      add :working_blocks, {:array, :map}, null: false, default: []
      add :working_copy_at, :utc_datetime_usec
    end

    alter table(:team_members) do
      add :working_title, :text
      add :working_blocks, {:array, :map}, null: false, default: []
      add :working_copy_at, :utc_datetime_usec
    end

    alter table(:testimonials) do
      add :working_title, :text
      add :working_blocks, {:array, :map}, null: false, default: []
      add :working_copy_at, :utc_datetime_usec
    end

    alter table(:faqs) do
      add :working_title, :text
      add :working_blocks, {:array, :map}, null: false, default: []
      add :working_copy_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:faqs) do
      remove :working_copy_at
      remove :working_blocks
      remove :working_title
    end

    alter table(:testimonials) do
      remove :working_copy_at
      remove :working_blocks
      remove :working_title
    end

    alter table(:team_members) do
      remove :working_copy_at
      remove :working_blocks
      remove :working_title
    end

    alter table(:products) do
      remove :working_copy_at
      remove :working_blocks
      remove :working_title
    end
  end
end
