defmodule KilnCMS.Repo.Migrations.WorkingCopyBaseExample do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:faqs) do
      add :working_base, :map, null: false, default: %{}
    end

    alter table(:testimonials) do
      add :working_base, :map, null: false, default: %{}
    end

    alter table(:team_members) do
      add :working_base, :map, null: false, default: %{}
    end

    alter table(:products) do
      add :working_base, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:products) do
      remove :working_base
    end

    alter table(:team_members) do
      remove :working_base
    end

    alter table(:testimonials) do
      remove :working_base
    end

    alter table(:faqs) do
      remove :working_base
    end
  end
end
