defmodule KilnCMS.Repo.Migrations.SearchTitleLexemesIndexExample do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:faqs, ["tsvector_to_array(to_tsvector(kiln_regconfig(locale), title))"],
             name: "faqs_title_lexemes_index",
             concurrently: true,
             using: "gin"
           )

    create index(:testimonials, ["tsvector_to_array(to_tsvector(kiln_regconfig(locale), title))"],
             name: "testimonials_title_lexemes_index",
             concurrently: true,
             using: "gin"
           )

    create index(:team_members, ["tsvector_to_array(to_tsvector(kiln_regconfig(locale), title))"],
             name: "team_members_title_lexemes_index",
             concurrently: true,
             using: "gin"
           )

    create index(:products, ["tsvector_to_array(to_tsvector(kiln_regconfig(locale), title))"],
             name: "products_title_lexemes_index",
             concurrently: true,
             using: "gin"
           )
  end

  def down do
    drop_if_exists index(
                     :products,
                     ["tsvector_to_array(to_tsvector(kiln_regconfig(locale), title))"],
                     name: "products_title_lexemes_index"
                   )

    drop_if_exists index(
                     :team_members,
                     ["tsvector_to_array(to_tsvector(kiln_regconfig(locale), title))"],
                     name: "team_members_title_lexemes_index"
                   )

    drop_if_exists index(
                     :testimonials,
                     ["tsvector_to_array(to_tsvector(kiln_regconfig(locale), title))"],
                     name: "testimonials_title_lexemes_index"
                   )

    drop_if_exists index(:faqs, ["tsvector_to_array(to_tsvector(kiln_regconfig(locale), title))"],
                     name: "faqs_title_lexemes_index"
                   )
  end
end
