import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database
config :kiln_cms, KilnCMS.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "kiln_cms_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :kiln_cms, KilnCMSWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "OluEpbxI8ouMfdhAmfUQ2mt0H/1ewFUIRNXmQeFLrFo8AxZGW+8wXiwDpKfV3mNF",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:kiln_cms, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:kiln_cms, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :kiln_cms, KilnCMSWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/kiln_cms_web/router\.ex$"E,
      ~r"lib/kiln_cms_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :kiln_cms, dev_routes: true, token_signing_secret: "DYgVqiH9UCH9+tNBUTSxpjj9sjIclKww"

# Default the AshAdmin actor to the signed-in user so policy-driven admin
# actions reflect real RBAC during inspection (issue #24). Dev-only: the
# `/admin` routes themselves only exist when `dev_routes` is enabled.
config :ash_admin, :actor_plug, KilnCMSWeb.AshAdmin.ActorPlug

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Use the EXLA (XLA) backend for Nx locally — the :exla dep is only available in
# dev/test. Prod/e2e fall back to Nx.BinaryBackend (see config/config.exs).
config :nx, default_backend: EXLA.Backend

# Collaborative-editing CRDT prototype (KilnCMS.Collab.Crdt) — dev-only while
# it's a spike; the collab channel refuses joins when this is off.
config :kiln_cms, :collab_prototype, true

# All localized UI locales enabled in dev so the fr/es translations can be
# exercised locally (prod opts in via its own config).
config :kiln_cms, :i18n, default_locale: "en", locales: ["en", "fr", "es"]
