import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :kiln_cms, KilnCMSWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. Note `:force_ssl` is required to be set at compile-time.
#
# Excluded, so they answer over plain HTTP instead of a 301:
#
#   * hosts `localhost`/`127.0.0.1` — the image's own HEALTHCHECK (Dockerfile).
#   * paths `/live` and `/up` — a PaaS health checker (Render, Railway, Fly,
#     DigitalOcean) probes the container directly, by its internal address,
#     with no `X-Forwarded-Proto`, so it would otherwise get a redirect and
#     read the deploy as unhealthy (#1529). Both carry no data: `/live` is a
#     bare 200 and `/up` a status. `/ready` returns a monitoring payload and
#     stays behind HTTPS. Pinned by test/config/prod_force_ssl_test.exs.
config :kiln_cms, KilnCMSWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      hosts: ["localhost", "127.0.0.1"],
      paths: ["/live", "/up"]
    ]
  ]

# Mark the session cookie `Secure` in production (traffic is HTTPS via
# `force_ssl`). Compile-time, read by `KilnCMSWeb.Endpoint`'s `@session_options`.
config :kiln_cms, :secure_session_cookie, true

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Never expose dev-only tooling (AshAdmin, LiveDashboard, Swoosh mailbox) in a
# production build. Set explicitly (not just left unset) and asserted again at
# runtime in KilnCMS.Application.
config :kiln_cms, dev_routes: false, mailbox_preview: false

# Disable GraphQL schema introspection in production (reconnaissance hardening).
config :kiln_cms, :graphql_introspection, false

# Same reasoning, same posture: the OpenAPI document and its explorer describe
# the whole headless API — including the write routes since #330 — so they are
# off unless an operator turns them on with `API_DOCS_ENABLED` (#567).
config :kiln_cms, :api_docs, false

# Webhook targets must be HTTPS and must not resolve to private addresses.
config :kiln_cms, KilnCMS.Webhooks.SafeUrl, require_https: true, resolve_dns: true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
