defmodule KilnCMS.SchemaExport.TypeScript do
  @moduledoc """
  `.d.ts` emitter over the exported JSON Schema (#430).

  The issue left this optional — "or leave it to json-schema-to-typescript
  downstream". It ships because the downstream tool is a Node dependency in a
  build that may not otherwise have one, and because generating from our own
  document is a dozen lines of formatting rather than a toolchain.

  It reads the **JSON Schema document** rather than the block registry, so the
  two emitters cannot disagree about what a field is: everything
  `Kiln.Block.JsonSchema` and `KilnCMS.SchemaExport` decide (nullability,
  enums, the recursive block union, closed custom-field maps) is already baked
  into the document by the time this sees it.

  Anything the emitter cannot express — `format`, `minimum`, `default` — is
  dropped rather than approximated. A `.d.ts` that lies about a constraint is
  worse than one that is merely loose about it.
  """

  @doc """
  Emit TypeScript declarations for a schema document from
  `KilnCMS.SchemaExport.json_schema/1`.
  """
  @spec emit(map()) :: String.t()
  def emit(document) do
    defs = Map.get(document, "$defs", %{})

    {block_defs, rest} = Enum.split_with(defs, fn {name, _} -> block_def?(name) end)
    {content_defs, shared_defs} = Enum.split_with(rest, fn {name, _} -> content_def?(name) end)

    [
      header(document),
      section("Shared", shared_defs |> Enum.reject(&union?/1) |> declarations()),
      section("Blocks", block_defs |> Enum.reject(&union?/1) |> declarations()),
      section("Block union", [union_alias("KilnBlock", Map.get(defs, "block"))]),
      section("Documents", declarations(content_defs)),
      section(
        "Document union",
        [document_union(Enum.map(content_defs, fn {name, _} -> name end))]
      )
    ]
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n")
  end

  defp header(document) do
    kiln = Map.get(document, "x-kiln", %{})

    """
    // Generated by `mix kiln.export.schema --format ts`. Do not edit.
    //
    // The `:json` fired-artifact shape served by
    // `GET /api/content/:type/:slug?surface=json`.
    //
    // Artifact format version: #{Map.get(kiln, "artifact_format_version", "unknown")}
    """
  end

  defp section(title, declarations) do
    case Enum.reject(declarations, &(&1 == "")) do
      [] ->
        ""

      declarations ->
        rule = String.duplicate("-", max(0, 60 - String.length(title)))
        "\n// -- #{title} #{rule}\n\n" <> Enum.join(declarations, "\n\n") <> "\n"
    end
  end

  defp declarations(defs) do
    defs
    |> Enum.sort_by(fn {name, _} -> name end)
    |> Enum.map(fn {name, schema} -> interface(type_name(name), schema) end)
  end

  defp union?({_name, schema}), do: Map.has_key?(schema, "oneOf")

  # A document with no block union at all (a hand-assembled `$defs`, or a future
  # partial export) simply has no alias to emit.
  defp union_alias(_name, nil), do: ""

  defp union_alias(name, %{"oneOf" => refs}) do
    members = Enum.map_join(refs, "\n  | ", &(&1 |> ref_target() |> type_name()))
    "export type #{name} =\n  | #{members};"
  end

  defp document_union([]), do: ""

  defp document_union(names) do
    members = names |> Enum.sort() |> Enum.map_join("\n  | ", &type_name/1)
    "export type KilnDocument =\n  | #{members};"
  end

  defp interface(name, %{"properties" => properties} = schema) do
    required = MapSet.new(Map.get(schema, "required", []))

    body =
      properties
      |> Enum.sort_by(fn {key, _} -> key end)
      |> Enum.map_join("\n", fn {key, value} ->
        optional = if MapSet.member?(required, key), do: "", else: "?"
        "  #{property_key(key)}#{optional}: #{ts_type(value)};"
      end)

    doc = doc_comment(schema)

    extra =
      if Map.get(schema, "additionalProperties") == false,
        do: "",
        else: "\n  [k: string]: unknown;"

    "#{doc}export interface #{name} {\n#{body}#{extra}\n}"
  end

  # A schema with no `properties` (a lone `const`, an open object) has no
  # interface to write — alias it to `unknown` rather than emitting `{}`, which
  # TypeScript treats as "anything but null".
  defp interface(name, schema), do: "#{doc_comment(schema)}export type #{name} = unknown;"

  defp doc_comment(schema) do
    case Map.get(schema, "description") do
      nil -> ""
      description -> "/** #{String.replace(description, "*/", "*\\/")} */\n"
    end
  end

  # ── type mapping ────────────────────────────────────────────────────────────

  defp ts_type(%{"$ref" => _} = schema), do: schema |> ref_target() |> type_name()

  defp ts_type(%{"oneOf" => refs}),
    do: Enum.map_join(refs, " | ", &(&1 |> ref_target() |> type_name()))

  # Ahead of `const`/`enum`, not after. A nullable enum carries both keywords,
  # and matching the value clause first would emit `"free" | "pro"` for a
  # `["string", "null"]` field — telling a consumer that `?.` is redundant on a
  # value delivery really does send as null.
  defp ts_type(%{"type" => types} = schema) when is_list(types) do
    {nulls, rest} = Enum.split_with(types, &(&1 == "null"))
    members = Enum.map(rest, &ts_type(Map.put(schema, "type", &1)))
    Enum.join(members ++ Enum.map(nulls, fn _ -> "null" end), " | ")
  end

  defp ts_type(%{"const" => value}), do: literal(value)

  defp ts_type(%{"enum" => values}), do: Enum.map_join(values, " | ", &literal/1)

  defp ts_type(%{"type" => "array"} = schema),
    do: "Array<" <> ts_type(Map.get(schema, "items", %{})) <> ">"

  defp ts_type(%{"type" => "object"} = schema) do
    case Map.get(schema, "properties") do
      nil -> "Record<string, unknown>"
      properties -> inline_object(properties, MapSet.new(Map.get(schema, "required", [])))
    end
  end

  defp ts_type(%{"type" => "integer"}), do: "number"
  defp ts_type(%{"type" => "number"}), do: "number"
  defp ts_type(%{"type" => "boolean"}), do: "boolean"
  defp ts_type(%{"type" => "string"}), do: "string"
  defp ts_type(%{"type" => "null"}), do: "null"
  defp ts_type(_schema), do: "unknown"

  defp inline_object(properties, required) do
    body =
      properties
      |> Enum.sort_by(fn {key, _} -> key end)
      |> Enum.map_join("; ", fn {key, value} ->
        optional = if MapSet.member?(required, key), do: "", else: "?"
        "#{property_key(key)}#{optional}: #{ts_type(value)}"
      end)

    "{ " <> body <> " }"
  end

  defp literal(value) when is_binary(value), do: ~s(") <> escape(value) <> ~s(")
  defp literal(value), do: to_string(value)

  # Custom-field names and `:select` options are admin input with no charset
  # validation, so a backslash or a newline in one would otherwise emit a
  # `.d.ts` that silently changes meaning (`C:\reports` → `C:reports`) or does
  # not parse at all. Backslash first, or it would re-escape the escapes.
  defp escape(value) do
    value
    |> String.replace("\\", "\\\\")
    |> String.replace(~s("), ~s(\\"))
    |> String.replace("\n", "\\n")
    |> String.replace("\r", "\\r")
    |> String.replace("\t", "\\t")
  end

  # ── naming ──────────────────────────────────────────────────────────────────

  defp ref_target(%{"$ref" => ref}), do: ref |> String.split("/") |> List.last()

  # `block_rich_text` → `RichTextBlock`, `content_post` → `PostDocument`,
  # `portable_text_block` → `PortableTextBlock`, `block` → `KilnBlock`.
  defp type_name("block"), do: "KilnBlock"

  defp type_name("block_" <> rest), do: pascal(rest) <> "Block"
  defp type_name("content_" <> rest), do: pascal(rest) <> "Document"
  defp type_name(name), do: pascal(name)

  defp pascal(name), do: Kiln.Block.JsonSchema.pascal(name)

  # A key that is not a plain identifier has to be quoted, or the declaration
  # will not parse. Custom-field names are admin input, so this is not
  # hypothetical.
  defp property_key(key) do
    if Regex.match?(~r/^[A-Za-z_$][A-Za-z0-9_$]*$/, key),
      do: key,
      else: ~s(") <> escape(key) <> ~s(")
  end

  defp block_def?("block_" <> _), do: true
  defp block_def?(_), do: false

  defp content_def?(name), do: String.starts_with?(name, "content_")
end
