defmodule KilnCMS.Repo.Migrations.ReverifyAppIcon do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:site_branding) do
      add :app_icon_verify_failures, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:site_branding) do
      remove :app_icon_verify_failures
    end
  end
end
