defmodule KilnCMS.Repo.Migrations.AddPathAlias do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:entries) do
      add :path_alias, :text
    end

    create index(:entries, [:path_alias],
             name: "entries_path_alias_index",
             where: "path_alias IS NOT NULL"
           )

    alter table(:posts) do
      add :path_alias, :text
    end

    create index(:posts, [:path_alias],
             name: "posts_path_alias_index",
             where: "path_alias IS NOT NULL"
           )

    alter table(:pages) do
      add :path_alias, :text
    end

    create index(:pages, [:path_alias],
             name: "pages_path_alias_index",
             where: "path_alias IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:pages, [:path_alias], name: "pages_path_alias_index")

    alter table(:pages) do
      remove :path_alias
    end

    drop_if_exists index(:posts, [:path_alias], name: "posts_path_alias_index")

    alter table(:posts) do
      remove :path_alias
    end

    drop_if_exists index(:entries, [:path_alias], name: "entries_path_alias_index")

    alter table(:entries) do
      remove :path_alias
    end
  end
end
