defmodule KilnCMS.Repo.Migrations.AddSiteAiProviders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_ai_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_ai_providers_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:site_ai_providers, [:org_id],
             name: "site_ai_providers_one_per_org_index"
           )

    alter table(:site_ai_providers) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enabled, :boolean, null: false, default: true
      add :provider, :text, null: false, default: "anthropic"
      add :base_url, :text
      add :seo_model, :text
      add :assist_model, :text
      add :ask_model, :text
      add :api_key_encrypted, :binary
    end

    create constraint(:site_ai_providers, :site_ai_provider_provider_must_be_known,
             check: """
               provider IN ('anthropic', 'openai', 'google', 'mistral', 'groq', 'openrouter', 'xai', 'openai_compatible')
             """
           )
  end

  def down do
    drop_if_exists constraint(:site_ai_providers, :site_ai_provider_provider_must_be_known)

    drop constraint(:site_ai_providers, "site_ai_providers_org_id_fkey")

    alter table(:site_ai_providers) do
      remove :api_key_encrypted
      remove :ask_model
      remove :assist_model
      remove :seo_model
      remove :base_url
      remove :provider
      remove :enabled
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:site_ai_providers, [:org_id],
                     name: "site_ai_providers_one_per_org_index"
                   )

    drop table(:site_ai_providers)
  end
end
