defmodule KilnCMS.Repo.Migrations.PolymorphicRelationships do
  @moduledoc """
  Replaces the per-type join tables (`page_tags`, `post_tags`, `related_pages`,
  `related_posts`) with two shared polymorphic tables: `taggings` (tag ⇄ any
  content record) and `content_links` (any content record ⇄ any content record,
  with a `kind`). Existing links are copied across before the old tables are
  dropped.

  The schema portions were generated by `mix ash.codegen`; the data-copy and the
  old-table drops are added by hand (codegen can't move data, and its drop
  prompts can't be answered in a non-interactive run).
  """

  use Ecto.Migration

  def up do
    create table(:taggings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject_id, :uuid, null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "taggings_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:taggings, [:subject_id, :tag_id], name: "taggings_unique_link_index")

    create table(:content_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_id, :uuid, null: false
      add :target_id, :uuid, null: false
      add :kind, :text, null: false, default: "related"
      add :position, :bigint, null: false, default: 0
    end

    create unique_index(:content_links, [:source_id, :target_id, :kind],
             name: "content_links_unique_link_index"
           )

    # Carry existing links across into the polymorphic tables.
    execute """
    INSERT INTO taggings (id, subject_id, tag_id)
    SELECT gen_random_uuid(), page_id, tag_id FROM page_tags
    UNION ALL
    SELECT gen_random_uuid(), post_id, tag_id FROM post_tags
    ON CONFLICT DO NOTHING
    """

    execute """
    INSERT INTO content_links (id, source_id, target_id, kind, position)
    SELECT gen_random_uuid(), source_id, related_id, 'related', 0 FROM related_pages
    UNION ALL
    SELECT gen_random_uuid(), source_id, related_id, 'related', 0 FROM related_posts
    ON CONFLICT DO NOTHING
    """

    drop table(:page_tags)
    drop table(:post_tags)
    drop table(:related_pages)
    drop table(:related_posts)
  end

  def down do
    # Recreate the per-type join tables…
    create table(:page_tags, primary_key: false) do
      add :page_id,
          references(:pages, column: :id, type: :uuid, prefix: "public", on_delete: :delete_all),
          primary_key: true,
          null: false

      add :tag_id,
          references(:tags, column: :id, type: :uuid, prefix: "public", on_delete: :delete_all),
          primary_key: true,
          null: false
    end

    create table(:post_tags, primary_key: false) do
      add :post_id,
          references(:posts, column: :id, type: :uuid, prefix: "public", on_delete: :delete_all),
          primary_key: true,
          null: false

      add :tag_id,
          references(:tags, column: :id, type: :uuid, prefix: "public", on_delete: :delete_all),
          primary_key: true,
          null: false
    end

    create table(:related_pages, primary_key: false) do
      add :source_id,
          references(:pages, column: :id, type: :uuid, prefix: "public", on_delete: :delete_all),
          primary_key: true,
          null: false

      add :related_id,
          references(:pages, column: :id, type: :uuid, prefix: "public", on_delete: :delete_all),
          primary_key: true,
          null: false
    end

    create table(:related_posts, primary_key: false) do
      add :source_id,
          references(:posts, column: :id, type: :uuid, prefix: "public", on_delete: :delete_all),
          primary_key: true,
          null: false

      add :related_id,
          references(:posts, column: :id, type: :uuid, prefix: "public", on_delete: :delete_all),
          primary_key: true,
          null: false
    end

    # …and copy links back, resolving each polymorphic id to its content type by
    # which table it exists in.
    execute """
    INSERT INTO page_tags (page_id, tag_id)
    SELECT subject_id, tag_id FROM taggings WHERE subject_id IN (SELECT id FROM pages)
    ON CONFLICT DO NOTHING
    """

    execute """
    INSERT INTO post_tags (post_id, tag_id)
    SELECT subject_id, tag_id FROM taggings WHERE subject_id IN (SELECT id FROM posts)
    ON CONFLICT DO NOTHING
    """

    execute """
    INSERT INTO related_pages (source_id, related_id)
    SELECT source_id, target_id FROM content_links
    WHERE kind = 'related' AND source_id IN (SELECT id FROM pages)
    ON CONFLICT DO NOTHING
    """

    execute """
    INSERT INTO related_posts (source_id, related_id)
    SELECT source_id, target_id FROM content_links
    WHERE kind = 'related' AND source_id IN (SELECT id FROM posts)
    ON CONFLICT DO NOTHING
    """

    drop_if_exists unique_index(:content_links, [:source_id, :target_id, :kind],
                     name: "content_links_unique_link_index"
                   )

    drop table(:content_links)

    drop constraint(:taggings, "taggings_tag_id_fkey")

    drop_if_exists unique_index(:taggings, [:subject_id, :tag_id],
                     name: "taggings_unique_link_index"
                   )

    drop table(:taggings)
  end
end
