defmodule KilnCMS.Repo.Migrations.NextOccurrenceIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:entries) do
      add :next_occurrence_at, :utc_datetime_usec
    end

    create index(:entries, [:org_id, :next_occurrence_at],
             name: "entries_next_occurrence_index",
             where: "next_occurrence_at IS NOT NULL"
           )

    alter table(:posts) do
      add :next_occurrence_at, :utc_datetime_usec
    end

    create index(:posts, [:org_id, :next_occurrence_at],
             name: "posts_next_occurrence_index",
             where: "next_occurrence_at IS NOT NULL"
           )

    alter table(:pages) do
      add :next_occurrence_at, :utc_datetime_usec
    end

    create index(:pages, [:org_id, :next_occurrence_at],
             name: "pages_next_occurrence_index",
             where: "next_occurrence_at IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:pages, [:org_id, :next_occurrence_at],
                     name: "pages_next_occurrence_index"
                   )

    alter table(:pages) do
      remove :next_occurrence_at
    end

    drop_if_exists index(:posts, [:org_id, :next_occurrence_at],
                     name: "posts_next_occurrence_index"
                   )

    alter table(:posts) do
      remove :next_occurrence_at
    end

    drop_if_exists index(:entries, [:org_id, :next_occurrence_at],
                     name: "entries_next_occurrence_index"
                   )

    alter table(:entries) do
      remove :next_occurrence_at
    end
  end
end
