defmodule KilnCMS.Repo.Migrations.AddFunnelCompletionGoal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:content_experiments) do
      add :goal_funnel_id, :uuid
    end
  end

  def down do
    alter table(:content_experiments) do
      remove :goal_funnel_id
    end
  end
end
