defmodule KilnCMS.Repo.Migrations.PublicThemeLayer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:site_branding) do
      add :theme, :text
      add :header_menu_key, :text
      add :footer_menu_key, :text
    end

    alter table(:site_code_injection) do
      add :custom_css, :text
    end
  end

  def down do
    alter table(:site_code_injection) do
      remove :custom_css
    end

    alter table(:site_branding) do
      remove :footer_menu_key
      remove :header_menu_key
      remove :theme
    end
  end
end
