defmodule KilnCMS.Repo.Migrations.AddOrgMembershipOrgIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:org_memberships, [:organization_id])
  end

  def down do
    drop_if_exists index(:org_memberships, [:organization_id])
  end
end
