defmodule KilnCMS.Repo.Migrations.AddContentLifecycles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:entries) do
      add :expiry_action, :text, null: false, default: "unpublish"
      add :review_after_days, :bigint
      add :last_reviewed_at, :utc_datetime_usec
    end

    create index(:entries, [:org_id, :last_reviewed_at],
             name: "entries_last_reviewed_at_index",
             where: "review_after_days IS NOT NULL AND state = 'published'"
           )

    create index(:entries, [:org_id, :unpublish_at],
             name: "entries_unpublish_at_index",
             where: "unpublish_at IS NOT NULL AND state = 'published'"
           )

    alter table(:posts) do
      add :expiry_action, :text, null: false, default: "unpublish"
      add :review_after_days, :bigint
      add :last_reviewed_at, :utc_datetime_usec
    end

    create index(:posts, [:org_id, :last_reviewed_at],
             name: "posts_last_reviewed_at_index",
             where: "review_after_days IS NOT NULL AND state = 'published'"
           )

    create index(:posts, [:org_id, :unpublish_at],
             name: "posts_unpublish_at_index",
             where: "unpublish_at IS NOT NULL AND state = 'published'"
           )

    alter table(:type_definitions) do
      add :default_review_after_days, :bigint
    end

    alter table(:pages) do
      add :expiry_action, :text, null: false, default: "unpublish"
      add :review_after_days, :bigint
      add :last_reviewed_at, :utc_datetime_usec
    end

    create index(:pages, [:org_id, :last_reviewed_at],
             name: "pages_last_reviewed_at_index",
             where: "review_after_days IS NOT NULL AND state = 'published'"
           )

    create index(:pages, [:org_id, :unpublish_at],
             name: "pages_unpublish_at_index",
             where: "unpublish_at IS NOT NULL AND state = 'published'"
           )
  end

  def down do
    drop_if_exists index(:pages, [:org_id, :unpublish_at], name: "pages_unpublish_at_index")

    drop_if_exists index(:pages, [:org_id, :last_reviewed_at],
                     name: "pages_last_reviewed_at_index"
                   )

    alter table(:pages) do
      remove :last_reviewed_at
      remove :review_after_days
      remove :expiry_action
    end

    alter table(:type_definitions) do
      remove :default_review_after_days
    end

    drop_if_exists index(:posts, [:org_id, :unpublish_at], name: "posts_unpublish_at_index")

    drop_if_exists index(:posts, [:org_id, :last_reviewed_at],
                     name: "posts_last_reviewed_at_index"
                   )

    alter table(:posts) do
      remove :last_reviewed_at
      remove :review_after_days
      remove :expiry_action
    end

    drop_if_exists index(:entries, [:org_id, :unpublish_at], name: "entries_unpublish_at_index")

    drop_if_exists index(:entries, [:org_id, :last_reviewed_at],
                     name: "entries_last_reviewed_at_index"
                   )

    alter table(:entries) do
      remove :last_reviewed_at
      remove :review_after_days
      remove :expiry_action
    end
  end
end
