defmodule KilnCMS.Repo.Migrations.AddFieldTargetType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:field_definitions) do
      add :target_type, :text
    end
  end

  def down do
    alter table(:field_definitions) do
      remove :target_type
    end
  end
end
