defmodule KilnCMS.Repo.Migrations.AddScheduledUnpublishVerscienta do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:clinics) do
      add :unpublish_at, :utc_datetime_usec
    end

    alter table(:conditions) do
      add :unpublish_at, :utc_datetime_usec
    end

    alter table(:practitioners) do
      add :unpublish_at, :utc_datetime_usec
    end

    alter table(:modalities) do
      add :unpublish_at, :utc_datetime_usec
    end

    alter table(:herbs) do
      add :unpublish_at, :utc_datetime_usec
    end

    alter table(:formulas) do
      add :unpublish_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:formulas) do
      remove :unpublish_at
    end

    alter table(:herbs) do
      remove :unpublish_at
    end

    alter table(:modalities) do
      remove :unpublish_at
    end

    alter table(:practitioners) do
      remove :unpublish_at
    end

    alter table(:conditions) do
      remove :unpublish_at
    end

    alter table(:clinics) do
      remove :unpublish_at
    end
  end
end
