defmodule KilnCMS.Repo.Migrations.SiteSuppressedRecipients do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_suppressed_recipients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_suppressed_recipients_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :email, :citext, null: false
    end

    create unique_index(:site_suppressed_recipients, [:org_id, :email],
             name: "site_suppressed_recipients_unique_site_email_index"
           )

    alter table(:site_suppressed_recipients) do
      add :reason, :text
      add :last_failure_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:site_suppressed_recipients, "site_suppressed_recipients_org_id_fkey")

    alter table(:site_suppressed_recipients) do
      remove :updated_at
      remove :inserted_at
      remove :last_failure_at
      remove :reason
    end

    drop_if_exists unique_index(:site_suppressed_recipients, [:org_id, :email],
                     name: "site_suppressed_recipients_unique_site_email_index"
                   )

    drop table(:site_suppressed_recipients)
  end
end
