defmodule KilnCMS.Repo.Migrations.AddProposedPublishAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pages) do
      add :proposed_publish_at, :utc_datetime_usec
    end

    alter table(:posts) do
      add :proposed_publish_at, :utc_datetime_usec
    end

    alter table(:entries) do
      add :proposed_publish_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:entries) do
      remove :proposed_publish_at
    end

    alter table(:posts) do
      remove :proposed_publish_at
    end

    alter table(:pages) do
      remove :proposed_publish_at
    end
  end
end
