defmodule KilnCMS.Repo.Migrations.AddSeoFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :seo_image, :text
      add :canonical_url, :text
    end

    alter table(:pages) do
      add :seo_image, :text
      add :canonical_url, :text
    end
  end

  def down do
    alter table(:pages) do
      remove :canonical_url
      remove :seo_image
    end

    alter table(:posts) do
      remove :canonical_url
      remove :seo_image
    end
  end
end
