defmodule KilnCMS.Repo.Migrations.AddAnchorLookupIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:history_anchors, [:org_id, :resource_type, :source_id])

    create index(:history_anchors, [:org_id, :resource_type, :source_id, :inserted_at, :id])
  end

  def down do
    drop_if_exists index(:history_anchors, [
                     :org_id,
                     :resource_type,
                     :source_id,
                     :inserted_at,
                     :id
                   ])

    create index(:history_anchors, [:org_id, :resource_type, :source_id])
  end
end
