defmodule KilnCMS.Repo.Migrations.ContentLinkReferenceEdges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:content_links) do
      add :field, :text
      add :source_type, :text
      add :target_type, :text
    end
  end

  def down do
    alter table(:content_links) do
      remove :target_type
      remove :source_type
      remove :field
    end
  end
end
