defmodule KilnCMS.Repo.Migrations.AddTagGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tag_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "tag_groups_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :position, :bigint, null: false, default: 0
      add :content_types, {:array, :text}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:tag_groups, [:slug], name: "tag_groups_slug_lookup_index")

    create unique_index(:tag_groups, [:org_id, :slug], name: "tag_groups_unique_slug_index")

    alter table(:tags) do
      add :tag_group_id,
          references(:tag_groups,
            column: :id,
            name: "tags_tag_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:tags, [:tag_group_id], name: "tags_tag_group_lookup_index")
  end

  def down do
    drop constraint(:tags, "tags_tag_group_id_fkey")

    drop_if_exists index(:tags, [:tag_group_id], name: "tags_tag_group_lookup_index")

    alter table(:tags) do
      remove :tag_group_id
    end

    drop constraint(:tag_groups, "tag_groups_org_id_fkey")

    drop_if_exists unique_index(:tag_groups, [:org_id, :slug],
                     name: "tag_groups_unique_slug_index"
                   )

    drop_if_exists index(:tag_groups, [:slug], name: "tag_groups_slug_lookup_index")

    drop table(:tag_groups)
  end
end
