defmodule KilnCMS.Repo.Migrations.AddAnchorSequence do
  @moduledoc """
  Adds `history_anchors.sequence` — the signed position that decides which
  anchor is the verification baseline (#666).

  Generated by `mix ash.codegen add_anchor_sequence`, then edited in the three
  ways codegen cannot express. Each is spelled out here because AGENTS.md says
  not to hand-edit generated migrations, and this is the exception it does not
  anticipate: a `NOT NULL` column on a table that already has rows.

    1. **Backfilled before the constraint.** Codegen emits
       `add :sequence, :bigint, null: false`, which fails outright on any
       populated table. The column is added nullable, filled with
       `row_number()` per document in `(inserted_at, id)` order — the order the
       chain was written in — and only then made `NOT NULL`.

    2. **The foreign key is added `NOT VALID`, then validated separately.**
       As generated it is added validated under `ACCESS EXCLUSIVE`, which
       (a) blocks reads *and* writes on `history_anchors` for a full scan, on
       the table `audit_anchor_every_write` grows fastest, and (b) **fails the
       whole migration** if any `prev_anchor_id` already dangles — which is
       precisely the tampered state #597 exists to detect. Migrations run on
       boot, so that turns a finding into a container that will not start, with
       a bare UUID for a message. Split in two, the `ADD CONSTRAINT` is
       instant, and `VALIDATE CONSTRAINT` takes only a `SHARE UPDATE EXCLUSIVE`
       lock, which does not block ordinary traffic.

    3. **Validation failure is reported, not swallowed.** If the validate step
       raises, the operator is told what it means and pointed at the query that
       lists the holes, rather than left with `23503` and a uuid.

  `down` is deliberately lossy and says so — see the CHANGELOG's Upgrading note.
  `sequence` is inside the v4 signed payload, so removing the column makes every
  anchor minted since this migration fail its own signature check. Rolling back
  is a one-way door for the audit surface.
  """

  use Ecto.Migration

  # Positions are per document, and `(inserted_at, id)` is the order the anchors
  # were written in — the same tiebreak `Chain.anchors/4` used before `sequence`
  # existed, so a backfilled chain reads in exactly the order it always did.
  @backfill """
  WITH numbered AS (
    SELECT id,
           row_number() OVER (
             PARTITION BY org_id, resource_type, source_id
             ORDER BY inserted_at, id
           ) AS position
      FROM history_anchors
  )
  UPDATE history_anchors AS a
     SET sequence = numbered.position
    FROM numbered
   WHERE a.id = numbered.id
  """

  @dangling """
  SELECT a.id, a.prev_anchor_id
    FROM history_anchors a
   WHERE a.prev_anchor_id IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM history_anchors p WHERE p.id = a.prev_anchor_id)
  """

  def up do
    alter table(:history_anchors) do
      add :sequence, :bigint
    end

    execute(@backfill)

    alter table(:history_anchors) do
      modify :sequence, :bigint, null: false
    end

    create index(:history_anchors, [:org_id, :resource_type, :source_id, :sequence], unique: true)

    execute("""
    ALTER TABLE history_anchors
      ADD CONSTRAINT history_anchors_prev_anchor_id_fkey
      FOREIGN KEY (prev_anchor_id) REFERENCES history_anchors(id)
      ON DELETE RESTRICT ON UPDATE RESTRICT
      NOT VALID
    """)

    validate_prev_anchor_links!()

    create index(:history_anchors, [:org_id, :prev_anchor_id])
  end

  def down do
    drop_if_exists index(:history_anchors, [:org_id, :prev_anchor_id])

    drop constraint(:history_anchors, "history_anchors_prev_anchor_id_fkey")

    drop_if_exists index(:history_anchors, [:org_id, :resource_type, :source_id, :sequence])

    alter table(:history_anchors) do
      remove :sequence
    end
  end

  defp validate_prev_anchor_links! do
    execute("ALTER TABLE history_anchors VALIDATE CONSTRAINT history_anchors_prev_anchor_id_fkey")
  rescue
    error ->
      reraise """
              Could not validate history_anchors.prev_anchor_id.

              At least one anchor names a predecessor that no longer exists. That is
              the hole #597 exists to detect, not a migration problem: an anchor row
              was deleted while its successor survived. The constraint has been added
              as NOT VALID, so it is already protecting new writes — the existing
              rows are what it cannot vouch for.

              List them with:

              #{String.trim(@dangling)}

              Then either restore the missing anchors from a backup, or accept the
              hole and validate manually:

                ALTER TABLE history_anchors
                  VALIDATE CONSTRAINT history_anchors_prev_anchor_id_fkey;

              Original error: #{Exception.message(error)}
              """,
              __STACKTRACE__
  end
end
