defmodule KilnCMS.Repo.Migrations.AddFormSpamModeration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:form_spam_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "form_spam_settings_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :keywords, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:form_spam_settings, [:org_id],
             name: "form_spam_settings_one_per_org_index"
           )

    alter table(:form_submissions) do
      add :status, :text, null: false, default: "new"
      add :spam_score, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:form_submissions) do
      remove :spam_score
      remove :status
    end

    drop constraint(:form_spam_settings, "form_spam_settings_org_id_fkey")

    drop_if_exists unique_index(:form_spam_settings, [:org_id],
                     name: "form_spam_settings_one_per_org_index"
                   )

    drop table(:form_spam_settings)
  end
end
