defmodule KilnCMS.Repo.Migrations.AddForms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:forms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :active, :boolean, null: false, default: true
      add :success_message, :text
      add :notify_email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:forms, [:slug], name: "forms_unique_slug_index")

    create table(:form_submissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :data, :map, null: false, default: %{}
      add :locale, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :form_id,
          references(:forms,
            column: :id,
            name: "form_submissions_form_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:form_fields, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :label, :text, null: false
      add :field_type, :text, null: false, default: "string"
      add :required, :boolean, null: false, default: false
      add :options, {:array, :text}, null: false, default: []
      add :help_text, :text
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :form_id,
          references(:forms,
            column: :id,
            name: "form_fields_form_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:form_fields, [:form_id, :name],
             name: "form_fields_unique_form_field_index"
           )
  end

  def down do
    drop constraint(:form_fields, "form_fields_form_id_fkey")

    drop_if_exists unique_index(:form_fields, [:form_id, :name],
                     name: "form_fields_unique_form_field_index"
                   )

    drop table(:form_fields)

    drop constraint(:form_submissions, "form_submissions_form_id_fkey")

    drop table(:form_submissions)

    drop_if_exists unique_index(:forms, [:slug], name: "forms_unique_slug_index")

    drop table(:forms)
  end
end
