defmodule KilnCMS.Repo.Migrations.AddEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:entries_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :type_definition_id,
          references(:type_definitions,
            column: :id,
            name: "entries_type_definition_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "entries_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "entries_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "entries_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:entries, ["title gin_trgm_ops"], name: "entries_title_trgm_index", using: "gin")

    create index(:entries, ["embedding vector_cosine_ops"],
             name: "entries_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:entries, [:type_definition_id, :slug, :locale],
             name: "entries_unique_slug_index"
           )
  end

  def down do
    drop constraint(:entries, "entries_type_definition_id_fkey")

    drop constraint(:entries, "entries_author_id_fkey")

    drop constraint(:entries, "entries_category_id_fkey")

    drop constraint(:entries, "entries_featured_image_id_fkey")

    drop_if_exists unique_index(:entries, [:type_definition_id, :slug, :locale],
                     name: "entries_unique_slug_index"
                   )

    drop_if_exists index(:entries, ["embedding vector_cosine_ops"],
                     name: "entries_embedding_hnsw_index"
                   )

    drop_if_exists index(:entries, ["title gin_trgm_ops"], name: "entries_title_trgm_index")

    drop table(:entries)

    drop table(:entries_versions)
  end
end
