defmodule KilnCMS.Repo.Migrations.FieldDefinitionLocalization do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:field_definitions) do
      add :localization, :text, null: false, default: "localized"
    end
  end

  def down do
    alter table(:field_definitions) do
      remove :localization
    end
  end
end
