defmodule KilnCMS.Repo.Migrations.StrictTenancyFks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:taggings, "taggings_tag_id_fkey")

    alter table(:taggings) do
      modify :tag_id,
             references(:tags,
               column: :id,
               name: "taggings_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(
           :newsletter_segment_memberships,
           "newsletter_segment_memberships_subscriber_id_fkey"
         )

    drop constraint(
           :newsletter_segment_memberships,
           "newsletter_segment_memberships_segment_id_fkey"
         )

    alter table(:newsletter_segment_memberships) do
      modify :segment_id,
             references(:newsletter_segments,
               column: :id,
               name: "newsletter_segment_memberships_segment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :subscriber_id,
             references(:newsletter_subscribers,
               column: :id,
               name: "newsletter_segment_memberships_subscriber_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:webhook_deliveries, "webhook_deliveries_endpoint_id_fkey")

    alter table(:webhook_deliveries) do
      modify :endpoint_id,
             references(:webhook_endpoints,
               column: :id,
               name: "webhook_deliveries_endpoint_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:form_submissions, "form_submissions_form_id_fkey")

    alter table(:form_submissions) do
      modify :form_id,
             references(:forms,
               column: :id,
               name: "form_submissions_form_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:form_fields, "form_fields_form_id_fkey")

    alter table(:form_fields) do
      modify :form_id,
             references(:forms,
               column: :id,
               name: "form_fields_form_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:entries, "entries_featured_image_id_fkey")

    drop constraint(:entries, "entries_category_id_fkey")

    drop constraint(:entries, "entries_type_definition_id_fkey")

    alter table(:entries) do
      modify :type_definition_id,
             references(:type_definitions,
               column: :id,
               name: "entries_type_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :category_id,
             references(:categories,
               column: :id,
               name: "entries_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :featured_image_id,
             references(:media_items,
               column: :id,
               name: "entries_featured_image_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:posts, "posts_featured_image_id_fkey")

    drop constraint(:posts, "posts_category_id_fkey")

    alter table(:posts) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "posts_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :featured_image_id,
             references(:media_items,
               column: :id,
               name: "posts_featured_image_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:field_definitions, "field_definitions_type_definition_id_fkey")

    alter table(:field_definitions) do
      modify :type_definition_id,
             references(:type_definitions,
               column: :id,
               name: "field_definitions_type_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:newsletter_sends, "newsletter_sends_segment_id_fkey")

    alter table(:newsletter_sends) do
      modify :segment_id,
             references(:newsletter_segments,
               column: :id,
               name: "newsletter_sends_segment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop constraint(:pages, "pages_featured_image_id_fkey")

    drop constraint(:pages, "pages_category_id_fkey")

    alter table(:pages) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "pages_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :featured_image_id,
             references(:media_items,
               column: :id,
               name: "pages_featured_image_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:pages, "pages_category_id_fkey")

    drop constraint(:pages, "pages_featured_image_id_fkey")

    alter table(:pages) do
      modify :featured_image_id,
             references(:media_items,
               column: :id,
               name: "pages_featured_image_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :category_id,
             references(:categories,
               column: :id,
               name: "pages_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:newsletter_sends, "newsletter_sends_segment_id_fkey")

    alter table(:newsletter_sends) do
      modify :segment_id,
             references(:newsletter_segments,
               column: :id,
               name: "newsletter_sends_segment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop constraint(:field_definitions, "field_definitions_type_definition_id_fkey")

    alter table(:field_definitions) do
      modify :type_definition_id,
             references(:type_definitions,
               column: :id,
               name: "field_definitions_type_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:posts, "posts_category_id_fkey")

    drop constraint(:posts, "posts_featured_image_id_fkey")

    alter table(:posts) do
      modify :featured_image_id,
             references(:media_items,
               column: :id,
               name: "posts_featured_image_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :category_id,
             references(:categories,
               column: :id,
               name: "posts_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:entries, "entries_type_definition_id_fkey")

    drop constraint(:entries, "entries_category_id_fkey")

    drop constraint(:entries, "entries_featured_image_id_fkey")

    alter table(:entries) do
      modify :featured_image_id,
             references(:media_items,
               column: :id,
               name: "entries_featured_image_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :category_id,
             references(:categories,
               column: :id,
               name: "entries_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :type_definition_id,
             references(:type_definitions,
               column: :id,
               name: "entries_type_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:form_fields, "form_fields_form_id_fkey")

    alter table(:form_fields) do
      modify :form_id,
             references(:forms,
               column: :id,
               name: "form_fields_form_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:form_submissions, "form_submissions_form_id_fkey")

    alter table(:form_submissions) do
      modify :form_id,
             references(:forms,
               column: :id,
               name: "form_submissions_form_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:webhook_deliveries, "webhook_deliveries_endpoint_id_fkey")

    alter table(:webhook_deliveries) do
      modify :endpoint_id,
             references(:webhook_endpoints,
               column: :id,
               name: "webhook_deliveries_endpoint_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(
           :newsletter_segment_memberships,
           "newsletter_segment_memberships_segment_id_fkey"
         )

    drop constraint(
           :newsletter_segment_memberships,
           "newsletter_segment_memberships_subscriber_id_fkey"
         )

    alter table(:newsletter_segment_memberships) do
      modify :subscriber_id,
             references(:newsletter_subscribers,
               column: :id,
               name: "newsletter_segment_memberships_subscriber_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :segment_id,
             references(:newsletter_segments,
               column: :id,
               name: "newsletter_segment_memberships_segment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:taggings, "taggings_tag_id_fkey")

    alter table(:taggings) do
      modify :tag_id,
             references(:tags,
               column: :id,
               name: "taggings_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end
end
