defmodule KilnCMS.Repo.Migrations.AddAutomationProvenanceToCommentsAndTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      modify :creator_id, :uuid, null: true
      add :created_by_rule_id, :uuid
    end

    alter table(:comments) do
      modify :author_id, :uuid, null: true
      modify :block_id, :uuid, null: true
      add :created_by_rule_id, :uuid
    end
  end

  def down do
    ensure_no_automation_authored_rows()

    alter table(:comments) do
      remove :created_by_rule_id
      modify :block_id, :uuid, null: false
      modify :author_id, :uuid, null: false
    end

    alter table(:tasks) do
      remove :created_by_rule_id
      modify :creator_id, :uuid, null: false
    end
  end

  # `up/0` relaxed these to nullable specifically so automation (#946) could
  # write a comment/task with no human author/creator, and a document-level
  # comment with no block. Restoring `null: false` blind, the autogenerated
  # default, fails with an opaque Postgres NOT NULL violation the moment any
  # such row exists — turning "roll back this migration" into a stuck
  # deploy discovered mid-rollback rather than before it's attempted.
  defp ensure_no_automation_authored_rows do
    %{rows: [[comments]]} =
      repo().query!("SELECT count(*) FROM comments WHERE created_by_rule_id IS NOT NULL")

    %{rows: [[tasks]]} =
      repo().query!("SELECT count(*) FROM tasks WHERE created_by_rule_id IS NOT NULL")

    if comments > 0 or tasks > 0 do
      raise """
      Cannot roll back #{__MODULE__}: #{comments} comment(s) and #{tasks} task(s) \
      were created by an automation rule (#946) and have no author/creator/block, \
      which would violate the NOT NULL constraints this rollback restores. Delete \
      or reassign those rows first if you need to roll back.
      """
    end
  end
end
