defmodule KilnCMS.Repo.Migrations.AddContentLinkPayload do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:content_links) do
      add :label, :text
      add :metadata, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:content_links) do
      remove :metadata
      remove :label
    end
  end
end
