defmodule KilnCMS.Repo.Migrations.AddVariantFailures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:media_items) do
      add :variant_failures, :map, default: %{}
    end
  end

  def down do
    alter table(:media_items) do
      remove :variant_failures
    end
  end
end
