defmodule KilnCMS.Repo.Migrations.AddVerscientaContentTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:practitioners_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:practitioners, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "practitioners_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "practitioners_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "practitioners_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:practitioners, ["title gin_trgm_ops"],
             name: "practitioners_title_trgm_index",
             using: "gin"
           )

    create index(:practitioners, ["embedding vector_cosine_ops"],
             name: "practitioners_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:practitioners, [:slug, :locale], name: "practitioners_unique_slug_index")

    create table(:modalities_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:modalities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "modalities_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "modalities_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "modalities_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:modalities, ["title gin_trgm_ops"],
             name: "modalities_title_trgm_index",
             using: "gin"
           )

    create index(:modalities, ["embedding vector_cosine_ops"],
             name: "modalities_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:modalities, [:slug, :locale], name: "modalities_unique_slug_index")

    create table(:herbs_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:herbs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "herbs_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "herbs_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "herbs_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:herbs, ["title gin_trgm_ops"], name: "herbs_title_trgm_index", using: "gin")

    create index(:herbs, ["embedding vector_cosine_ops"],
             name: "herbs_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:herbs, [:slug, :locale], name: "herbs_unique_slug_index")

    create table(:formulas_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:formulas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "formulas_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "formulas_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "formulas_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:formulas, ["title gin_trgm_ops"],
             name: "formulas_title_trgm_index",
             using: "gin"
           )

    create index(:formulas, ["embedding vector_cosine_ops"],
             name: "formulas_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:formulas, [:slug, :locale], name: "formulas_unique_slug_index")

    create table(:conditions_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:conditions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "conditions_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "conditions_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "conditions_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:conditions, ["title gin_trgm_ops"],
             name: "conditions_title_trgm_index",
             using: "gin"
           )

    create index(:conditions, ["embedding vector_cosine_ops"],
             name: "conditions_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:conditions, [:slug, :locale], name: "conditions_unique_slug_index")

    create table(:clinics_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:clinics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :audience, :text, null: false, default: "public"
      add :custom_fields, :map, null: false, default: %{}
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "clinics_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "clinics_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "clinics_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:clinics, ["title gin_trgm_ops"], name: "clinics_title_trgm_index", using: "gin")

    create index(:clinics, ["embedding vector_cosine_ops"],
             name: "clinics_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:clinics, [:slug, :locale], name: "clinics_unique_slug_index")
  end

  def down do
    drop constraint(:clinics, "clinics_author_id_fkey")

    drop constraint(:clinics, "clinics_category_id_fkey")

    drop constraint(:clinics, "clinics_featured_image_id_fkey")

    drop_if_exists unique_index(:clinics, [:slug, :locale], name: "clinics_unique_slug_index")

    drop_if_exists index(:clinics, ["embedding vector_cosine_ops"],
                     name: "clinics_embedding_hnsw_index"
                   )

    drop_if_exists index(:clinics, ["title gin_trgm_ops"], name: "clinics_title_trgm_index")

    drop table(:clinics)

    drop table(:clinics_versions)

    drop constraint(:conditions, "conditions_author_id_fkey")

    drop constraint(:conditions, "conditions_category_id_fkey")

    drop constraint(:conditions, "conditions_featured_image_id_fkey")

    drop_if_exists unique_index(:conditions, [:slug, :locale],
                     name: "conditions_unique_slug_index"
                   )

    drop_if_exists index(:conditions, ["embedding vector_cosine_ops"],
                     name: "conditions_embedding_hnsw_index"
                   )

    drop_if_exists index(:conditions, ["title gin_trgm_ops"], name: "conditions_title_trgm_index")

    drop table(:conditions)

    drop table(:conditions_versions)

    drop constraint(:formulas, "formulas_author_id_fkey")

    drop constraint(:formulas, "formulas_category_id_fkey")

    drop constraint(:formulas, "formulas_featured_image_id_fkey")

    drop_if_exists unique_index(:formulas, [:slug, :locale], name: "formulas_unique_slug_index")

    drop_if_exists index(:formulas, ["embedding vector_cosine_ops"],
                     name: "formulas_embedding_hnsw_index"
                   )

    drop_if_exists index(:formulas, ["title gin_trgm_ops"], name: "formulas_title_trgm_index")

    drop table(:formulas)

    drop table(:formulas_versions)

    drop constraint(:herbs, "herbs_author_id_fkey")

    drop constraint(:herbs, "herbs_category_id_fkey")

    drop constraint(:herbs, "herbs_featured_image_id_fkey")

    drop_if_exists unique_index(:herbs, [:slug, :locale], name: "herbs_unique_slug_index")

    drop_if_exists index(:herbs, ["embedding vector_cosine_ops"],
                     name: "herbs_embedding_hnsw_index"
                   )

    drop_if_exists index(:herbs, ["title gin_trgm_ops"], name: "herbs_title_trgm_index")

    drop table(:herbs)

    drop table(:herbs_versions)

    drop constraint(:modalities, "modalities_author_id_fkey")

    drop constraint(:modalities, "modalities_category_id_fkey")

    drop constraint(:modalities, "modalities_featured_image_id_fkey")

    drop_if_exists unique_index(:modalities, [:slug, :locale],
                     name: "modalities_unique_slug_index"
                   )

    drop_if_exists index(:modalities, ["embedding vector_cosine_ops"],
                     name: "modalities_embedding_hnsw_index"
                   )

    drop_if_exists index(:modalities, ["title gin_trgm_ops"], name: "modalities_title_trgm_index")

    drop table(:modalities)

    drop table(:modalities_versions)

    drop constraint(:practitioners, "practitioners_author_id_fkey")

    drop constraint(:practitioners, "practitioners_category_id_fkey")

    drop constraint(:practitioners, "practitioners_featured_image_id_fkey")

    drop_if_exists unique_index(:practitioners, [:slug, :locale],
                     name: "practitioners_unique_slug_index"
                   )

    drop_if_exists index(:practitioners, ["embedding vector_cosine_ops"],
                     name: "practitioners_embedding_hnsw_index"
                   )

    drop_if_exists index(:practitioners, ["title gin_trgm_ops"],
                     name: "practitioners_title_trgm_index"
                   )

    drop table(:practitioners)

    drop table(:practitioners_versions)
  end
end
