defmodule KilnCMS.Repo.Migrations.AddFormProgressIndicator do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forms) do
      add :progress_indicator, :text, null: false, default: "steps"
    end
  end

  def down do
    alter table(:forms) do
      remove :progress_indicator
    end
  end
end
