defmodule KilnCMS.Repo.Migrations.AddMissedPathsEvictionIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:missed_paths, [:org_id, "count", "last_seen_at DESC"],
             name: "missed_paths_eviction_index"
           )
  end

  def down do
    drop_if_exists index(:missed_paths, [:org_id, "count", "last_seen_at DESC"],
                     name: "missed_paths_eviction_index"
                   )
  end
end
