defmodule KilnCMS.Repo.Migrations.AddOrganizationsAndNullableOrgId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :custom_domain, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organizations, [:custom_domain],
             name: "organizations_unique_custom_domain_index",
             where: "(custom_domain IS NOT NULL)"
           )

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    drop_if_exists index(:block_embeddings, ["embedding vector_cosine_ops"],
                     name: "block_embeddings_hnsw_index"
                   )

    alter table(:block_embeddings) do
      add :org_id,
          references(:organizations,
            column: :id,
            name: "block_embeddings_org_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:block_embeddings, ["embedding vector_cosine_ops"],
             name: "block_embeddings_hnsw_index",
             using: "hnsw"
           )

    drop_if_exists unique_index(:block_embeddings, [:document_type, :document_id, :block_key],
                     name: "block_embeddings_doc_block_index"
                   )

    create unique_index(:block_embeddings, [:org_id, :document_type, :document_id, :block_key],
             name: "block_embeddings_doc_block_index"
           )

    alter table(:reference_edges) do
      add :org_id,
          references(:organizations,
            column: :id,
            name: "reference_edges_org_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop_if_exists unique_index(:reference_edges, [:from_type, :from_id, :to_type, :to_id],
                     name: "reference_edges_edge_index"
                   )

    create unique_index(:reference_edges, [:org_id, :from_type, :from_id, :to_type, :to_id],
             name: "reference_edges_edge_index"
           )

    drop_if_exists index(:entries, ["title gin_trgm_ops"], name: "entries_title_trgm_index")

    drop_if_exists index(:entries, ["embedding vector_cosine_ops"],
                     name: "entries_embedding_hnsw_index"
                   )

    alter table(:entries) do
      add :org_id,
          references(:organizations,
            column: :id,
            name: "entries_org_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:entries, ["title gin_trgm_ops"], name: "entries_title_trgm_index", using: "gin")

    create index(:entries, ["embedding vector_cosine_ops"],
             name: "entries_embedding_hnsw_index",
             using: "hnsw"
           )

    drop_if_exists unique_index(:entries, [:type_definition_id, :slug, :locale],
                     name: "entries_unique_slug_index"
                   )

    create unique_index(:entries, [:org_id, :type_definition_id, :slug, :locale],
             name: "entries_unique_slug_index"
           )

    alter table(:published_artifacts) do
      add :org_id,
          references(:organizations,
            column: :id,
            name: "published_artifacts_org_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop_if_exists unique_index(:published_artifacts, [:document_type, :document_id, :surface],
                     name: "published_artifacts_doc_surface_index"
                   )

    create unique_index(:published_artifacts, [:org_id, :document_type, :document_id, :surface],
             name: "published_artifacts_doc_surface_index"
           )

    alter table(:pages_versions) do
      add :org_id, :uuid
    end

    drop_if_exists index(:posts, ["title gin_trgm_ops"], name: "posts_title_trgm_index")

    drop_if_exists index(:posts, ["embedding vector_cosine_ops"],
                     name: "posts_embedding_hnsw_index"
                   )

    alter table(:posts) do
      add :org_id,
          references(:organizations,
            column: :id,
            name: "posts_org_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:posts, ["title gin_trgm_ops"], name: "posts_title_trgm_index", using: "gin")

    create index(:posts, ["embedding vector_cosine_ops"],
             name: "posts_embedding_hnsw_index",
             using: "hnsw"
           )

    drop_if_exists unique_index(:posts, [:slug, :locale], name: "posts_unique_slug_index")

    create unique_index(:posts, [:org_id, :slug, :locale], name: "posts_unique_slug_index")

    create table(:org_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "viewer"
      add :audiences, {:array, :text}, null: false, default: []
      add :editable_types, {:array, :text}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "org_memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "org_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:org_memberships, [:user_id, :organization_id],
             name: "org_memberships_unique_membership_index"
           )

    alter table(:entries_versions) do
      add :org_id, :uuid
    end

    alter table(:posts_versions) do
      add :org_id, :uuid
    end

    drop_if_exists index(:pages, ["title gin_trgm_ops"], name: "pages_title_trgm_index")

    drop_if_exists index(:pages, ["embedding vector_cosine_ops"],
                     name: "pages_embedding_hnsw_index"
                   )

    alter table(:pages) do
      add :org_id,
          references(:organizations,
            column: :id,
            name: "pages_org_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:pages, ["title gin_trgm_ops"], name: "pages_title_trgm_index", using: "gin")

    create index(:pages, ["embedding vector_cosine_ops"],
             name: "pages_embedding_hnsw_index",
             using: "hnsw"
           )

    drop_if_exists unique_index(:pages, [:slug, :locale], name: "pages_unique_slug_index")

    create unique_index(:pages, [:org_id, :slug, :locale], name: "pages_unique_slug_index")
  end

  def down do
    drop constraint(:pages, "pages_org_id_fkey")

    drop_if_exists unique_index(:pages, [:org_id, :slug, :locale],
                     name: "pages_unique_slug_index"
                   )

    create unique_index(:pages, [:slug, :locale], name: "pages_unique_slug_index")

    drop_if_exists index(:pages, ["embedding vector_cosine_ops"],
                     name: "pages_embedding_hnsw_index"
                   )

    drop_if_exists index(:pages, ["title gin_trgm_ops"], name: "pages_title_trgm_index")

    alter table(:pages) do
      remove :org_id
    end

    create index(:pages, ["embedding vector_cosine_ops"],
             name: "pages_embedding_hnsw_index",
             using: "hnsw"
           )

    create index(:pages, ["title gin_trgm_ops"], name: "pages_title_trgm_index", using: "gin")

    alter table(:posts_versions) do
      remove :org_id
    end

    alter table(:entries_versions) do
      remove :org_id
    end

    drop constraint(:org_memberships, "org_memberships_organization_id_fkey")

    drop constraint(:org_memberships, "org_memberships_user_id_fkey")

    drop_if_exists unique_index(:org_memberships, [:user_id, :organization_id],
                     name: "org_memberships_unique_membership_index"
                   )

    drop table(:org_memberships)

    drop constraint(:posts, "posts_org_id_fkey")

    drop_if_exists unique_index(:posts, [:org_id, :slug, :locale],
                     name: "posts_unique_slug_index"
                   )

    create unique_index(:posts, [:slug, :locale], name: "posts_unique_slug_index")

    drop_if_exists index(:posts, ["embedding vector_cosine_ops"],
                     name: "posts_embedding_hnsw_index"
                   )

    drop_if_exists index(:posts, ["title gin_trgm_ops"], name: "posts_title_trgm_index")

    alter table(:posts) do
      remove :org_id
    end

    create index(:posts, ["embedding vector_cosine_ops"],
             name: "posts_embedding_hnsw_index",
             using: "hnsw"
           )

    create index(:posts, ["title gin_trgm_ops"], name: "posts_title_trgm_index", using: "gin")

    alter table(:pages_versions) do
      remove :org_id
    end

    drop constraint(:published_artifacts, "published_artifacts_org_id_fkey")

    drop_if_exists unique_index(
                     :published_artifacts,
                     [:org_id, :document_type, :document_id, :surface],
                     name: "published_artifacts_doc_surface_index"
                   )

    create unique_index(:published_artifacts, [:document_type, :document_id, :surface],
             name: "published_artifacts_doc_surface_index"
           )

    alter table(:published_artifacts) do
      remove :org_id
    end

    drop constraint(:entries, "entries_org_id_fkey")

    drop_if_exists unique_index(:entries, [:org_id, :type_definition_id, :slug, :locale],
                     name: "entries_unique_slug_index"
                   )

    create unique_index(:entries, [:type_definition_id, :slug, :locale],
             name: "entries_unique_slug_index"
           )

    drop_if_exists index(:entries, ["embedding vector_cosine_ops"],
                     name: "entries_embedding_hnsw_index"
                   )

    drop_if_exists index(:entries, ["title gin_trgm_ops"], name: "entries_title_trgm_index")

    alter table(:entries) do
      remove :org_id
    end

    create index(:entries, ["embedding vector_cosine_ops"],
             name: "entries_embedding_hnsw_index",
             using: "hnsw"
           )

    create index(:entries, ["title gin_trgm_ops"], name: "entries_title_trgm_index", using: "gin")

    drop constraint(:reference_edges, "reference_edges_org_id_fkey")

    drop_if_exists unique_index(
                     :reference_edges,
                     [:org_id, :from_type, :from_id, :to_type, :to_id],
                     name: "reference_edges_edge_index"
                   )

    create unique_index(:reference_edges, [:from_type, :from_id, :to_type, :to_id],
             name: "reference_edges_edge_index"
           )

    alter table(:reference_edges) do
      remove :org_id
    end

    drop constraint(:block_embeddings, "block_embeddings_org_id_fkey")

    drop_if_exists unique_index(
                     :block_embeddings,
                     [:org_id, :document_type, :document_id, :block_key],
                     name: "block_embeddings_doc_block_index"
                   )

    create unique_index(:block_embeddings, [:document_type, :document_id, :block_key],
             name: "block_embeddings_doc_block_index"
           )

    drop_if_exists index(:block_embeddings, ["embedding vector_cosine_ops"],
                     name: "block_embeddings_hnsw_index"
                   )

    alter table(:block_embeddings) do
      remove :org_id
    end

    create index(:block_embeddings, ["embedding vector_cosine_ops"],
             name: "block_embeddings_hnsw_index",
             using: "hnsw"
           )

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    drop_if_exists unique_index(:organizations, [:custom_domain],
                     name: "organizations_unique_custom_domain_index"
                   )

    drop table(:organizations)
  end
end
