defmodule KilnCMS.Repo.Migrations.AddPushSubscriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:push_subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :endpoint, :text, null: false
      add :p256dh, :text, null: false
      add :auth, :text, null: false
      add :label, :text, null: false, default: "Browser"
      add :last_delivered_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "push_subscriptions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :org_id,
          references(:organizations,
            column: :id,
            name: "push_subscriptions_org_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:push_subscriptions, [:user_id])

    create unique_index(:push_subscriptions, [:endpoint],
             name: "push_subscriptions_unique_endpoint_index"
           )
  end

  def down do
    drop constraint(:push_subscriptions, "push_subscriptions_user_id_fkey")

    drop constraint(:push_subscriptions, "push_subscriptions_org_id_fkey")

    drop_if_exists unique_index(:push_subscriptions, [:endpoint],
                     name: "push_subscriptions_unique_endpoint_index"
                   )

    drop_if_exists index(:push_subscriptions, [:user_id])

    drop table(:push_subscriptions)
  end
end
