defmodule KilnCMS.Repo.Migrations.DropContentLinkUniqueLinkIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:content_links, [:org_id, :source_id, :target_id, :kind],
                     name: "content_links_unique_link_index"
                   )
  end

  def down do
    create unique_index(:content_links, [:org_id, :source_id, :target_id, :kind],
             name: "content_links_unique_link_index"
           )
  end
end
