defmodule KilnCMS.Repo.Migrations.AddComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:comments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "comments_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :content_type, :text, null: false
      add :content_id, :uuid, null: false
      add :block_id, :uuid, null: false
      add :thread_id, :uuid
      add :body, :text, null: false
      add :author_id, :uuid, null: false
      add :resolved_at, :utc_datetime_usec
      add :resolved_by_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:comments, [:org_id, :content_type, :content_id, :block_id],
             name: "comments_block_lookup_index"
           )
  end

  def down do
    drop constraint(:comments, "comments_org_id_fkey")

    drop_if_exists index(:comments, [:org_id, :content_type, :content_id, :block_id],
                     name: "comments_block_lookup_index"
                   )

    drop table(:comments)
  end
end
