defmodule KilnCMS.Repo.Migrations.NewsletterAutomationDedupe do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:newsletter_sends) do
      add :automation_rule_id, :uuid
      add :content_published_at, :utc_datetime_usec
    end

    create unique_index(
             :newsletter_sends,
             [:org_id, :automation_rule_id, :content_id, :content_published_at],
             name: "newsletter_sends_automation_dedupe_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :newsletter_sends,
                     [:org_id, :automation_rule_id, :content_id, :content_published_at],
                     name: "newsletter_sends_automation_dedupe_index"
                   )

    alter table(:newsletter_sends) do
      remove :content_published_at
      remove :automation_rule_id
    end
  end
end
