defmodule KilnCMS.Repo.Migrations.AddHistoryAnchorIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:history_anchors, [:org_id, :resource_type, :source_id])
  end

  def down do
    drop_if_exists index(:history_anchors, [:org_id, :resource_type, :source_id])
  end
end
