defmodule KilnCMS.Repo.Migrations.AddHealthContentTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:herbs_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:herbs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "herbs_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "herbs_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "herbs_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:herbs, ["title gin_trgm_ops"], name: "herbs_title_trgm_index", using: "gin")

    create index(:herbs, ["embedding vector_cosine_ops"],
             name: "herbs_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:herbs, [:slug, :locale], name: "herbs_unique_slug_index")

    create table(:conditions_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:conditions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text, null: false
      add :excerpt, :text
      add :blocks, {:array, :map}, default: []
      add :seo_title, :text
      add :seo_description, :text
      add :seo_image, :text
      add :canonical_url, :text
      add :locale, :text, default: "en"
      add :published_at, :utc_datetime_usec
      add :published_version_id, :uuid
      add :scheduled_at, :utc_datetime_usec
      add :search_text, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
      add :lock_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "draft"

      add :author_id,
          references(:users,
            column: :id,
            name: "conditions_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "conditions_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :featured_image_id,
          references(:media_items,
            column: :id,
            name: "conditions_featured_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:conditions, ["title gin_trgm_ops"],
             name: "conditions_title_trgm_index",
             using: "gin"
           )

    create index(:conditions, ["embedding vector_cosine_ops"],
             name: "conditions_embedding_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:conditions, [:slug, :locale], name: "conditions_unique_slug_index")
  end

  def down do
    drop constraint(:conditions, "conditions_author_id_fkey")

    drop constraint(:conditions, "conditions_category_id_fkey")

    drop constraint(:conditions, "conditions_featured_image_id_fkey")

    drop_if_exists unique_index(:conditions, [:slug, :locale],
                     name: "conditions_unique_slug_index"
                   )

    drop_if_exists index(:conditions, ["embedding vector_cosine_ops"],
                     name: "conditions_embedding_hnsw_index"
                   )

    drop_if_exists index(:conditions, ["title gin_trgm_ops"], name: "conditions_title_trgm_index")

    drop table(:conditions)

    drop table(:conditions_versions)

    drop constraint(:herbs, "herbs_author_id_fkey")

    drop constraint(:herbs, "herbs_category_id_fkey")

    drop constraint(:herbs, "herbs_featured_image_id_fkey")

    drop_if_exists unique_index(:herbs, [:slug, :locale], name: "herbs_unique_slug_index")

    drop_if_exists index(:herbs, ["embedding vector_cosine_ops"],
                     name: "herbs_embedding_hnsw_index"
                   )

    drop_if_exists index(:herbs, ["title gin_trgm_ops"], name: "herbs_title_trgm_index")

    drop table(:herbs)

    drop table(:herbs_versions)
  end
end
