defmodule KilnCMS.Repo.Migrations.AddNotificationPrefs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :notify_on_review_request, :boolean, null: false, default: true
      add :notify_on_publish, :boolean, null: false, default: true
      add :notify_on_return_to_draft, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:users) do
      remove :notify_on_return_to_draft
      remove :notify_on_publish
      remove :notify_on_review_request
    end
  end
end
