defmodule KilnCMS.Repo.Migrations.AddTierBackedSegments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:newsletter_segments) do
      add :managed_by, :text, null: false, default: "admin"

      add :tier_id,
          references(:billing_membership_tiers,
            column: :id,
            name: "newsletter_segments_tier_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:newsletter_subscribers) do
      add :user_id, :uuid
    end

    create constraint(:newsletter_segments, :newsletter_segments_managed_by_must_be_known,
             check: """
               managed_by IN ('admin', 'tier')
             """
           )

    create constraint(:newsletter_segments, :newsletter_segments_tier_required_when_managed,
             check: """
               managed_by <> 'tier' OR tier_id IS NOT NULL
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :newsletter_segments,
                     :newsletter_segments_tier_required_when_managed
                   )

    drop_if_exists constraint(:newsletter_segments, :newsletter_segments_managed_by_must_be_known)

    alter table(:newsletter_subscribers) do
      remove :user_id
    end

    drop constraint(:newsletter_segments, "newsletter_segments_tier_id_fkey")

    alter table(:newsletter_segments) do
      remove :tier_id
      remove :managed_by
    end
  end
end
