defmodule KilnCMS.Repo.Migrations.AddHistoryAnchors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:history_anchors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "history_anchors_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resource_type, :text, null: false
      add :source_id, :uuid, null: false
      add :chain_hash, :text, null: false
      add :version_count, :bigint, null: false
      add :last_version_id, :uuid
      add :published_version_id, :uuid
      add :signature, :text
      add :key_id, :text
      add :actor_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:history_anchors, "history_anchors_org_id_fkey")

    drop table(:history_anchors)
  end
end
