defmodule KilnCMS.Repo.Migrations.AddFormConfirmations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forms) do
      add :confirmation_type, :text, null: false, default: "message"
      add :redirect_url, :text
      add :confirmation_variants, {:array, :map}, null: false, default: []
      add :notify_conditions, :map, null: false, default: %{}
      add :autoresponder_enabled, :boolean, null: false, default: false
      add :autoresponder_subject, :text
      add :autoresponder_body, :text
    end
  end

  def down do
    alter table(:forms) do
      remove :autoresponder_body
      remove :autoresponder_subject
      remove :autoresponder_enabled
      remove :notify_conditions
      remove :confirmation_variants
      remove :redirect_url
      remove :confirmation_type
    end
  end
end
