defmodule KilnCMS.Repo.Migrations.AddBillingMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:billing_membership_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "billing_membership_events_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :membership_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :tier_id, :uuid
      add :kind, :text, null: false
      add :from_status, :text
      add :to_status, :text, null: false
      add :audiences_added, {:array, :text}, null: false, default: []
      add :audiences_removed, {:array, :text}, null: false, default: []
      add :provider_event_id, :text
      add :actor_id, :uuid
      add :note, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:billing_membership_events, [:org_id, :user_id])

    create index(:billing_membership_events, [:org_id, :membership_id])

    create table(:billing_webhook_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false, default: "stripe"
      add :provider_event_id, :text, null: false
      add :type, :text, null: false
      add :payload, :map, null: false, default: %{}
      add :status, :text, null: false, default: "received"
      add :org_id, :uuid
      add :membership_id, :uuid
      add :error, :text
      add :processed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:billing_webhook_events, [:provider, :provider_event_id],
             name: "billing_webhook_events_unique_provider_event_index"
           )

    create table(:billing_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "billing_memberships_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id, :uuid, null: false
      add :status, :text, null: false, default: "incomplete"
      add :provider_customer_id, :text
      add :provider_subscription_id, :text
      add :current_period_end, :utc_datetime_usec
      add :cancel_at_period_end, :boolean, null: false, default: false
      add :activated_at, :utc_datetime_usec
      add :canceled_at, :utc_datetime_usec
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tier_id,
          references(:billing_membership_tiers,
            column: :id,
            name: "billing_memberships_tier_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:billing_memberships, [:org_id, :user_id])

    create index(:billing_memberships, [:org_id, :provider_customer_id])

    create index(:billing_memberships, [:org_id, :provider_subscription_id])

    create unique_index(:billing_memberships, [:org_id, :user_id, :tier_id],
             name: "billing_memberships_one_per_user_and_tier_index"
           )

    create constraint(:billing_memberships, :billing_memberships_status_must_be_known,
             check: """
               status IN ('incomplete', 'active', 'past_due', 'canceled', 'comped')
             """
           )

    create constraint(:billing_webhook_events, :billing_webhook_events_status_must_be_known,
             check: """
               status IN ('received', 'processing', 'processed', 'failed', 'ignored')
             """
           )

    create constraint(:billing_webhook_events, :billing_webhook_events_provider_must_be_known,
             check: """
               provider IN ('stripe')
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :billing_webhook_events,
                     :billing_webhook_events_provider_must_be_known
                   )

    drop_if_exists constraint(
                     :billing_webhook_events,
                     :billing_webhook_events_status_must_be_known
                   )

    drop_if_exists constraint(:billing_memberships, :billing_memberships_status_must_be_known)

    drop constraint(:billing_memberships, "billing_memberships_org_id_fkey")

    drop constraint(:billing_memberships, "billing_memberships_tier_id_fkey")

    drop_if_exists unique_index(:billing_memberships, [:org_id, :user_id, :tier_id],
                     name: "billing_memberships_one_per_user_and_tier_index"
                   )

    drop_if_exists index(:billing_memberships, [:org_id, :provider_subscription_id])

    drop_if_exists index(:billing_memberships, [:org_id, :provider_customer_id])

    drop_if_exists index(:billing_memberships, [:org_id, :user_id])

    drop table(:billing_memberships)

    drop_if_exists unique_index(:billing_webhook_events, [:provider, :provider_event_id],
                     name: "billing_webhook_events_unique_provider_event_index"
                   )

    drop table(:billing_webhook_events)

    drop constraint(:billing_membership_events, "billing_membership_events_org_id_fkey")

    drop_if_exists index(:billing_membership_events, [:org_id, :membership_id])

    drop_if_exists index(:billing_membership_events, [:org_id, :user_id])

    drop table(:billing_membership_events)
  end
end
