defmodule KilnCMS.Repo.Migrations.AddContentEmbedding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
    end

    create index(:posts, ["embedding vector_cosine_ops"],
             name: "posts_embedding_hnsw_index",
             using: "hnsw"
           )

    alter table(:pages) do
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
    end

    create index(:pages, ["embedding vector_cosine_ops"],
             name: "pages_embedding_hnsw_index",
             using: "hnsw"
           )
  end

  def down do
    drop_if_exists index(:pages, ["embedding vector_cosine_ops"],
                     name: "pages_embedding_hnsw_index"
                   )

    alter table(:pages) do
      remove :embedded_at
      remove :embedding
    end

    drop_if_exists index(:posts, ["embedding vector_cosine_ops"],
                     name: "posts_embedding_hnsw_index"
                   )

    alter table(:posts) do
      remove :embedded_at
      remove :embedding
    end
  end
end
