defmodule KilnCMS.Repo.Migrations.AddTrigramAutocomplete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:posts, ["title gin_trgm_ops"], name: "posts_title_trgm_index", using: "gin")

    create index(:pages, ["title gin_trgm_ops"], name: "pages_title_trgm_index", using: "gin")
  end

  def down do
    drop_if_exists index(:pages, ["title gin_trgm_ops"], name: "pages_title_trgm_index")

    drop_if_exists index(:posts, ["title gin_trgm_ops"], name: "posts_title_trgm_index")
  end
end
