defmodule KilnCMS.Repo.Migrations.AddDocumentEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:document_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :document_type, :text, null: false
      add :document_id, :uuid, null: false
      add :seq, :bigint, null: false
      add :kind, :text, null: false
      add :payload, :map, null: false, default: %{}
      add :actor_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:document_events, [:document_type, :document_id, :seq],
             name: "document_events_doc_seq_index"
           )
  end

  def down do
    drop_if_exists unique_index(:document_events, [:document_type, :document_id, :seq],
                     name: "document_events_doc_seq_index"
                   )

    drop table(:document_events)
  end
end
