defmodule KilnCMS.Repo.Migrations.ContentLinkReferenceEdges1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create unique_index(:content_links, [:org_id, :source_id, :target_id, :kind, :field],
             name: "content_links_unique_field_link_index",
             nulls_distinct: false,
             concurrently: true
           )
  end

  def down do
    drop_if_exists unique_index(:content_links, [:org_id, :source_id, :target_id, :kind, :field],
                     name: "content_links_unique_field_link_index"
                   )
  end
end
