defmodule KilnCMS.Repo.Migrations.WorkingCopyEveryField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pages) do
      add :working_fields, :map, null: false, default: %{}
    end

    alter table(:posts) do
      add :working_fields, :map, null: false, default: %{}
    end

    alter table(:entries) do
      add :working_fields, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:entries) do
      remove :working_fields
    end

    alter table(:posts) do
      remove :working_fields
    end

    alter table(:pages) do
      remove :working_fields
    end
  end
end
