defmodule KilnCMS.Repo.Migrations.AddMediaUploaderIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:media_items, [:org_id, :uploaded_by_id], name: "media_items_uploaded_by_index")
  end

  def down do
    drop_if_exists index(:media_items, [:org_id, :uploaded_by_id],
                     name: "media_items_uploaded_by_index"
                   )
  end
end
