defmodule KilnCMS.Repo.Migrations.AddMailSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mail_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :singleton, :bigint, null: false, default: 0
      add :dkim_selector, :text
      add :dkim_key_provider, :text, null: false, default: "database"
      add :dkim_key_provider_config, :map, default: %{}
      add :dkim_private_key_encrypted, :binary
      add :dkim_public_key, :text
      add :server_ip, :text
      add :last_verified_at, :utc_datetime_usec
      add :verification_results, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:mail_settings, [:singleton], name: "mail_settings_singleton_row_index")
  end

  def down do
    drop_if_exists unique_index(:mail_settings, [:singleton],
                     name: "mail_settings_singleton_row_index"
                   )

    drop table(:mail_settings)
  end
end
