defmodule KilnCMS.Repo.Migrations.AddContentViewDaily do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:content_views_daily, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content_type, :text, null: false
      add :content_id, :uuid, null: false
      add :day, :date, null: false
      add :views, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:content_views_daily, [:content_type, :content_id, :day],
             name: "content_views_daily_unique_content_day_index"
           )
  end

  def down do
    drop_if_exists unique_index(:content_views_daily, [:content_type, :content_id, :day],
                     name: "content_views_daily_unique_content_day_index"
                   )

    drop table(:content_views_daily)
  end
end
