defmodule KilnCMS.Repo.Migrations.AddAliasPattern do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:type_definitions) do
      add :alias_pattern, :text
    end
  end

  def down do
    alter table(:type_definitions) do
      remove :alias_pattern
    end
  end
end
