defmodule KilnCMS.Repo.Migrations.GovernanceVersionActor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pages_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "pages_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    alter table(:entries_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "entries_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    alter table(:posts_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "posts_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:posts_versions, "posts_versions_user_id_fkey")

    alter table(:posts_versions) do
      remove :user_id
    end

    drop constraint(:entries_versions, "entries_versions_user_id_fkey")

    alter table(:entries_versions) do
      remove :user_id
    end

    drop constraint(:pages_versions, "pages_versions_user_id_fkey")

    alter table(:pages_versions) do
      remove :user_id
    end
  end
end
