defmodule KilnCMS.Repo.Migrations.NotificationActorId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notifications) do
      add :actor_id, :uuid
    end
  end

  def down do
    alter table(:notifications) do
      remove :actor_id
    end
  end
end
