defmodule KilnCMS.Repo.Migrations.AddFederationBlocksAndNonces do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:federation_blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "federation_blocks_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :kind, :text, null: false
      add :value, :text, null: false
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:federation_blocks, [:org_id, :kind, :value],
             name: "federation_blocks_one_per_target_index"
           )

    create table(:federation_seen_signatures, primary_key: false) do
      add :signature_hash, :text, null: false, primary_key: true
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:federation_seen_signatures, [:expires_at],
             name: "federation_seen_signatures_expires_at_index"
           )
  end

  def down do
    drop_if_exists index(:federation_seen_signatures, [:expires_at],
                     name: "federation_seen_signatures_expires_at_index"
                   )

    drop table(:federation_seen_signatures)

    drop constraint(:federation_blocks, "federation_blocks_org_id_fkey")

    drop_if_exists unique_index(:federation_blocks, [:org_id, :kind, :value],
                     name: "federation_blocks_one_per_target_index"
                   )

    drop table(:federation_blocks)
  end
end
