defmodule KilnCMS.Repo.Migrations.CommentNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :notify_on_comment, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:users) do
      remove :notify_on_comment
    end
  end
end
