defmodule KilnCMS.Repo.Migrations.AddUserStatusMarks do
  @moduledoc """
  Adds `users.status_marks` — how the content list marks each row's status
  (#1323).

  Generated by `mix ash.codegen add_user_status_marks`. Unlike `nav_preset`,
  existing accounts are NOT backfilled to the old behaviour: the trigram glyph
  they saw until now is exactly what #1323 asks to stop showing by default, and
  the words it is replaced with carry the same three facts. Anyone who read the
  glyph gets it back from Your settings → Content list.
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :status_marks, :text, null: false, default: "words"
    end
  end

  def down do
    alter table(:users) do
      remove :status_marks
    end
  end
end
