defmodule KilnCMS.Repo.Migrations.AddScheduledUnpublish do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :unpublish_at, :utc_datetime_usec
    end

    alter table(:pages) do
      add :unpublish_at, :utc_datetime_usec
    end

    alter table(:entries) do
      add :unpublish_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:entries) do
      remove :unpublish_at
    end

    alter table(:pages) do
      remove :unpublish_at
    end

    alter table(:posts) do
      remove :unpublish_at
    end
  end
end
