defmodule KilnCMS.Repo.Migrations.RbacFieldGrants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:org_memberships) do
      add :field_grants, :map, null: false, default: %{}
    end

    alter table(:users) do
      add :field_grants, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:users) do
      remove :field_grants
    end

    alter table(:org_memberships) do
      remove :field_grants
    end
  end
end
