defmodule KilnCMS.Repo.Migrations.AddEditableTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :editable_types, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:users) do
      remove :editable_types
    end
  end
end
