defmodule KilnCMS.Repo.Migrations.Relationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tags, [:slug], name: "tags_unique_slug_index")

    create table(:related_posts, primary_key: false) do
      add :source_id,
          references(:posts,
            column: :id,
            name: "related_posts_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :related_id,
          references(:posts,
            column: :id,
            name: "related_posts_related_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    create table(:related_pages, primary_key: false) do
      add :source_id,
          references(:pages,
            column: :id,
            name: "related_pages_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :related_id,
          references(:pages,
            column: :id,
            name: "related_pages_related_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    alter table(:posts) do
      add :category_id, :uuid
      add :featured_image_id, :uuid
    end

    create table(:post_tags, primary_key: false) do
      add :post_id,
          references(:posts,
            column: :id,
            name: "post_tags_post_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "post_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    alter table(:pages) do
      add :category_id, :uuid
      add :featured_image_id, :uuid
    end

    create table(:page_tags, primary_key: false) do
      add :page_id,
          references(:pages,
            column: :id,
            name: "page_tags_page_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "page_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:posts) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "posts_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :featured_image_id,
             references(:media_items,
               column: :id,
               name: "posts_featured_image_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:pages) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "pages_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :featured_image_id,
             references(:media_items,
               column: :id,
               name: "pages_featured_image_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:categories) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:categories, [:slug], name: "categories_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:categories, [:slug], name: "categories_unique_slug_index")

    alter table(:categories) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :slug
      remove :name
    end

    drop constraint(:pages, "pages_category_id_fkey")

    drop constraint(:pages, "pages_featured_image_id_fkey")

    alter table(:pages) do
      modify :featured_image_id, :uuid
      modify :category_id, :uuid
    end

    drop constraint(:posts, "posts_category_id_fkey")

    drop constraint(:posts, "posts_featured_image_id_fkey")

    alter table(:posts) do
      modify :featured_image_id, :uuid
      modify :category_id, :uuid
    end

    drop table(:categories)

    drop constraint(:page_tags, "page_tags_page_id_fkey")

    drop constraint(:page_tags, "page_tags_tag_id_fkey")

    drop table(:page_tags)

    alter table(:pages) do
      remove :featured_image_id
      remove :category_id
    end

    drop constraint(:post_tags, "post_tags_post_id_fkey")

    drop constraint(:post_tags, "post_tags_tag_id_fkey")

    drop table(:post_tags)

    alter table(:posts) do
      remove :featured_image_id
      remove :category_id
    end

    drop constraint(:related_pages, "related_pages_source_id_fkey")

    drop constraint(:related_pages, "related_pages_related_id_fkey")

    drop table(:related_pages)

    drop constraint(:related_posts, "related_posts_source_id_fkey")

    drop constraint(:related_posts, "related_posts_related_id_fkey")

    drop table(:related_posts)

    drop_if_exists unique_index(:tags, [:slug], name: "tags_unique_slug_index")

    drop table(:tags)
  end
end
