defmodule KilnCMS.Repo.Migrations.AddMailSettingsProviderCheck do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:mail_settings, :dkim_key_provider_must_be_known,
             check: """
               dkim_key_provider IN ('database', 'env', 'file')
             """
           )

    alter table(:mail_settings) do
      modify :dkim_key_provider_config, :map, null: false
    end
  end

  def down do
    alter table(:mail_settings) do
      modify :dkim_key_provider_config, :map, null: true
    end

    drop_if_exists constraint(:mail_settings, :dkim_key_provider_must_be_known)
  end
end
