defmodule KilnCMS.Repo.Migrations.AddContentViews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:content_views, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content_type, :text, null: false
      add :content_id, :uuid, null: false
      add :views, :bigint, null: false, default: 1
      add :last_viewed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:content_views, [:content_type, :content_id],
             name: "content_views_unique_content_index"
           )
  end

  def down do
    drop_if_exists unique_index(:content_views, [:content_type, :content_id],
                     name: "content_views_unique_content_index"
                   )

    drop table(:content_views)
  end
end
