defmodule KilnCMS.Repo.Migrations.AddAnchorBoundaryTimestamp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:history_anchors) do
      add :last_version_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:history_anchors) do
      remove :last_version_at
    end
  end
end
