defmodule KilnCMS.Repo.Migrations.SocialAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:social_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "social_accounts_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :provider, :text, null: false
      add :handle, :text
      add :instance_url, :text
      add :credential_encrypted, :binary
      add :enabled, :boolean, null: false, default: true
      add :last_posted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:social_accounts, [:org_id, :provider],
             name: "social_accounts_one_per_provider_index"
           )

    create table(:social_posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "social_posts_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :account_id,
          references(:social_accounts,
            column: :id,
            name: "social_posts_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :provider, :text, null: false
      add :content_type, :text, null: false
      add :content_id, :uuid, null: false
      add :content_published_at, :utc_datetime_usec, null: false
      add :automation_rule_id, :uuid
      add :state, :text, null: false, default: "claimed"
      add :text, :text
      add :url, :text
      add :remote_id, :text
      add :remote_url, :text
      add :error, :text
      add :posted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:social_posts, [:org_id, :account_id, :content_id, :content_published_at],
             name: "social_posts_announce_once_index"
           )
  end

  def down do
    drop constraint(:social_posts, "social_posts_org_id_fkey")

    drop constraint(:social_posts, "social_posts_account_id_fkey")

    drop_if_exists unique_index(
                     :social_posts,
                     [:org_id, :account_id, :content_id, :content_published_at],
                     name: "social_posts_announce_once_index"
                   )

    drop table(:social_posts)

    drop constraint(:social_accounts, "social_accounts_org_id_fkey")

    drop_if_exists unique_index(:social_accounts, [:org_id, :provider],
                     name: "social_accounts_one_per_provider_index"
                   )

    drop table(:social_accounts)
  end
end
