defmodule KilnCMS.Repo.Migrations.AddContentDraftSnapshot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:entries) do
      add :draft_snapshot, :map
      add :draft_saved_at, :utc_datetime_usec
    end

    alter table(:posts) do
      add :draft_snapshot, :map
      add :draft_saved_at, :utc_datetime_usec
    end

    alter table(:pages) do
      add :draft_snapshot, :map
      add :draft_saved_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:pages) do
      remove :draft_saved_at
      remove :draft_snapshot
    end

    alter table(:posts) do
      remove :draft_saved_at
      remove :draft_snapshot
    end

    alter table(:entries) do
      remove :draft_saved_at
      remove :draft_snapshot
    end
  end
end
