defmodule KilnCMS.Repo.Migrations.AddIdempotentRequests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:idempotent_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :org_id, :uuid, null: false
      add :scope, :text, null: false
      add :key, :text, null: false
      add :fingerprint, :text, null: false
      add :status, :text, null: false, default: "in_progress"
      add :response_status, :bigint
      add :response_headers, :map, default: %{}
      add :response_body, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:idempotent_requests, [:org_id, :scope, :key],
             name: "idempotent_requests_unique_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:idempotent_requests, [:org_id, :scope, :key],
                     name: "idempotent_requests_unique_key_index"
                   )

    drop table(:idempotent_requests)
  end
end
