defmodule KilnCMS.Repo.Migrations.AddSyncExposures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:pages_versions, [:org_id, :version_inserted_at])

    create index(:entries_versions, [:org_id, :version_inserted_at])

    create index(:posts_versions, [:org_id, :version_inserted_at])

    create table(:sync_exposures, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "sync_exposures_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :document_type, :text, null: false
      add :document_id, :uuid, null: false
      add :type_name, :text, null: false
      add :type_definition_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:sync_exposures, [:org_id, :document_id],
             name: "sync_exposures_document_index"
           )
  end

  def down do
    drop constraint(:sync_exposures, "sync_exposures_org_id_fkey")

    drop_if_exists unique_index(:sync_exposures, [:org_id, :document_id],
                     name: "sync_exposures_document_index"
                   )

    drop table(:sync_exposures)

    drop_if_exists index(:posts_versions, [:org_id, :version_inserted_at])

    drop_if_exists index(:entries_versions, [:org_id, :version_inserted_at])

    drop_if_exists index(:pages_versions, [:org_id, :version_inserted_at])
  end
end
