defmodule KilnCMS.Repo.Migrations.AddAutomationProvenanceToCommentsAndTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  Generated by `mix ash_postgres.generate_migrations`, then hand-edited past
  what codegen produces to add a `down/0` guard codegen cannot write:
  `ensure_no_automation_authored_rows/0` below. AGENTS.md's rule against
  hand-editing generated migrations has no exception clause — this is a
  deliberate, disclosed departure from it, not a sanctioned one (#1252
  review), made because a blind rollback would otherwise fail with an opaque
  Postgres constraint violation instead of a clear, actionable error.
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      modify :creator_id, :uuid, null: true
      add :created_by_rule_id, :uuid
    end

    alter table(:comments) do
      modify :author_id, :uuid, null: true
      modify :block_id, :uuid, null: true
      add :created_by_rule_id, :uuid
    end
  end

  def down do
    ensure_no_automation_authored_rows()

    alter table(:comments) do
      remove :created_by_rule_id
      modify :block_id, :uuid, null: false
      modify :author_id, :uuid, null: false
    end

    alter table(:tasks) do
      remove :created_by_rule_id
      modify :creator_id, :uuid, null: false
    end
  end

  # `up/0` relaxed these to nullable specifically so automation (#946) could
  # write a comment/task with no human author/creator, and a document-level
  # comment with no block. Restoring `null: false` blind, the autogenerated
  # default, fails with an opaque Postgres NOT NULL violation the moment any
  # such row exists — turning "roll back this migration" into a stuck
  # deploy discovered mid-rollback rather than before it's attempted.
  #
  # Checks the columns `down/0` actually restores `NOT NULL` on
  # (`author_id`/`block_id` on comments, `creator_id` on tasks), not
  # `created_by_rule_id` (#1252 review: those three are independently
  # nullable — `CMS.add_comment`/`assign_task` accept `created_by_rule_id`
  # without requiring it alongside a nil actor — so a row created with a nil
  # actor and no rule id would pass a `created_by_rule_id IS NOT NULL` count
  # of zero and still blow up the very `modify ... null: false` this guard
  # exists to preempt).
  defp ensure_no_automation_authored_rows do
    %{rows: [[comments]]} =
      repo().query!("SELECT count(*) FROM comments WHERE author_id IS NULL OR block_id IS NULL")

    %{rows: [[tasks]]} =
      repo().query!("SELECT count(*) FROM tasks WHERE creator_id IS NULL")

    if comments > 0 or tasks > 0 do
      raise """
      Cannot roll back #{__MODULE__}: #{comments} comment(s) have a null \
      author_id or block_id and #{tasks} task(s) have a null creator_id, \
      which would violate the NOT NULL constraints this rollback restores \
      (#946 let automation write rows with no human author/creator). Delete \
      or reassign those rows first if you need to roll back.
      """
    end
  end
end
