defmodule KilnCMS.Repo.Migrations.AddInAppNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :org_id, :uuid, null: false
      add :event, :text, null: false
      add :content_type, :text, null: false
      add :content_id, :uuid, null: false
      add :block_id, :uuid
      add :title, :text, null: false
      add :excerpt, :text
      add :actor_name, :text
      add :read_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "notifications_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:notifications, [:org_id, :user_id, :inserted_at],
             name: "notifications_user_lookup_index"
           )
  end

  def down do
    drop constraint(:notifications, "notifications_user_id_fkey")

    drop_if_exists index(:notifications, [:org_id, :user_id, :inserted_at],
                     name: "notifications_user_lookup_index"
                   )

    drop table(:notifications)
  end
end
