defmodule KilnCMS.Repo.Migrations.AddFunnels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:funnels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "funnels_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false
      add :slug, :text, null: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:funnels, [:org_id, :slug], name: "funnels_unique_slug_index")

    create table(:funnel_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "funnel_steps_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :content_type, :text, null: false
      add :content_id, :uuid, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :funnel_id,
          references(:funnels,
            column: :id,
            name: "funnel_steps_funnel_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:funnel_steps, "funnel_steps_org_id_fkey")

    drop constraint(:funnel_steps, "funnel_steps_funnel_id_fkey")

    drop table(:funnel_steps)

    drop constraint(:funnels, "funnels_org_id_fkey")

    drop_if_exists unique_index(:funnels, [:org_id, :slug], name: "funnels_unique_slug_index")

    drop table(:funnels)
  end
end
