defmodule KilnCMS.Repo.Migrations.AddFieldDefinitionNamesRecord do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:field_definitions) do
      add :names_record, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:field_definitions) do
      remove :names_record
    end
  end
end
