defmodule KilnCMS.Repo.Migrations.GovernanceChainCheckpoints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chain_checkpoint_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "chain_checkpoint_entries_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :checkpoint_id, :uuid, null: false
      add :checkpoint_sequence, :bigint, null: false
      add :resource_type, :text, null: false
      add :source_id, :uuid, null: false
      add :head_anchor_id, :uuid, null: false
      add :head_sequence, :bigint, null: false
      add :chain_hash, :text, null: false
      add :version_count, :bigint, null: false
      add :proof, {:array, :map}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:chain_checkpoint_entries, [:org_id, :checkpoint_id, :resource_type, :source_id],
             unique: true
           )

    create index(:chain_checkpoint_entries, [
             :org_id,
             :resource_type,
             :source_id,
             :head_sequence,
             :checkpoint_sequence
           ])

    create table(:chain_checkpoints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:chain_checkpoint_entries) do
      modify :checkpoint_id,
             references(:chain_checkpoints,
               column: :id,
               name: "chain_checkpoint_entries_checkpoint_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    alter table(:chain_checkpoints) do
      add :org_id,
          references(:organizations,
            column: :id,
            name: "chain_checkpoints_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :sequence, :bigint, null: false
      add :root, :text, null: false
      add :document_count, :bigint, null: false
      add :covered_at, :utc_datetime_usec, null: false

      add :prev_checkpoint_id,
          references(:chain_checkpoints,
            column: :id,
            name: "chain_checkpoints_prev_checkpoint_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :restrict
          )

      add :prev_checkpoint_digest, :text
      add :signature, :text
      add :key_id, :text
      add :witness, :text, null: false, default: "none"
      add :witness_receipt, :map
      add :witnessed_at, :utc_datetime_usec
      add :witness_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:chain_checkpoints, [:org_id, :witnessed_at, :sequence])

    create index(:chain_checkpoints, [:org_id, :sequence], unique: true)
  end

  def down do
    drop constraint(:chain_checkpoints, "chain_checkpoints_org_id_fkey")

    drop constraint(:chain_checkpoints, "chain_checkpoints_prev_checkpoint_id_fkey")

    drop_if_exists index(:chain_checkpoints, [:org_id, :sequence])

    drop_if_exists index(:chain_checkpoints, [:org_id, :witnessed_at, :sequence])

    alter table(:chain_checkpoints) do
      remove :updated_at
      remove :inserted_at
      remove :witness_error
      remove :witnessed_at
      remove :witness_receipt
      remove :witness
      remove :key_id
      remove :signature
      remove :prev_checkpoint_digest
      remove :prev_checkpoint_id
      remove :covered_at
      remove :document_count
      remove :root
      remove :sequence
      remove :org_id
    end

    drop constraint(:chain_checkpoint_entries, "chain_checkpoint_entries_checkpoint_id_fkey")

    alter table(:chain_checkpoint_entries) do
      modify :checkpoint_id, :uuid
    end

    drop table(:chain_checkpoints)

    drop constraint(:chain_checkpoint_entries, "chain_checkpoint_entries_org_id_fkey")

    drop_if_exists index(:chain_checkpoint_entries, [
                     :org_id,
                     :resource_type,
                     :source_id,
                     :head_sequence,
                     :checkpoint_sequence
                   ])

    drop_if_exists index(:chain_checkpoint_entries, [
                     :org_id,
                     :checkpoint_id,
                     :resource_type,
                     :source_id
                   ])

    drop table(:chain_checkpoint_entries)
  end
end
