defmodule KilnCMS.Repo.Migrations.AddContentReleases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:release_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "release_items_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :content_type, :text, null: false
      add :content_id, :uuid, null: false
      add :action, :text, null: false, default: "publish"
      add :status, :text, null: false, default: "pending"
      add :prior_state, :text
      add :prior_version_id, :uuid
      add :applied_at, :utc_datetime_usec

      add :added_by_id,
          references(:users,
            column: :id,
            name: "release_items_added_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :release_id, :uuid, null: false
    end

    create index(:release_items, [:org_id, :release_id, :status],
             name: "release_items_release_status_index"
           )

    create unique_index(:release_items, [:org_id, :content_type, :content_id],
             name: "release_items_one_pending_per_content_index",
             where: "(status = 'pending')"
           )

    create table(:content_releases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:release_items) do
      modify :release_id,
             references(:content_releases,
               column: :id,
               name: "release_items_release_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:content_releases) do
      add :org_id,
          references(:organizations,
            column: :id,
            name: "content_releases_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false
      add :description, :text
      add :scheduled_at, :utc_datetime_usec
      add :published_at, :utc_datetime_usec
      add :rolled_back_at, :utc_datetime_usec
      add :failure_reason, :text
      add :failed_item_id, :uuid

      add :creator_id,
          references(:users,
            column: :id,
            name: "content_releases_creator_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :triggered_by_id,
          references(:users,
            column: :id,
            name: "content_releases_triggered_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "open"
    end

    create index(:content_releases, [:org_id, :state, :scheduled_at],
             name: "content_releases_state_index"
           )
  end

  def down do
    drop constraint(:content_releases, "content_releases_org_id_fkey")

    drop constraint(:content_releases, "content_releases_creator_id_fkey")

    drop constraint(:content_releases, "content_releases_triggered_by_id_fkey")

    drop_if_exists index(:content_releases, [:org_id, :state, :scheduled_at],
                     name: "content_releases_state_index"
                   )

    alter table(:content_releases) do
      remove :state
      remove :updated_at
      remove :inserted_at
      remove :triggered_by_id
      remove :creator_id
      remove :failed_item_id
      remove :failure_reason
      remove :rolled_back_at
      remove :published_at
      remove :scheduled_at
      remove :description
      remove :name
      remove :org_id
    end

    drop constraint(:release_items, "release_items_release_id_fkey")

    alter table(:release_items) do
      modify :release_id, :uuid
    end

    drop table(:content_releases)

    drop constraint(:release_items, "release_items_org_id_fkey")

    drop constraint(:release_items, "release_items_added_by_id_fkey")

    drop_if_exists unique_index(:release_items, [:org_id, :content_type, :content_id],
                     name: "release_items_one_pending_per_content_index"
                   )

    drop_if_exists index(:release_items, [:org_id, :release_id, :status],
                     name: "release_items_release_status_index"
                   )

    drop table(:release_items)
  end
end
