defmodule KilnCMS.Repo.Migrations.AddTenantlessLookupIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:block_embeddings, [:document_type, :document_id],
             name: "block_embeddings_doc_lookup_index"
           )

    create index(:reference_edges, [:from_type, :from_id],
             name: "reference_edges_from_source_lookup_index"
           )

    create index(:entries, [:slug, :locale], name: "entries_slug_locale_lookup_index")

    create index(:published_artifacts, [:document_type, :document_id, :surface],
             name: "published_artifacts_doc_surface_lookup_index"
           )

    create index(:posts, [:slug, :locale], name: "posts_slug_locale_lookup_index")

    create index(:pages, [:slug, :locale], name: "pages_slug_locale_lookup_index")
  end

  def down do
    drop_if_exists index(:pages, [:slug, :locale], name: "pages_slug_locale_lookup_index")

    drop_if_exists index(:posts, [:slug, :locale], name: "posts_slug_locale_lookup_index")

    drop_if_exists index(:published_artifacts, [:document_type, :document_id, :surface],
                     name: "published_artifacts_doc_surface_lookup_index"
                   )

    drop_if_exists index(:entries, [:slug, :locale], name: "entries_slug_locale_lookup_index")

    drop_if_exists index(:reference_edges, [:from_type, :from_id],
                     name: "reference_edges_from_source_lookup_index"
                   )

    drop_if_exists index(:block_embeddings, [:document_type, :document_id],
                     name: "block_embeddings_doc_lookup_index"
                   )
  end
end
