defmodule KilnCMS.Repo.Migrations.AddBlockEmbeddings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:block_embeddings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :document_type, :text, null: false
      add :document_id, :uuid, null: false
      add :block_key, :text, null: false
      add :block_type, :text, null: false
      add :content_hash, :text, null: false
      add :ancestor_context, :text
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec
    end

    create index(:block_embeddings, ["embedding vector_cosine_ops"],
             name: "block_embeddings_hnsw_index",
             using: "hnsw"
           )

    create unique_index(:block_embeddings, [:document_type, :document_id, :block_key],
             name: "block_embeddings_doc_block_index"
           )
  end

  def down do
    drop_if_exists unique_index(:block_embeddings, [:document_type, :document_id, :block_key],
                     name: "block_embeddings_doc_block_index"
                   )

    drop_if_exists index(:block_embeddings, ["embedding vector_cosine_ops"],
                     name: "block_embeddings_hnsw_index"
                   )

    drop table(:block_embeddings)
  end
end
