defmodule KilnCMS.Repo.Migrations.DropOldSearchGin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:posts, ["to_tsvector('english', coalesce(search_text, ''))"],
                     name: "posts_search_text_gin_index"
                   )

    drop_if_exists index(:pages, ["to_tsvector('english', coalesce(search_text, ''))"],
                     name: "pages_search_text_gin_index"
                   )
  end

  def down do
    create index(:pages, ["to_tsvector('english', coalesce(search_text, ''))"],
             name: "pages_search_text_gin_index",
             using: "gin"
           )

    create index(:posts, ["to_tsvector('english', coalesce(search_text, ''))"],
             name: "posts_search_text_gin_index",
             using: "gin"
           )
  end
end
