defmodule KilnCMS.Repo.Migrations.AddMediaDimensionsVariants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:media_items) do
      add :width, :bigint
      add :height, :bigint
      add :variants, :map, default: %{}
    end
  end

  def down do
    alter table(:media_items) do
      remove :variants
      remove :height
      remove :width
    end
  end
end
