defmodule KilnCMS.Repo.Migrations.AddSearchAnalytics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:search_queries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :query, :text, null: false
      add :locale, :text, null: false, default: "en"
      add :count, :bigint, null: false, default: 1
      add :result_count, :bigint
      add :last_searched_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:search_queries, [:query, :locale],
             name: "search_queries_unique_query_index"
           )
  end

  def down do
    drop_if_exists unique_index(:search_queries, [:query, :locale],
                     name: "search_queries_unique_query_index"
                   )

    drop table(:search_queries)
  end
end
