defmodule KilnCMS.Repo.Migrations.AddExternalLinkChecker do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_link_check, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_link_check_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :external_enabled, :boolean, null: false, default: false
      add :last_swept_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:site_link_check, [:org_id], name: "site_link_check_one_per_org_index")

    create table(:external_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "external_links_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :url, :text, null: false
      add :url_digest, :text, null: false
      add :host, :text
      add :document_type, :text, null: false
      add :document_id, :uuid, null: false
      add :document_title, :text
      add :block_index, :bigint
      add :outcome, :text, null: false, default: "pending"
      add :status_code, :bigint
      add :reason, :text
      add :failure_count, :bigint, null: false, default: 0
      add :first_failed_at, :utc_datetime_usec
      add :last_checked_at, :utc_datetime_usec
      add :last_seen_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:external_links, [:org_id, :outcome])

    create index(:external_links, [:org_id, :url_digest])

    create unique_index(:external_links, [:org_id, :document_type, :document_id, :url_digest],
             name: "external_links_unique_occurrence_index"
           )
  end

  def down do
    drop constraint(:external_links, "external_links_org_id_fkey")

    drop_if_exists unique_index(
                     :external_links,
                     [:org_id, :document_type, :document_id, :url_digest],
                     name: "external_links_unique_occurrence_index"
                   )

    drop_if_exists index(:external_links, [:org_id, :url_digest])

    drop_if_exists index(:external_links, [:org_id, :outcome])

    drop table(:external_links)

    drop constraint(:site_link_check, "site_link_check_org_id_fkey")

    drop_if_exists unique_index(:site_link_check, [:org_id],
                     name: "site_link_check_one_per_org_index"
                   )

    drop table(:site_link_check)
  end
end
