defmodule KilnCMS.Repo.Migrations.AddMediaUploader do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:media_items) do
      add :uploaded_by_id,
          references(:users,
            column: :id,
            name: "media_items_uploaded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:media_items, "media_items_uploaded_by_id_fkey")

    alter table(:media_items) do
      remove :uploaded_by_id
    end
  end
end
