defmodule KilnCMS.Repo.Migrations.Passkeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:passkeys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false, default: "Passkey"
      add :credential_id, :text, null: false
      add :public_key, :binary, null: false
      add :sign_count, :bigint, null: false, default: 0
      add :last_used_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "passkeys_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:passkeys, [:user_id])

    create unique_index(:passkeys, [:credential_id], name: "passkeys_unique_credential_index")
  end

  def down do
    drop constraint(:passkeys, "passkeys_user_id_fkey")

    drop_if_exists unique_index(:passkeys, [:credential_id],
                     name: "passkeys_unique_credential_index"
                   )

    drop_if_exists index(:passkeys, [:user_id])

    drop table(:passkeys)
  end
end
