defmodule KilnCMS.Repo.Migrations.ContentTreeParentAndPosition1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:pages, [:parent_id], name: "pages_parent_lookup_index", concurrently: true)

    create index(:posts, [:parent_id], name: "posts_parent_lookup_index", concurrently: true)

    create index(:entries, [:parent_id], name: "entries_parent_lookup_index", concurrently: true)
  end

  def down do
    drop_if_exists index(:entries, [:parent_id], name: "entries_parent_lookup_index")

    drop_if_exists index(:posts, [:parent_id], name: "posts_parent_lookup_index")

    drop_if_exists index(:pages, [:parent_id], name: "pages_parent_lookup_index")
  end
end
