defmodule KilnCMS.Repo.Migrations.AddMediaAudienceAndDownloads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`,
  then hand-trimmed: the generator also proposed dropping and recreating 17
  unrelated foreign-key constraints (funnel_steps, tags, chain_checkpoints,
  pages, chain_checkpoint_entries, newsletter_sends, history_anchors,
  field_definitions, posts, entries, form_fields, form_submissions,
  webhook_deliveries, newsletter_segment_memberships, taggings,
  newsletter_segments, billing_memberships) — a semantic no-op (identical
  constraint, same columns/on_delete) that only existed because the
  generator's snapshot hash for those resources doesn't agree with itself
  between a core-only run and one with the example overlay activated.
  Regenerating them here pinned this branch to one context's hash and broke
  the other's `ash.codegen --check`. Left untouched (and their accompanying
  snapshot files removed from this branch), this migration is exactly what
  `media_items` needs — nothing else.
  """

  use Ecto.Migration

  def up do
    alter table(:media_items) do
      add :audience, :text, null: false, default: "public"
      add :download_count, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:media_items) do
      remove :download_count
      remove :audience
    end
  end
end
