defmodule KilnCMS.Repo.Migrations.AddFormBuilderSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:form_fields) do
      add :placeholder, :text
      add :default_value, :text
      add :width, :text, null: false, default: "full"
    end

    alter table(:forms) do
      add :submit_label, :text
    end
  end

  def down do
    alter table(:forms) do
      remove :submit_label
    end

    alter table(:form_fields) do
      remove :width
      remove :default_value
      remove :placeholder
    end
  end
end
