defmodule KilnCMS.Repo.Migrations.AddAnchorSequence do
  @moduledoc """
  Adds `history_anchors.sequence` — the signed position that decides which
  anchor is the verification baseline (#666).

  Generated by `mix ash.codegen add_anchor_sequence`, then edited in two ways
  codegen cannot express. Spelled out because AGENTS.md says not to hand-edit
  generated migrations, and this is the exception it does not anticipate: a
  `NOT NULL` column on a table that already has rows.

    1. **Backfilled before the constraint.** Codegen emits
       `add :sequence, :bigint, null: false`, which fails outright on any
       populated table. The column is added nullable, filled with `row_number()`
       per document in `(inserted_at, id)` order — the order the chain was
       written in — and only then made `NOT NULL`.

    2. **The foreign key is added `NOT VALID`, then validated separately, and a
       validation failure warns rather than raising.** Added the ordinary way,
       it fails with a bare `23503` and a UUID on any chain that already has a
       hole — and since migrations run on boot, that is a container that will
       not start, over a *finding* rather than a fault. Split, the constraint
       lands unconditionally and protects every new write, the operator is told
       which rows are dangling and what to do, and the deployment comes up.

       Refusing to boot would also be the wrong trade on its own terms: the hole
       is what #597's tamper-evidence exists to surface, and turning a detection
       into an outage is how detections get switched off.

       It is an `execute/1` **closure**, not a string, and that is load-bearing:
       the string form only buffers the statement, and the buffer is flushed
       after `up/0` has already returned, so anything wrapped around it in this
       function would never see the outcome. The closure runs during the flush,
       in order, and can branch on what it finds.

  `down` is deliberately lossy and says so — see the CHANGELOG's Upgrading note.
  `sequence` is inside the v4 signed payload, so removing the column makes every
  anchor minted since this migration fail its own signature check. Rolling back
  is a one-way door for the audit surface.
  """

  use Ecto.Migration

  # Positions are per document, and `(inserted_at, id)` is the order the anchors
  # were written in — the same tiebreak `Chain.anchors/4` used before `sequence`
  # existed, so a backfilled chain reads in exactly the order it always did.
  @backfill """
  WITH numbered AS (
    SELECT id,
           row_number() OVER (
             PARTITION BY org_id, resource_type, source_id
             ORDER BY inserted_at, id
           ) AS position
      FROM history_anchors
  )
  UPDATE history_anchors AS a
     SET sequence = numbered.position
    FROM numbered
   WHERE a.id = numbered.id
  """

  @dangling """
  SELECT a.id, a.prev_anchor_id
    FROM history_anchors a
   WHERE a.prev_anchor_id IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM history_anchors p WHERE p.id = a.prev_anchor_id)
  """

  def up do
    alter table(:history_anchors) do
      add :sequence, :bigint
    end

    execute(@backfill)

    alter table(:history_anchors) do
      modify :sequence, :bigint, null: false
    end

    create index(:history_anchors, [:org_id, :resource_type, :source_id, :sequence], unique: true)

    execute(&add_prev_anchor_fkey/0, &drop_prev_anchor_fkey/0)

    create index(:history_anchors, [:org_id, :prev_anchor_id])
  end

  def down do
    drop_if_exists index(:history_anchors, [:org_id, :prev_anchor_id])

    execute(&drop_prev_anchor_fkey/0, &add_prev_anchor_fkey/0)

    drop_if_exists index(:history_anchors, [:org_id, :resource_type, :source_id, :sequence])

    alter table(:history_anchors) do
      remove :sequence
    end
  end

  defp add_prev_anchor_fkey do
    repo().query!("""
    ALTER TABLE history_anchors
      ADD CONSTRAINT history_anchors_prev_anchor_id_fkey
      FOREIGN KEY (prev_anchor_id) REFERENCES history_anchors(id)
      ON DELETE RESTRICT ON UPDATE RESTRICT
      NOT VALID
    """)

    case repo().query!(@dangling) do
      %{rows: []} ->
        repo().query!(
          "ALTER TABLE history_anchors VALIDATE CONSTRAINT history_anchors_prev_anchor_id_fkey"
        )

      %{rows: rows} ->
        IO.warn("""
        #{length(rows)} history anchor(s) name a predecessor that no longer exists.

        The foreign key has been added and is protecting every new write, but it
        is NOT VALID: the existing rows are what it cannot vouch for. They are a
        finding, not a migration problem — an anchor was deleted while its
        successor survived, which is what #597's tamper-evidence exists to
        surface. `Chain.verify/4` reports those documents as tampered.

        List them with:

        #{String.trim(@dangling)}

        Once they are accounted for — restored from a backup, or the successors
        that name them removed — mark the constraint good:

          ALTER TABLE history_anchors
            VALIDATE CONSTRAINT history_anchors_prev_anchor_id_fkey;
        """)
    end
  end

  defp drop_prev_anchor_fkey do
    repo().query!(
      "ALTER TABLE history_anchors DROP CONSTRAINT IF EXISTS history_anchors_prev_anchor_id_fkey"
    )
  end
end
