defmodule KilnCMS.Repo.Migrations.AddMediaDerivatives do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:media_derivatives, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "media_derivatives_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :storage_key, :text, null: false
      add :source_key, :text, null: false
      add :focal, :text
      add :content_type, :text, null: false
      add :byte_size, :bigint, null: false
      add :width, :bigint, null: false
      add :height, :bigint, null: false
      add :private, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :media_item_id,
          references(:media_items,
            column: :id,
            name: "media_derivatives_media_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:media_derivatives, [:org_id, :media_item_id],
             name: "media_derivatives_media_item_index"
           )

    create unique_index(:media_derivatives, [:org_id, :storage_key],
             name: "media_derivatives_unique_storage_key_index"
           )
  end

  def down do
    drop constraint(:media_derivatives, "media_derivatives_org_id_fkey")

    drop constraint(:media_derivatives, "media_derivatives_media_item_id_fkey")

    drop_if_exists unique_index(:media_derivatives, [:org_id, :storage_key],
                     name: "media_derivatives_unique_storage_key_index"
                   )

    drop_if_exists index(:media_derivatives, [:org_id, :media_item_id],
                     name: "media_derivatives_media_item_index"
                   )

    drop table(:media_derivatives)
  end
end
