defmodule KilnCMS.Repo.Migrations.SeoPatterns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:type_definitions) do
      add :seo_title_pattern, :text
      add :seo_description_pattern, :text
    end
  end

  def down do
    alter table(:type_definitions) do
      remove :seo_description_pattern
      remove :seo_title_pattern
    end
  end
end
