defmodule KilnCMS.Repo.Migrations.AddTagEmbeddings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tag_embeddings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "tag_embeddings_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false
      add :embedding, :"vector(384)"
      add :embedded_at, :utc_datetime_usec

      add :tag_id,
          references(:tags,
            column: :id,
            name: "tag_embeddings_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:tag_embeddings, [:org_id, :tag_id],
             name: "tag_embeddings_one_per_tag_index"
           )
  end

  def down do
    drop constraint(:tag_embeddings, "tag_embeddings_org_id_fkey")

    drop constraint(:tag_embeddings, "tag_embeddings_tag_id_fkey")

    drop_if_exists unique_index(:tag_embeddings, [:org_id, :tag_id],
                     name: "tag_embeddings_one_per_tag_index"
                   )

    drop table(:tag_embeddings)
  end
end
