defmodule KilnCMS.Repo.Migrations.AddSeoKeywords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:entries) do
      add :seo_keywords, :text
    end

    alter table(:posts) do
      add :seo_keywords, :text
    end

    alter table(:pages) do
      add :seo_keywords, :text
    end
  end

  def down do
    alter table(:pages) do
      remove :seo_keywords
    end

    alter table(:posts) do
      remove :seo_keywords
    end

    alter table(:entries) do
      remove :seo_keywords
    end
  end
end
