defmodule KilnCMS.Repo.Migrations.AddSiteMeilisearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_meilisearch, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_meilisearch_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:site_meilisearch, [:org_id], name: "site_meilisearch_one_per_org_index")

    alter table(:site_meilisearch) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enabled, :boolean, null: false, default: true
      add :url, :text
      add :index, :text, default: "kiln_content"
      add :api_key_encrypted, :binary
    end
  end

  def down do
    drop constraint(:site_meilisearch, "site_meilisearch_org_id_fkey")

    alter table(:site_meilisearch) do
      remove :api_key_encrypted
      remove :index
      remove :url
      remove :enabled
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:site_meilisearch, [:org_id],
                     name: "site_meilisearch_one_per_org_index"
                   )

    drop table(:site_meilisearch)
  end
end
