defmodule KilnCMS.Repo.Migrations.AddSiteMailRelays do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_mail_relays, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_mail_relays_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enabled, :boolean, null: false, default: true
      add :host, :text
      add :port, :bigint, null: false, default: 587
      add :security, :text, null: false, default: "starttls"
      add :username, :text
      add :password_encrypted, :binary
      add :from_email, :text
      add :from_name, :text
    end

    create unique_index(:site_mail_relays, [:org_id], name: "site_mail_relays_one_per_org_index")

    create constraint(:site_mail_relays, :site_mail_relay_security_must_be_known,
             check: """
               security IN ('starttls', 'tls')
             """
           )
  end

  def down do
    drop_if_exists constraint(:site_mail_relays, :site_mail_relay_security_must_be_known)

    drop constraint(:site_mail_relays, "site_mail_relays_org_id_fkey")

    drop_if_exists unique_index(:site_mail_relays, [:org_id],
                     name: "site_mail_relays_one_per_org_index"
                   )

    drop table(:site_mail_relays)
  end
end
