defmodule KilnCMS.Repo.Migrations.RbacReadableTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:org_memberships) do
      add :readable_types, {:array, :text}, null: false, default: []
    end

    alter table(:users) do
      add :readable_types, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:users) do
      remove :readable_types
    end

    alter table(:org_memberships) do
      remove :readable_types
    end
  end
end
