defmodule KilnCMS.Repo.Migrations.AddMenus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:menu_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "menu_items_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :label, :text, null: false
      add :position, :bigint, null: false, default: 0
      add :link_type, :text, null: false, default: "content"
      add :target_type, :text
      add :target_id, :uuid
      add :url, :text
      add :open_in_new_tab, :boolean, null: false, default: false
      add :visible, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :menu_id, :uuid, null: false
      add :parent_id, :uuid
    end

    create index(:menu_items, [:parent_id], name: "menu_items_parent_lookup_index")

    create index(:menu_items, [:menu_id], name: "menu_items_menu_lookup_index")

    create table(:menus, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:menu_items) do
      modify :menu_id,
             references(:menus,
               column: :id,
               name: "menu_items_menu_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :parent_id,
             references(:menu_items,
               column: :id,
               name: "menu_items_parent_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:menus) do
      add :org_id,
          references(:organizations,
            column: :id,
            name: "menus_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :key, :text, null: false
      add :name, :text, null: false
      add :locale, :text, null: false, default: "en"
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:menus, [:org_id, :key, :locale], name: "menus_unique_key_index")
  end

  def down do
    drop constraint(:menus, "menus_org_id_fkey")

    drop_if_exists unique_index(:menus, [:org_id, :key, :locale], name: "menus_unique_key_index")

    alter table(:menus) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :locale
      remove :name
      remove :key
      remove :org_id
    end

    drop constraint(:menu_items, "menu_items_menu_id_fkey")

    drop constraint(:menu_items, "menu_items_parent_id_fkey")

    alter table(:menu_items) do
      modify :parent_id, :uuid
      modify :menu_id, :uuid
    end

    drop table(:menus)

    drop constraint(:menu_items, "menu_items_org_id_fkey")

    drop_if_exists index(:menu_items, [:menu_id], name: "menu_items_menu_lookup_index")

    drop_if_exists index(:menu_items, [:parent_id], name: "menu_items_parent_lookup_index")

    drop table(:menu_items)
  end
end
