defmodule KilnCMS.Repo.Migrations.AddApiKeyAccessScope do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:api_keys) do
      add :access, :text, null: false, default: "read"
    end
  end

  def down do
    alter table(:api_keys) do
      remove :access
    end
  end
end
