defmodule KilnCMS.Repo.Migrations.TypeDefinitionSchemaOrgType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:type_definitions) do
      add :schema_org_type, :text, null: false, default: "Article"
    end
  end

  def down do
    alter table(:type_definitions) do
      remove :schema_org_type
    end
  end
end
