defmodule KilnCMS.Repo.Migrations.AddMediaDurationSeconds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:media_items) do
      add :duration_seconds, :float
    end
  end

  def down do
    alter table(:media_items) do
      remove :duration_seconds
    end
  end
end
