defmodule KilnCMS.Repo.Migrations.DropVersionSourceFks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:posts_versions, "posts_versions_version_source_id_fkey")

    alter table(:posts_versions) do
      modify :version_source_id, :uuid
    end

    create index(:posts_versions, [:version_source_id])

    drop constraint(:pages_versions, "pages_versions_version_source_id_fkey")

    alter table(:pages_versions) do
      modify :version_source_id, :uuid
    end

    create index(:pages_versions, [:version_source_id])
  end

  def down do
    drop_if_exists index(:pages_versions, [:version_source_id])

    alter table(:pages_versions) do
      modify :version_source_id,
             references(:pages,
               column: :id,
               name: "pages_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:posts_versions, [:version_source_id])

    alter table(:posts_versions) do
      modify :version_source_id,
             references(:posts,
               column: :id,
               name: "posts_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
