defmodule KilnCMS.Repo.Migrations.AddVersionSourceIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:pages_versions, [:org_id, :version_source_id, :version_inserted_at, :id])

    create index(:entries_versions, [:org_id, :version_source_id, :version_inserted_at, :id])

    create index(:posts_versions, [:org_id, :version_source_id, :version_inserted_at, :id])
  end

  def down do
    drop_if_exists index(:posts_versions, [:org_id, :version_source_id, :version_inserted_at, :id])

    drop_if_exists index(:entries_versions, [
                     :org_id,
                     :version_source_id,
                     :version_inserted_at,
                     :id
                   ])

    drop_if_exists index(:pages_versions, [:org_id, :version_source_id, :version_inserted_at, :id])
  end
end
