defmodule KilnCMS.Repo.Migrations.AddMediaItemQuarantine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:media_items) do
      add :quarantined, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:media_items) do
      remove :quarantined
    end
  end
end
