defmodule KilnCMS.Repo.Migrations.AddContentViewGoal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:content_experiments) do
      add :goal_content_type, :text
    end
  end

  def down do
    alter table(:content_experiments) do
      remove :goal_content_type
    end
  end
end
