defmodule KilnCMS.Repo.Migrations.ChainFoldOrder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:history_anchors) do
      add :folded_version_ids, {:array, :uuid}, null: false, default: []
      add :payload_version, :bigint
    end
  end

  def down do
    alter table(:history_anchors) do
      remove :payload_version
      remove :folded_version_ids
    end
  end
end
