defmodule KilnCMS.Repo.Migrations.AddSiteBranding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_branding, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_branding_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :site_name, :text
      add :logo_url, :text
      add :favicon_url, :text
      add :social_image_url, :text
      add :brand_color, :text
      add :show_attribution, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:site_branding, [:org_id], name: "site_branding_one_per_org_index")
  end

  def down do
    drop constraint(:site_branding, "site_branding_org_id_fkey")

    drop_if_exists unique_index(:site_branding, [:org_id],
                     name: "site_branding_one_per_org_index"
                   )

    drop table(:site_branding)
  end
end
