defmodule KilnCMS.Repo.Migrations.AddContentViewDayBuckets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:content_view_days, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "content_view_days_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :content_type, :text, null: false
      add :content_id, :uuid, null: false
      add :day, :date, null: false, default: fragment("CURRENT_DATE")
      add :views, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:content_view_days, [:org_id, :day], name: "content_view_days_trend_index")

    create unique_index(:content_view_days, [:org_id, :content_type, :content_id, :day],
             name: "content_view_days_unique_content_day_index"
           )
  end

  def down do
    drop constraint(:content_view_days, "content_view_days_org_id_fkey")

    drop_if_exists unique_index(:content_view_days, [:org_id, :content_type, :content_id, :day],
                     name: "content_view_days_unique_content_day_index"
                   )

    drop_if_exists index(:content_view_days, [:org_id, :day],
                     name: "content_view_days_trend_index"
                   )

    drop table(:content_view_days)
  end
end
