defmodule KilnCMS.Repo.Migrations.AddWebhookDeliveryLedger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:webhook_endpoints) do
      add :consecutive_failures, :bigint, null: false, default: 0
      add :auto_disabled_at, :utc_datetime_usec
    end

    create table(:webhook_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event, :text, null: false
      add :payload, :map, null: false, default: %{}
      add :status, :text, null: false, default: "pending"
      add :attempts, :bigint, null: false, default: 0
      add :last_status, :bigint
      add :last_error, :text
      add :delivered_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :endpoint_id,
          references(:webhook_endpoints,
            column: :id,
            name: "webhook_deliveries_endpoint_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:webhook_deliveries, "webhook_deliveries_endpoint_id_fkey")

    drop table(:webhook_deliveries)

    alter table(:webhook_endpoints) do
      remove :auto_disabled_at
      remove :consecutive_failures
    end
  end
end
