defmodule KilnCMS.Repo.Migrations.AddPublishedVersionId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :published_version_id, :uuid
    end

    alter table(:pages) do
      add :published_version_id, :uuid
    end
  end

  def down do
    alter table(:pages) do
      remove :published_version_id
    end

    alter table(:posts) do
      remove :published_version_id
    end
  end
end
