defmodule KilnCMS.Repo.Migrations.AddFormAutoresponder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forms) do
      add :autoresponder_enabled, :boolean, null: false, default: false
      add :autoresponder_subject, :text
      add :autoresponder_body, :text
    end
  end

  def down do
    alter table(:forms) do
      remove :autoresponder_body
      remove :autoresponder_subject
      remove :autoresponder_enabled
    end
  end
end
