defmodule KilnCMS.Repo.Migrations.AddBillingSettingsAndTiers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:billing_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :singleton, :bigint, null: false, default: 0
      add :provider, :text, null: false, default: "stripe"
      add :secret_key_provider, :text, null: false, default: "database"
      add :secret_key_provider_config, :map, null: false, default: %{}
      add :secret_key_encrypted, :binary
      add :webhook_secret_provider, :text, null: false, default: "database"
      add :webhook_secret_provider_config, :map, null: false, default: %{}
      add :webhook_secret_encrypted, :binary
      add :provider_account_id, :text
      add :livemode, :boolean
      add :last_verified_at, :utc_datetime_usec
      add :verification_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:billing_settings, [:singleton],
             name: "billing_settings_singleton_row_index"
           )

    create table(:billing_membership_tiers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "billing_membership_tiers_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :audience, :text, null: false
      add :provider_price_id, :text, null: false
      add :price_config, :map, null: false, default: %{}
      add :active, :boolean, null: false, default: true
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:billing_membership_tiers, [:org_id, :provider_price_id],
             name: "billing_membership_tiers_unique_price_per_org_index"
           )

    create unique_index(:billing_membership_tiers, [:org_id, :slug],
             name: "billing_membership_tiers_unique_slug_per_org_index"
           )

    create constraint(:billing_membership_tiers, :billing_membership_tiers_audience_must_be_gated,
             check: """
               audience IN ('member')
             """
           )

    create constraint(:billing_settings, :billing_secret_key_provider_must_be_known,
             check: """
               secret_key_provider IN ('database', 'env', 'file')
             """
           )

    create constraint(:billing_settings, :billing_webhook_secret_provider_must_be_known,
             check: """
               webhook_secret_provider IN ('database', 'env', 'file')
             """
           )

    create constraint(:billing_settings, :billing_provider_must_be_known,
             check: """
               provider IN ('stripe')
             """
           )
  end

  def down do
    drop_if_exists constraint(:billing_settings, :billing_provider_must_be_known)

    drop_if_exists constraint(:billing_settings, :billing_webhook_secret_provider_must_be_known)

    drop_if_exists constraint(:billing_settings, :billing_secret_key_provider_must_be_known)

    drop_if_exists constraint(
                     :billing_membership_tiers,
                     :billing_membership_tiers_audience_must_be_gated
                   )

    drop constraint(:billing_membership_tiers, "billing_membership_tiers_org_id_fkey")

    drop_if_exists unique_index(:billing_membership_tiers, [:org_id, :slug],
                     name: "billing_membership_tiers_unique_slug_per_org_index"
                   )

    drop_if_exists unique_index(:billing_membership_tiers, [:org_id, :provider_price_id],
                     name: "billing_membership_tiers_unique_price_per_org_index"
                   )

    drop table(:billing_membership_tiers)

    drop_if_exists unique_index(:billing_settings, [:singleton],
                     name: "billing_settings_singleton_row_index"
                   )

    drop table(:billing_settings)
  end
end
