defmodule KilnCMS.Repo.Migrations.EditorsCanPublish do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:site_editorial_settings) do
      add :editors_can_publish, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:site_editorial_settings) do
      remove :editors_can_publish
    end
  end
end
