defmodule KilnCMS.Repo.Migrations.AddBlockTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:tasks, [:org_id, :content_type, :content_id],
                     name: "tasks_content_lookup_index"
                   )

    alter table(:tasks) do
      add :block_id, :uuid
    end

    create index(:tasks, [:org_id, :content_type, :content_id, :block_id],
             name: "tasks_content_lookup_index"
           )
  end

  def down do
    drop_if_exists index(:tasks, [:org_id, :content_type, :content_id, :block_id],
                     name: "tasks_content_lookup_index"
                   )

    alter table(:tasks) do
      remove :block_id
    end

    create index(:tasks, [:org_id, :content_type, :content_id],
             name: "tasks_content_lookup_index"
           )
  end
end
