defmodule KilnCMS.Repo.Migrations.AddThrottleCounters do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:throttle_counters, primary_key: false) do
      add :bucket, :text, null: false, primary_key: true
      add :key_hash, :binary, null: false, primary_key: true
      add :window_index, :bigint, null: false, primary_key: true
      add :count, :bigint, null: false
      add :expires_at, :utc_datetime_usec, null: false
    end

    create index(:throttle_counters, [:expires_at], name: "throttle_counters_expires_at_index")
  end

  def down do
    drop_if_exists index(:throttle_counters, [:expires_at],
                     name: "throttle_counters_expires_at_index"
                   )

    drop table(:throttle_counters)
  end
end
