defmodule KilnCMS.Repo.Migrations.AddRedirects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:redirects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "redirects_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :path, :text, null: false
      add :locale, :text, null: false, default: "en"
      add :target_type, :text, null: false
      add :target_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:redirects, [:org_id, :path, :locale],
             name: "redirects_unique_path_index"
           )
  end

  def down do
    drop constraint(:redirects, "redirects_org_id_fkey")

    drop_if_exists unique_index(:redirects, [:org_id, :path, :locale],
                     name: "redirects_unique_path_index"
                   )

    drop table(:redirects)
  end
end
