defmodule KilnCMS.Repo.Migrations.AddSiteLocaleSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_locale_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_locale_settings_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :fallbacks, :map
    end

    create unique_index(:site_locale_settings, [:org_id],
             name: "site_locale_settings_one_per_org_index"
           )
  end

  def down do
    drop constraint(:site_locale_settings, "site_locale_settings_org_id_fkey")

    drop_if_exists unique_index(:site_locale_settings, [:org_id],
                     name: "site_locale_settings_one_per_org_index"
                   )

    drop table(:site_locale_settings)
  end
end
