defmodule KilnCMS.Repo.Migrations.SiteVapidKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_vapid_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_vapid_keys_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:site_vapid_keys, [:org_id], name: "site_vapid_keys_one_per_org_index")

    alter table(:site_vapid_keys) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :public_key, :text
      add :private_key_encrypted, :binary
      add :subject, :text
    end

    alter table(:push_subscriptions) do
      add :vapid_public_key, :text
    end

    create index(:push_subscriptions, [:org_id, :vapid_public_key])
  end

  def down do
    drop_if_exists index(:push_subscriptions, [:org_id, :vapid_public_key])

    alter table(:push_subscriptions) do
      remove :vapid_public_key
    end

    drop constraint(:site_vapid_keys, "site_vapid_keys_org_id_fkey")

    alter table(:site_vapid_keys) do
      remove :subject
      remove :private_key_encrypted
      remove :public_key
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:site_vapid_keys, [:org_id],
                     name: "site_vapid_keys_one_per_org_index"
                   )

    drop table(:site_vapid_keys)
  end
end
