defmodule KilnCMS.Repo.Migrations.VersionSignatures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pages_versions) do
      add :chain_signature, :text
      add :chain_key_id, :text
    end

    alter table(:entries_versions) do
      add :chain_signature, :text
      add :chain_key_id, :text
    end

    alter table(:posts_versions) do
      add :chain_signature, :text
      add :chain_key_id, :text
    end
  end

  def down do
    alter table(:posts_versions) do
      remove :chain_key_id
      remove :chain_signature
    end

    alter table(:entries_versions) do
      remove :chain_key_id
      remove :chain_signature
    end

    alter table(:pages_versions) do
      remove :chain_key_id
      remove :chain_signature
    end
  end
end
