defmodule KilnCMS.Repo.Migrations.FormEmbedOrigins do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:forms) do
      add :embed_origins, {:array, :text}
    end
  end

  def down do
    alter table(:forms) do
      remove :embed_origins
    end
  end
end
