defmodule KilnCMS.Repo.Migrations.PerOrgCodeInjection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_code_injection, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_code_injection_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :head_html, :text
      add :footer_html, :text
      add :enabled, :boolean, null: false, default: true
      add :script_src, {:array, :text}, default: []
      add :connect_src, {:array, :text}, default: []
      add :img_src, {:array, :text}, default: []
      add :script_hashes, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:site_code_injection, [:org_id],
             name: "site_code_injection_one_per_org_index"
           )

    create table(:site_code_injection_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :org_id, :uuid, null: false

      add :version_source_id,
          references(:site_code_injection,
            column: :id,
            name: "site_code_injection_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "site_code_injection_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(
           :site_code_injection_versions,
           "site_code_injection_versions_version_source_id_fkey"
         )

    drop constraint(:site_code_injection_versions, "site_code_injection_versions_user_id_fkey")

    drop table(:site_code_injection_versions)

    drop constraint(:site_code_injection, "site_code_injection_org_id_fkey")

    drop_if_exists unique_index(:site_code_injection, [:org_id],
                     name: "site_code_injection_one_per_org_index"
                   )

    drop table(:site_code_injection)
  end
end
