defmodule KilnCMS.Repo.Migrations.AddReferenceEdges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reference_edges, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :from_type, :text, null: false
      add :from_id, :uuid, null: false
      add :to_type, :text, null: false
      add :to_id, :uuid, null: false
    end

    create unique_index(:reference_edges, [:from_type, :from_id, :to_type, :to_id],
             name: "reference_edges_edge_index"
           )
  end

  def down do
    drop_if_exists unique_index(:reference_edges, [:from_type, :from_id, :to_type, :to_id],
                     name: "reference_edges_edge_index"
                   )

    drop table(:reference_edges)
  end
end
