defmodule KilnCMS.Repo.Migrations.SiteSsoProvidersAndDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_sso_domains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_sso_domains_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :domain, :text, null: false
    end

    create unique_index(:site_sso_domains, [:org_id, :domain],
             name: "site_sso_domains_unique_domain_index"
           )

    alter table(:site_sso_domains) do
      add :verification_token, :text, null: false
      add :verified_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:site_sso_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_sso_providers_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:site_sso_providers, [:org_id],
             name: "site_sso_providers_one_per_org_index"
           )

    alter table(:site_sso_providers) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enabled, :boolean, null: false, default: true
      add :issuer, :text
      add :client_id, :text
      add :client_secret_encrypted, :binary
      add :label, :text
    end
  end

  def down do
    drop constraint(:site_sso_providers, "site_sso_providers_org_id_fkey")

    alter table(:site_sso_providers) do
      remove :label
      remove :client_secret_encrypted
      remove :client_id
      remove :issuer
      remove :enabled
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:site_sso_providers, [:org_id],
                     name: "site_sso_providers_one_per_org_index"
                   )

    drop table(:site_sso_providers)

    drop constraint(:site_sso_domains, "site_sso_domains_org_id_fkey")

    alter table(:site_sso_domains) do
      remove :updated_at
      remove :inserted_at
      remove :verified_at
      remove :verification_token
    end

    drop_if_exists unique_index(:site_sso_domains, [:org_id, :domain],
                     name: "site_sso_domains_unique_domain_index"
                   )

    drop table(:site_sso_domains)
  end
end
