defmodule KilnCMS.Repo.Migrations.AddAnchorSequence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:history_anchors) do
      add :sequence, :bigint
    end

    create index(:history_anchors, [:org_id, :resource_type, :source_id, :sequence])

    alter table(:history_anchors) do
      modify :prev_anchor_id,
             references(:history_anchors,
               column: :id,
               name: "history_anchors_prev_anchor_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :restrict
             )
    end

    create index(:history_anchors, [:org_id, :prev_anchor_id])
  end

  def down do
    drop_if_exists index(:history_anchors, [:org_id, :prev_anchor_id])

    drop constraint(:history_anchors, "history_anchors_prev_anchor_id_fkey")

    alter table(:history_anchors) do
      modify :prev_anchor_id, :uuid
    end

    drop_if_exists index(:history_anchors, [:org_id, :resource_type, :source_id, :sequence])

    alter table(:history_anchors) do
      remove :sequence
    end
  end
end
