defmodule KilnCMS.Repo.Migrations.AddSiteSecurityTxt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_security_txt, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_security_txt_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:site_security_txt, [:org_id],
             name: "site_security_txt_one_per_org_index"
           )

    alter table(:site_security_txt) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :contacts, {:array, :text}
      add :expires_on, :date
      add :policy_url, :text
      add :preferred_languages, {:array, :text}
      add :encryption_url, :text
      add :acknowledgments_url, :text
    end
  end

  def down do
    drop constraint(:site_security_txt, "site_security_txt_org_id_fkey")

    alter table(:site_security_txt) do
      remove :acknowledgments_url
      remove :encryption_url
      remove :preferred_languages
      remove :policy_url
      remove :expires_on
      remove :contacts
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:site_security_txt, [:org_id],
                     name: "site_security_txt_one_per_org_index"
                   )

    drop table(:site_security_txt)
  end
end
