defmodule KilnCMS.Repo.Migrations.ConsoleContentListIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:pages, [:org_id, :updated_at, :id],
             name: "pages_console_updated_index",
             concurrently: true
           )

    create index(:pages, [:org_id, :title, :id],
             name: "pages_console_title_index",
             concurrently: true
           )

    create index(:pages, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
             name: "pages_console_published_index",
             concurrently: true
           )

    create index(:posts, [:org_id, :updated_at, :id],
             name: "posts_console_updated_index",
             concurrently: true
           )

    create index(:posts, [:org_id, :title, :id],
             name: "posts_console_title_index",
             concurrently: true
           )

    create index(:posts, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
             name: "posts_console_published_index",
             concurrently: true
           )

    create index(:entries, [:org_id, :updated_at, :id],
             name: "entries_console_updated_index",
             concurrently: true
           )

    create index(:entries, [:org_id, :title, :id],
             name: "entries_console_title_index",
             concurrently: true
           )

    create index(:entries, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
             name: "entries_console_published_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists index(:entries, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
                     name: "entries_console_published_index"
                   )

    drop_if_exists index(:entries, [:org_id, :title, :id], name: "entries_console_title_index")

    drop_if_exists index(:entries, [:org_id, :updated_at, :id],
                     name: "entries_console_updated_index"
                   )

    drop_if_exists index(:posts, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
                     name: "posts_console_published_index"
                   )

    drop_if_exists index(:posts, [:org_id, :title, :id], name: "posts_console_title_index")

    drop_if_exists index(:posts, [:org_id, :updated_at, :id], name: "posts_console_updated_index")

    drop_if_exists index(:pages, [:org_id, "published_at DESC NULLS LAST", "id DESC"],
                     name: "pages_console_published_index"
                   )

    drop_if_exists index(:pages, [:org_id, :title, :id], name: "pages_console_title_index")

    drop_if_exists index(:pages, [:org_id, :updated_at, :id], name: "pages_console_updated_index")
  end
end
