defmodule KilnCMS.Repo.Migrations.ContentTreeParentAndPosition do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pages) do
      add :position, :bigint, null: false, default: 0

      add :parent_id,
          references(:pages,
            column: :id,
            name: "pages_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:posts) do
      add :position, :bigint, null: false, default: 0

      add :parent_id,
          references(:posts,
            column: :id,
            name: "posts_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:entries) do
      add :position, :bigint, null: false, default: 0

      add :parent_id,
          references(:entries,
            column: :id,
            name: "entries_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:entries, "entries_parent_id_fkey")

    alter table(:entries) do
      remove :parent_id
      remove :position
    end

    drop constraint(:posts, "posts_parent_id_fkey")

    alter table(:posts) do
      remove :parent_id
      remove :position
    end

    drop constraint(:pages, "pages_parent_id_fkey")

    alter table(:pages) do
      remove :parent_id
      remove :position
    end
  end
end
