defmodule KilnCMS.Repo.Migrations.AddTotpPendingSecret do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :totp_pending_secret, :binary
    end
  end

  def down do
    alter table(:users) do
      remove :totp_pending_secret
    end
  end
end
