defmodule KilnCMS.Repo.Migrations.AddSiteStorage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:media_items) do
      add :storage_profile_id, :uuid
    end

    create table(:site_storages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "site_storages_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:site_storages, [:org_id], name: "site_storages_one_per_org_index")

    alter table(:site_storages) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :enabled, :boolean, null: false, default: true
      add :profile_id, :uuid
    end

    create table(:storage_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :org_id,
          references(:organizations,
            column: :id,
            name: "storage_profiles_org_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :endpoint, :text
      add :region, :text, null: false, default: "us-east-1"
      add :bucket, :text, null: false
      add :private_bucket, :text
      add :public_base_url, :text, null: false
      add :access_key_id, :text, null: false
      add :secret_access_key_encrypted, :binary, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:storage_profiles, "storage_profiles_org_id_fkey")

    drop table(:storage_profiles)

    drop constraint(:site_storages, "site_storages_org_id_fkey")

    alter table(:site_storages) do
      remove :profile_id
      remove :enabled
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:site_storages, [:org_id],
                     name: "site_storages_one_per_org_index"
                   )

    drop table(:site_storages)

    alter table(:media_items) do
      remove :storage_profile_id
    end
  end
end
