defmodule KilnCMS.SchemaExport.TypeScriptParityTest do
  @moduledoc """
  The emitter-parity tripwire for the JS client's `kiln-types` generator.

  `clients/js/src/generator.ts` is a port of `KilnCMS.SchemaExport.TypeScript`
  that promises "the same declarations for the same document". Both suites
  assert the same checked-in golden from the same fixture — this side from
  ExUnit, the JS side from vitest (`clients/js/test/parity.test.ts`) — so a
  change to either emitter that the other doesn't mirror turns exactly one
  side red instead of drifting silently.

  Only the first header line differs by design (each emitter names its own
  entry point), so the comparison drops it.

  To regenerate after a deliberate, mirrored change to both emitters:

      cd clients/js && npm run build && node dist/bin/kiln-types.js \\
        --from test/fixtures/schema.json --out test/fixtures/golden.d.ts
  """
  use ExUnit.Case, async: true

  @fixtures Path.expand("../../../clients/js/test/fixtures", __DIR__)

  test "emit/1 reproduces the shared golden below the header line" do
    document = @fixtures |> Path.join("schema.json") |> File.read!() |> Jason.decode!()
    golden = @fixtures |> Path.join("golden.d.ts") |> File.read!()

    emitted = KilnCMS.SchemaExport.TypeScript.emit(document)

    assert drop_header_line(emitted) == drop_header_line(golden)
  end

  # Line 1 is `// Generated by \`<entry point>\`. Do not edit.` — the one
  # deliberate difference between the two emitters' outputs.
  defp drop_header_line(text) do
    text |> String.split("\n") |> tl() |> Enum.join("\n")
  end
end
