defmodule KilnCMSWeb.ContentController do
  @moduledoc """
  Public content delivery — renders **published** content as HTML for anonymous
  site visitors (the human-facing counterpart to the headless GraphQL/JSON:API
  endpoints).

  URL structure matches the sitemap: pages at `/<slug>`, posts at
  `/blog/<slug>` (plus a `/blog` index), and every other content type at
  `/<plural>/<slug>` (resolved generically through `KilnCMS.CMS.ContentTypes`).
  Only published content is reachable; the read actions filter on
  `state == :published`, so an unpublished slug 404s rather than leaking a draft.
  """
  use KilnCMSWeb, :controller

  alias KilnCMS.Analytics
  alias KilnCMS.Cache
  alias KilnCMS.CMS
  alias KilnCMS.CMS.ContentTypes
  alias KilnCMS.I18n
  alias KilnCMSWeb.StructuredData

  def show_page(conn, %{"slug" => slug}) do
    locale = locale(conn)
    ct = ContentTypes.get(:page)
    org_id = current_org_id(conn)

    fetch =
      &CMS.get_published_page_by_slug!(slug, &1,
        not_found_error?: false,
        authorize?: false,
        tenant: org_id,
        load: [:author]
      )

    case Cache.fetch_published(org_id, "page", slug, locale, fn ->
           payload(fetch, locale, ct, org_id)
         end) do
      nil ->
        not_found(conn)

      payload ->
        track_view("page", payload.record.id)
        render_content(conn, :show_page, payload, ct)
    end
  end

  def show_post(conn, %{"slug" => slug}) do
    locale = locale(conn)
    ct = ContentTypes.get(:post)
    org_id = current_org_id(conn)

    fetch =
      &CMS.get_published_post_by_slug!(slug, &1,
        not_found_error?: false,
        authorize?: false,
        tenant: org_id,
        load: [:author]
      )

    case Cache.fetch_published(org_id, "post", slug, locale, fn ->
           payload(fetch, locale, ct, org_id)
         end) do
      nil ->
        not_found(conn)

      payload ->
        track_view("post", payload.record.id)
        render_content(conn, :show_post, payload, ct)
    end
  end

  # Generic delivery for any other content type at `/<plural>/<slug>` (e.g. a
  # type generated by `mix kiln.gen.content`). `type` is the URL segment.
  def show_content(conn, %{"type" => type, "slug" => slug}) do
    locale = locale(conn)
    org_id = current_org_id(conn)

    with ct when not is_nil(ct) <- ContentTypes.get_by_path(type),
         fetch =
           &ContentTypes.get_published_by_slug(ct.type, slug, &1,
             not_found_error?: false,
             authorize?: false,
             tenant: org_id,
             load: [:author]
           ),
         payload when not is_nil(payload) <-
           Cache.fetch_published(org_id, to_string(ct.type), slug, locale, fn ->
             payload(fetch, locale, ct, org_id)
           end) do
      track_view(to_string(ct.type), payload.record.id)
      render_content(conn, :show, payload, ct)
    else
      _ -> not_found(conn)
    end
  end

  # Posts shown per page on the public blog index. Bounds per-request memory/DB
  # load — the `:published` read is paginated and capped at its `max_page_size`.
  @blog_page_size 20

  def blog_index(conn, params) do
    locale = locale(conn)
    page = page_param(params)

    # No `count: true` — only `more?` is used, and a count adds a full
    # COUNT(*) over published posts to every request.
    %Ash.Page.Offset{results: posts, more?: more?} =
      CMS.list_published_posts!(
        authorize?: false,
        tenant: current_org_id(conn),
        query: [filter: [locale: locale]],
        page: [limit: @blog_page_size, offset: page * @blog_page_size]
      )

    conn
    |> put_resp_header("cache-control", "public, max-age=60, stale-while-revalidate=300")
    |> put_resp_header("vary", "Accept-Language")
    |> assign(:locale, locale)
    |> assign(:page_title, gettext("Blog"))
    |> assign(:meta_description, gettext("Latest posts."))
    |> assign(:locale_links, blog_locale_links(locale))
    |> assign(:json_ld, json_ld_script(StructuredData.blog(posts)))
    |> render(:blog_index, posts: posts, page: page, has_prev?: page > 0, has_next?: more?)
  end

  # Public on-site search (#149). Anonymous, so the read policy returns published
  # content only; locale-scoped to the active locale. Posts, pages and dynamic
  # entries (media isn't part of the public site).
  def search(conn, params) do
    locale = locale(conn)
    query = params["q"] |> to_string() |> String.trim()

    # Optional category facet (`?category=<slug>`): filters both hybrid legs.
    # An unknown slug matches nothing rather than silently unfiltering.
    category = category_filter(params["category"])

    filters =
      case category do
        %{id: id} -> %{category_id: id}
        :unknown -> %{category_id: Ecto.UUID.generate()}
        nil -> %{}
      end

    results =
      if query == "" do
        %{posts: [], pages: [], entries: []}
      else
        # NOTE (epic #336): `KilnCMS.Search.global` is NOT yet tenant-scoped — the
        # search subsystem doesn't accept a tenant, so this (and the headless
        # `SearchApiController`) span all orgs. Safe under the single-org rollout
        # guard; the tenant facet lands with the search PR (PR 3) before real
        # multi-org is enabled. Do not lift the guard until then.
        r =
          KilnCMS.Search.global(query,
            authorize?: true,
            locale: locale,
            limit: 20,
            filters: filters
          )

        %{posts: r.posts, pages: r.pages, entries: entry_results(r.entries)}
      end

    # Category counts over the unfiltered match set — the sidebar shows the
    # full distribution to switch between (tag facets are API-only for now).
    facets =
      if query == "",
        do: [],
        else: KilnCMS.Search.facets(query, authorize?: true, locale: locale).categories

    # A sparse result set gets a trigram "did you mean" (published titles
    # only) — the fuzzy hybrid leg may have rescued a typo's hits, and the
    # suggestion then names the corrected term. Exact-match queries never
    # suggest (`Search.suggest/2` skips exact word matches).
    total = length(results.posts) + length(results.pages) + length(results.entries)

    suggestion =
      if query != "" and total < 3,
        do: KilnCMS.Search.suggest(query, authorize?: true, locale: locale)

    conn
    # Don't cache personalized/empty query result pages on shared caches.
    |> put_resp_header("cache-control", "private, no-cache")
    |> assign(:locale, locale)
    |> assign(:page_title, gettext("Search"))
    |> assign(:locale_links, search_locale_links(locale, query))
    |> render(:search,
      query: query,
      results: results,
      suggestion: suggestion,
      facets: facets,
      active_category: if(is_struct(category), do: category)
    )
  end

  # Resolve a `?category=` slug world-readably: nil when absent, the category
  # when known, `:unknown` otherwise.
  defp category_filter(slug) when is_binary(slug) and slug != "" do
    case KilnCMS.CMS.get_category_by_slug(slug, authorize?: true) do
      {:ok, category} -> category
      _not_found -> :unknown
    end
  end

  defp category_filter(_absent), do: nil

  # Dynamic-entry hits as plain view maps: resolve each result's type through
  # the registry for its URL segment and label, dropping hits whose type no
  # longer resolves (archived between indexing and render).
  defp entry_results(entries) do
    Enum.flat_map(entries, fn entry ->
      case ContentTypes.get_dynamic(entry.type_name) do
        %{path_segment: segment, label: label} ->
          [
            %{
              title: entry.title,
              excerpt: Map.get(entry, :excerpt),
              path: "/#{segment}/#{entry.slug}",
              type_label: label
            }
          ]

        _archived ->
          []
      end
    end)
  end

  # Language-switcher links to the search page (preserving the query) per locale.
  defp search_locale_links(current, query) do
    suffix = if query == "", do: "", else: "?q=#{URI.encode_www_form(query)}"

    for locale <- I18n.locales() do
      prefix = if locale == I18n.default_locale(), do: "", else: "/#{locale}"

      %{
        locale: locale,
        href: "#{base_url()}#{prefix}/search#{suffix}",
        current: locale == current
      }
    end
  end

  # Highest zero-based page index we'll serve. Clamps `?page=N` so a huge value
  # can't force Postgres into a massive OFFSET + full COUNT scan (cheap DoS).
  @max_page 500

  # Zero-based page index from `?page=N` (1-based in the URL for humans).
  # Anything missing or invalid is page 0; anything beyond @max_page is clamped.
  defp page_param(%{"page" => raw}) do
    case Integer.parse(to_string(raw)) do
      {n, _} when n > 1 -> min(n - 1, @max_page)
      _ -> 0
    end
  end

  defp page_param(_params), do: 0

  # Language-switcher links to the blog index in each supported locale.
  defp blog_locale_links(current) do
    for locale <- I18n.locales() do
      prefix = if locale == I18n.default_locale(), do: "", else: "/#{locale}"
      %{locale: locale, href: "#{base_url()}#{prefix}/blog", current: locale == current}
    end
  end

  # The requested locale (set by `KilnCMSWeb.Plugs.SetLocale`).
  defp locale(conn), do: conn.assigns[:locale] || I18n.default_locale()

  defp current_org_id(conn), do: KilnCMSWeb.Tenant.current_org_id(conn)

  # The cached delivery payload: the published record, its media-enriched blocks,
  # and its published locale variants. All enrichment (the per-image media lookup
  # + `srcset`, and the `translations` lookup for hreflang/locale links) happens
  # here at cache-miss time, so a cache *hit* carries resolved media URLs and
  # translations and issues no further DB queries. Returns `nil` (not cached)
  # when nothing is found.
  defp payload(fetch, locale, ct, org_id) do
    case localized(fetch, locale) do
      nil ->
        nil

      record ->
        %{
          record: record,
          blocks: blocks(record, org_id),
          translations: translations(ct, record.slug)
        }
    end
  end

  # Fetch the record in `locale`, falling back to the default locale's version.
  defp localized(fetch, locale) do
    default = I18n.default_locale()

    case fetch.(locale) do
      nil when locale != default -> fetch.(default)
      record -> record
    end
  end

  # Assign SEO metadata (read by the root layout) and the pre-enriched blocks,
  # then render. `payload` is a `%{record, blocks}` map (see `payload/2`) and
  # `ct` its `ContentTypes` entry.
  defp render_content(
         conn,
         template,
         %{record: record, blocks: blocks, translations: translations},
         ct
       ) do
    conn = put_delivery_cache_headers(conn, record)
    start = System.monotonic_time()

    result =
      if delivery_fresh?(conn, record) do
        send_resp(conn, :not_modified, "")
      else
        render_content_body(conn, template, record, blocks, translations, ct)
      end

    # Delivery-render duration telemetry (#206), tagged by content type and
    # whether the response was a 304.
    :telemetry.execute(
      [:kiln_cms, :delivery, :render],
      %{duration: System.monotonic_time() - start, count: 1},
      %{type: to_string(ct.type), status: result.status}
    )

    result
  end

  defp render_content_body(conn, template, record, blocks, translations, ct) do
    conn
    |> assign(:locale, record.locale)
    |> assign(:page_title, record.seo_title || record.title)
    |> assign(:meta_description, record.seo_description)
    |> assign(:canonical_url, record.canonical_url || locale_url(ct, record.slug, record.locale))
    |> assign(:og_image, record.seo_image)
    |> assign(:og_type, "article")
    |> assign(:hreflang, hreflang_alternates(ct, translations))
    |> assign(:locale_links, locale_links(ct, translations, record.locale))
    |> assign(:json_ld, json_ld_script(StructuredData.document(record, ct)))
    |> render(template, record: record, blocks: blocks)
  end

  # Published locale variants of `slug`. Best-effort: a content type without a
  # translations interface simply yields none.
  defp translations(ct, slug) do
    ContentTypes.list_translations(ct.type, slug, authorize?: false)
  rescue
    _ -> []
  end

  # `rel="alternate" hreflang` entries for every published locale variant, plus
  # an `x-default` pointing at the default locale.
  defp hreflang_alternates(ct, translations) do
    default = I18n.default_locale()

    alternates =
      for t <- translations, do: %{hreflang: t.locale, href: locale_url(ct, t.slug, t.locale)}

    case Enum.find(translations, &(&1.locale == default)) do
      nil -> alternates
      t -> alternates ++ [%{hreflang: "x-default", href: locale_url(ct, t.slug, default)}]
    end
  end

  # Language-switcher links to each published translation of this record.
  defp locale_links(ct, translations, current) do
    translations
    |> Enum.map(
      &%{
        locale: &1.locale,
        href: locale_url(ct, &1.slug, &1.locale),
        current: &1.locale == current
      }
    )
    |> Enum.sort_by(& &1.locale)
  end

  # Absolute public URL for `slug` in `locale` (non-default locales are prefixed).
  defp locale_url(ct, slug, locale) do
    prefix = if locale == I18n.default_locale(), do: "", else: "/#{locale}"
    "#{base_url()}#{prefix}#{ContentTypes.public_prefix(ct)}/#{slug}"
  end

  defp base_url, do: Application.get_env(:kiln_cms, :public_base_url, "http://localhost:4000")

  # Pre-render the JSON-LD as a safe <script> tag. HEEx doesn't interpolate
  # inside a literal <script> element, so the layout injects this with `{...}`.
  # `escape: :html_safe` escapes `<`/`>`/`&`, so the JSON can't break out of the
  # tag.
  defp json_ld_script(data) do
    json = Jason.encode!(data, escape: :html_safe)
    Phoenix.HTML.raw(~s(<script type="application/ld+json">#{json}</script>))
  end

  defp blocks(record, org_id) do
    # Blocks are stored as the typed union (Kiln v2); convert back to legacy block
    # structs so the existing media-enriching renderer (`BlockComponents`) is
    # unchanged. A `columns` block (#335) nests child blocks, so the tree is built
    # recursively and flattened once for the media/form preloads — a nested image
    # or form is loaded in the same batched query as a top-level one.
    tree = block_tree(record.blocks)
    flat = flatten_block_tree(tree)

    media = load_block_media(flat, org_id)
    forms = load_block_forms(flat)
    Enum.map(tree, &enrich_block(&1, media, forms))
  end

  # Typed union → legacy `KilnCMS.CMS.Block` structs, recursing into `columns`
  # children so each nested block is itself a legacy struct the renderer handles.
  defp block_tree(blocks) do
    blocks
    |> KilnCMS.CMS.TypedBlocks.to_typed()
    |> KilnCMS.CMS.TypedBlocks.to_legacy()
    |> Enum.map(&struct(KilnCMS.CMS.Block, &1))
    |> Enum.map(&nest_columns/1)
  end

  defp nest_columns(%KilnCMS.CMS.Block{type: :columns, data: data} = block) do
    cols =
      for col <- data["columns"] || [] do
        %{"blocks" => col |> Map.get("blocks", []) |> block_tree()}
      end

    %{block | data: Map.put(data, "columns", cols)}
  end

  defp nest_columns(block), do: block

  # Depth-first block list, so the media/form preloads see nested blocks too.
  defp flatten_block_tree(blocks) do
    Enum.flat_map(blocks, fn
      %KilnCMS.CMS.Block{type: :columns, data: %{"columns" => cols}} = block ->
        [block | Enum.flat_map(cols, &flatten_block_tree(&1["blocks"] || []))]

      block ->
        [block]
    end)
  end

  # Batch-load the active forms referenced by form blocks (fields included),
  # keyed by slug — inactive/unknown slugs simply don't enrich.
  defp load_block_forms(blocks) do
    slugs =
      for b <- blocks,
          to_string(b.type) == "form",
          slug = b.data["form_slug"] || b.content,
          is_binary(slug) and slug != "",
          uniq: true,
          do: slug

    Map.new(slugs, &{&1, KilnCMS.Forms.get_active(&1)})
  end

  # Batch-load the media items referenced by image blocks (so we render one
  # query, not one per image).
  defp load_block_media(blocks, org_id) do
    ids =
      for b <- blocks,
          to_string(b.type) == "image",
          id = b.data["media_id"],
          is_binary(id),
          uniq: true,
          do: id

    case ids do
      [] ->
        %{}

      ids ->
        # Tenant-scoped so a page can only enrich media from its own site (#336);
        # `authorize?: false` is the delivery bypass, so the tenant is the guard.
        CMS.list_media_items!(
          authorize?: false,
          tenant: org_id,
          query: [filter: [id: [in: ids]]]
        )
        |> Map.new(&{&1.id, &1})
    end
  end

  defp enrich_block(block, media, forms) do
    base = %{type: to_string(block.type), content: block.content}

    cond do
      block.type == :columns ->
        enrich_columns(base, block, media, forms)

      block.type == :image && match?(%{}, media[block.data["media_id"]]) ->
        item = media[block.data["media_id"]]

        Map.merge(base, %{
          srcset: srcset(item),
          alt: item.alt,
          width: item.width,
          height: item.height,
          focal: focal_style(item)
        })

      block.type == :form ->
        # nil form (inactive/unknown slug) → the component renders nothing.
        Map.put(base, :form, forms[block.data["form_slug"] || block.content])

      true ->
        base
    end
  end

  # Recursively enrich a columns block's nested children (each column's blocks go
  # through the same `enrich_block/3` a top-level block does), and attach the grid
  # style so `BlockComponents` lays the container out identically to firing.
  defp enrich_columns(base, block, media, forms) do
    cols =
      for col <- block.data["columns"] || [] do
        %{blocks: Enum.map(col["blocks"] || [], &enrich_block(&1, media, forms))}
      end

    Map.merge(base, %{
      columns: cols,
      style:
        KilnCMS.Blocks.Columns.grid_style(block.data["layout"], block.data["gap"], length(cols))
    })
  end

  # `object-position` from the media item's focal point, so any theme (or the
  # inline styles below) cropping via `object-fit` keeps the subject in frame.
  # Omitted at the default center — no styling noise for untouched media.
  defp focal_style(%{focal_x: x, focal_y: y})
       when is_number(x) and is_number(y) and (x != 0.5 or y != 0.5) do
    "object-position: #{round(x * 100)}% #{round(y * 100)}%"
  end

  defp focal_style(_item), do: nil

  # Builds an `srcset` value from a media item's variants plus the original,
  # e.g. "/uploads/thumb 400w, /uploads/medium 1024w, /uploads/orig 1600w".
  # Cropped variants (different aspect ratio) are excluded — they're for
  # consumers that ask for that framing by label, not for responsive scaling.
  defp srcset(item) do
    cropped = KilnCMS.ImageProcessor.cropped_labels()

    variant_parts =
      for {label, %{"url" => url, "width" => w}} <- item.variants || %{},
          label not in cropped,
          safe = KilnCMS.HTMLSanitizer.safe_image_src(url),
          is_binary(safe),
          do: "#{safe} #{w}w"

    original =
      case item.width && KilnCMS.HTMLSanitizer.safe_image_src(item.url) do
        url when is_binary(url) -> ["#{url} #{item.width}w"]
        _ -> []
      end

    case variant_parts ++ original do
      [] -> nil
      parts -> Enum.join(parts, ", ")
    end
  end

  # Record a privacy-first page view. Best-effort and **off the request path**:
  # the upsert runs in a supervised, unlinked task so a slow DB pool (or a crawler
  # spike) can't queue page delivery. The supervisor's `max_children` bounds
  # concurrent tasks, so a spike drops views (start_child → {:error, :max_children})
  # rather than exhausting the pool. Failures are swallowed.
  #
  # `:async_analytics` is on in prod/dev but off under test, where the detached
  # task would run outside the ExUnit SQL sandbox connection (leaking a connection
  # past the owning test and racing assertions). Running it inline keeps the
  # upsert on the request's sandbox-owned connection.
  defp track_view(type, id) do
    if Application.get_env(:kiln_cms, :async_analytics, true) do
      Task.Supervisor.start_child(KilnCMS.TaskSupervisor, fn -> record_view(type, id) end)
    else
      record_view(type, id)
    end

    :ok
  end

  defp record_view(type, id) do
    Analytics.record_view(type, id, authorize?: false)
  rescue
    _ -> :ok
  end

  defp not_found(conn) do
    conn
    # A 404 may be an unpublished/draft slug — never let a CDN or browser cache
    # it (it would mask the page once published).
    |> put_resp_header("cache-control", "no-store")
    |> put_status(:not_found)
    |> put_view(KilnCMSWeb.ErrorHTML)
    |> render(:"404")
  end

  # CDN/browser cache headers for published HTML: a short shared max-age with a
  # longer stale-while-revalidate window (the in-BEAM cache is single-node, so
  # these let a CDN absorb origin load), plus a content ETag for conditional GETs
  # and `Vary: Accept-Language` since delivery is locale-sensitive.
  defp put_delivery_cache_headers(conn, record) do
    conn
    |> put_resp_header("cache-control", "public, max-age=60, stale-while-revalidate=300")
    |> put_resp_header("vary", "Accept-Language")
    |> put_resp_header("etag", etag(record))
  end

  defp etag(record) do
    raw = "#{record.id}:#{record.updated_at}:#{record.published_version_id}"
    digest = :sha256 |> :crypto.hash(raw) |> Base.encode16(case: :lower) |> binary_part(0, 16)
    ~s("#{digest}")
  end

  defp delivery_fresh?(conn, record) do
    match?([_ | _], get_req_header(conn, "if-none-match")) and
      etag(record) in get_req_header(conn, "if-none-match")
  end
end
