defmodule KilnCMSWeb.ContentController do
  @moduledoc """
  Public content delivery — renders **published** content as HTML for anonymous
  site visitors (the human-facing counterpart to the headless GraphQL/JSON:API
  endpoints).

  URL structure matches the sitemap: pages at `/<slug>`, posts at
  `/blog/<slug>` (plus a `/blog` index), and every other content type at
  `/<plural>/<slug>` (resolved generically through `KilnCMS.CMS.ContentTypes`).
  Only published content is reachable; the read actions filter on
  `state == :published`, so an unpublished slug 404s rather than leaking a draft.
  """
  use KilnCMSWeb, :controller

  alias KilnCMS.Analytics
  alias KilnCMS.CMS
  alias KilnCMS.CMS.ContentTypes
  alias KilnCMSWeb.StructuredData

  def show_page(conn, %{"slug" => slug}) do
    case CMS.get_published_page_by_slug!(slug, not_found_error?: false, authorize?: false) do
      nil ->
        not_found(conn)

      page ->
        track_view("page", page.id)
        render_content(conn, :show_page, page, ContentTypes.get(:page))
    end
  end

  def show_post(conn, %{"slug" => slug}) do
    case CMS.get_published_post_by_slug!(slug, not_found_error?: false, authorize?: false) do
      nil ->
        not_found(conn)

      post ->
        track_view("post", post.id)
        render_content(conn, :show_post, post, ContentTypes.get(:post))
    end
  end

  # Generic delivery for any other content type at `/<plural>/<slug>` (e.g. a
  # type generated by `mix kiln.gen.content`). `type` is the URL segment.
  def show_content(conn, %{"type" => type, "slug" => slug}) do
    with ct when not is_nil(ct) <- ContentTypes.get_by_path(type),
         record when not is_nil(record) <-
           ContentTypes.get_published_by_slug(ct.type, slug,
             not_found_error?: false,
             authorize?: false
           ) do
      track_view(to_string(ct.type), record.id)
      render_content(conn, :show, record, ct)
    else
      _ -> not_found(conn)
    end
  end

  def blog_index(conn, _params) do
    posts = CMS.list_published_posts!(authorize?: false)

    conn
    |> assign(:page_title, "Blog")
    |> assign(:meta_description, "Latest posts.")
    |> render(:blog_index, posts: posts)
  end

  # Assign SEO metadata (read by the root layout) and the normalized blocks,
  # then render. `record` is a published content struct and `ct` its
  # `ContentTypes` entry.
  defp render_content(conn, template, record, ct) do
    conn
    |> assign(:page_title, record.seo_title || record.title)
    |> assign(:meta_description, record.seo_description)
    |> assign(:canonical_url, record.canonical_url)
    |> assign(:og_image, record.seo_image)
    |> assign(:og_type, "article")
    |> assign(:json_ld, json_ld_script(record, ct))
    |> render(template, record: record, blocks: blocks(record))
  end

  # Pre-render the JSON-LD as a safe <script> tag. HEEx doesn't interpolate
  # inside a literal <script> element, so the layout injects this with `{...}`.
  # `escape: :html_safe` escapes `<`/`>`/`&`, so the JSON can't break out of the
  # tag.
  defp json_ld_script(record, ct) do
    json = Jason.encode!(StructuredData.build(record, ct), escape: :html_safe)
    Phoenix.HTML.raw(~s(<script type="application/ld+json">#{json}</script>))
  end

  defp blocks(record) do
    raw = List.wrap(record.blocks)
    media = load_block_media(raw)
    Enum.map(raw, &enrich_block(&1, media))
  end

  # Batch-load the media items referenced by image blocks (so we render one
  # query, not one per image).
  defp load_block_media(blocks) do
    ids =
      for b <- blocks,
          to_string(b.type) == "image",
          id = b.data["media_id"],
          is_binary(id),
          uniq: true,
          do: id

    case ids do
      [] ->
        %{}

      ids ->
        CMS.list_media_items!(authorize?: false, query: [filter: [id: [in: ids]]])
        |> Map.new(&{&1.id, &1})
    end
  end

  defp enrich_block(block, media) do
    base = %{type: to_string(block.type), content: block.content}

    case media[block.data["media_id"]] do
      %{} = item when block.type == :image ->
        Map.merge(base, %{
          srcset: srcset(item),
          alt: item.alt,
          width: item.width,
          height: item.height
        })

      _ ->
        base
    end
  end

  # Builds an `srcset` value from a media item's variants plus the original,
  # e.g. "/uploads/thumb 400w, /uploads/medium 1024w, /uploads/orig 1600w".
  defp srcset(item) do
    variant_parts =
      for {_label, %{"url" => url, "width" => w}} <- item.variants || %{}, do: "#{url} #{w}w"

    original = if item.width, do: ["#{item.url} #{item.width}w"], else: []

    case variant_parts ++ original do
      [] -> nil
      parts -> Enum.join(parts, ", ")
    end
  end

  # Record a privacy-first page view. Best-effort: analytics must never break or
  # slow content delivery, so failures are swallowed.
  defp track_view(type, id) do
    Analytics.record_view(type, id, authorize?: false)
  rescue
    _ -> :ok
  end

  defp not_found(conn) do
    conn
    |> put_status(:not_found)
    |> put_view(KilnCMSWeb.ErrorHTML)
    |> render(:"404")
  end
end
