defmodule KilnCMSWeb.ContentController do
  @moduledoc """
  Public content delivery — renders **published** content as HTML for anonymous
  site visitors (the human-facing counterpart to the headless GraphQL/JSON:API
  endpoints).

  URL structure matches the sitemap: pages at `/<slug>`, posts at
  `/blog/<slug>` (plus a `/blog` index), and every other content type at
  `/<plural>/<slug>` (resolved generically through `KilnCMS.CMS.ContentTypes`).
  Only published content is reachable; the read actions filter on
  `state == :published`, so an unpublished slug 404s rather than leaking a draft.

  ## Why every read here runs `authorize?: false`

  A site visitor has no actor. `KilnCMS.CMS.Content`'s read policies do admit
  an anonymous reader — `published` + `audience == :public` (+ no passphrase)
  passes with no actor at all — but the rest of a visitor's read scope lives
  on the *request*: the audience memberships and passphrase unlocks that
  `reader_audiences/1` and `ContentLock` pull off the session cannot be
  expressed through an actor the policies could evaluate. So delivery goes
  through dedicated read actions (`:public_by_slug`, `:teaser_by_slug`,
  `:locked_by_slug`, `:published_translations`, `:published`) whose *own
  filters* carry the published-state, audience and unlock grants, and it is
  always tenant-scoped (`tenant: current_org_id/1`) so one site can never
  serve another's records. That is why the bypass — not "the policies need an
  actor": a new anonymous read of plain public content should prefer the
  policies. Each bypass below points back here; the per-site comment says
  which action's filter is the guard.
  """
  use KilnCMSWeb, :controller

  alias KilnCMS.Cache
  alias KilnCMS.CMS
  alias KilnCMS.CMS.ContentPassword
  alias KilnCMS.CMS.ContentTypes
  alias KilnCMS.Experiments
  alias KilnCMS.Feeds
  alias KilnCMS.I18n
  alias KilnCMS.Seo.Patterns
  alias KilnCMSWeb.ContentLock
  alias KilnCMSWeb.EventIndex
  alias KilnCMSWeb.Params
  alias KilnCMSWeb.StructuredData
  alias KilnCMSWeb.ViewTracking

  def show_page(conn, %{"slug" => slug} = params) do
    locale = locale(conn)
    ct = ContentTypes.get(:page)
    org_id = current_org_id(conn)
    audiences = reader_audiences(conn)
    unlocks = ContentLock.grants(conn)

    # Delivery bypass (moduledoc): `:public_by_slug` filters published + audience
    # + unlock itself; `tenant:` scopes it to this site.
    fetch =
      &CMS.get_published_page_by_slug!(slug, &1, %{audiences: audiences, unlocks: unlocks},
        not_found_error?: false,
        authorize?: false,
        tenant: org_id,
        load: [:author, :category]
      )

    case fetch_payload(org_id, "page", slug, locale, audiences, unlocks, fn ->
           payload(fetch, locale, ct, org_id, audiences)
         end) do
      nil ->
        # A single segment that names no page may still name an event-shaped
        # type's index (#766) — `/gigs` for a type served at `/gigs/<slug>`.
        #
        # LAST in the funnel, after the page, the alias, the redirect table, the
        # lock page and the teaser, and only ahead of the 404 itself. That order
        # is the whole safety argument: this can only turn a 404 into an index,
        # never take a URL away from something that already answers there — a
        # `path_alias` of `/gigs` on some record, say, which nothing forbids.
        # It also leaves an operator a way to replace the generated listing with
        # a hand-built page at the same address.
        follow_redirect_or_404(conn, "/" <> slug, ct, fn -> event_index(conn, slug, params) end)

      payload ->
        serve(conn, :show_page, "page", payload, ct, audiences)
    end
  end

  def show_post(conn, %{"slug" => slug}) do
    locale = locale(conn)
    ct = ContentTypes.get(:post)
    org_id = current_org_id(conn)
    audiences = reader_audiences(conn)
    unlocks = ContentLock.grants(conn)

    # Delivery bypass (moduledoc): `:public_by_slug` filters published + audience
    # + unlock itself; `tenant:` scopes it to this site.
    fetch =
      &CMS.get_published_post_by_slug!(slug, &1, %{audiences: audiences, unlocks: unlocks},
        not_found_error?: false,
        authorize?: false,
        tenant: org_id,
        load: [:author, :category]
      )

    case fetch_payload(org_id, "post", slug, locale, audiences, unlocks, fn ->
           payload(fetch, locale, ct, org_id, audiences)
         end) do
      nil ->
        follow_redirect_or_404(conn, "/blog/" <> slug, ct)

      payload ->
        serve(conn, :show_post, "post", payload, ct, audiences)
    end
  end

  # Generic delivery for any other content type at `/<plural>/<slug>` (e.g. a
  # type generated by `mix kiln.gen.content`). `type` is the URL segment.
  def show_content(conn, %{"type" => type, "slug" => slug}) do
    locale = locale(conn)
    org_id = current_org_id(conn)
    audiences = reader_audiences(conn)
    unlocks = ContentLock.grants(conn)
    ct = ContentTypes.get_by_path(type, org_id)

    # Delivery bypass (moduledoc): the type's `:public_by_slug` filters
    # published + audience + unlock itself; `tenant:` scopes it to this site.
    with ct when not is_nil(ct) <- ct,
         fetch =
           &ContentTypes.get_published_by_slug(ct.type, slug, &1,
             audiences: audiences,
             unlocks: unlocks,
             not_found_error?: false,
             authorize?: false,
             tenant: org_id,
             load: [:author, :category]
           ),
         payload when not is_nil(payload) <-
           fetch_payload(org_id, to_string(ct.type), slug, locale, audiences, unlocks, fn ->
             payload(fetch, locale, ct, org_id, audiences)
           end) do
      serve(conn, :show, to_string(ct.type), payload, ct, audiences)
    else
      _ -> follow_redirect_or_404(conn, "/" <> type <> "/" <> slug, ct)
    end
  end

  # Serve a payload at its canonical URL: a record with a `path_alias` (#485)
  # 301s its flat `/<prefix>/<slug>` URL to the alias; everything else renders.
  defp serve(conn, view, type_string, payload, ct, audiences) do
    alias_path = Map.get(payload.record, :path_alias)

    if is_binary(alias_path) and conn.request_path != alias_path do
      moved_permanently(conn, alias_path)
    else
      ViewTracking.track(conn, :html, type_string, payload.record.id, payload.record.org_id)

      # A/B experiments (#499). Stateless by default on this surface: a variant
      # is drawn per request and nothing is stored about the visitor. `nil` — no
      # experiment, or the feature is off — is the overwhelmingly common case
      # and costs one cached lookup.
      #
      # With `sticky: true` (#984, opt-in) the visitor keeps their arm across
      # reloads via a bucket cookie, and the conn comes back carrying it. The
      # page is `private, no-store` either way — stickiness changes which arm a
      # visitor sees, not that the body differs between visitors.
      {variant, conn} = Experiments.Delivery.assign_sticky(type_string, payload.record, conn)

      # And this page may itself be some *other* experiment's `:content_view`
      # goal — the conversion happens on a later page than the assignment, which
      # is the whole reason that goal needs the sticky cookie (#984). A no-op
      # unless the visitor carries an exposure this page converts.
      conn = Experiments.Delivery.record_content_view(type_string, payload.record, conn)

      render_content(conn, view, payload, ct, audiences, variant)
    end
  end

  # Deep paths (3+ segments) carry no content routes — they exist only as
  # redirect sources, e.g. a legacy `/2019/05/old-post` imported from a
  # previous site (#457).
  def fallback(conn, %{"path" => segments}) do
    follow_redirect_or_404(conn, "/" <> Enum.join(segments, "/"))
  end

  # Every URL miss funnels here: first a multi-segment path alias (#485) —
  # the canonical home of aliased content — then the redirect table (a
  # published rename leaves a `CMS.Redirect` behind; resolution is live, no
  # chains); anything unresolvable 404s as before.
  # `ct` (when known) lets the flat-slug miss try a paywall teaser for that type.
  #
  # Order matters: alias, then the redirect table, then the lock page, then the
  # teaser, then 404. Both interstitials come after the redirect table, so a
  # document that also has a legacy redirect still redirects — neither may shadow
  # an editor's explicit routing decision.
  #
  # Lock before teaser (#496), because the lock read already requires the reader
  # to satisfy the audience axis. A locked members-only post therefore shows the
  # paywall to a visitor who isn't a member and the passphrase form to one who
  # is, which is the AND the two axes are supposed to compose to. The other order
  # would have shown every member a paywall they had already paid past.
  #
  # `fallback` is one last thing to try before the 404 — the event index (#766)
  # is the only caller that passes one. It sits at the very end deliberately:
  # a generated listing must never outrank a record that actually resolves at
  # the same URL, and putting it here means the ordering is stated once, in the
  # funnel, rather than inferred from which branch called what.
  defp follow_redirect_or_404(conn, path, ct \\ nil, fallback \\ fn -> nil end) do
    serve_alias(conn, path) ||
      case KilnCMS.CMS.Redirects.resolve(path, locale(conn), current_org_id(conn)) do
        nil ->
          serve_lock(conn, path, ct) || serve_teaser(conn, path, ct) || fallback.() ||
            not_found(conn, path)

        %{to: to} ->
          moved_permanently(conn, to)
      end
  end

  @doc """
  Verify a passphrase submitted from a lock page (#496) and, on success, record
  the grant and send the visitor back to the document.

  A wrong passphrase re-renders the same lock page with an error and a `401`. A
  path that names nothing locked 404s through the normal funnel.

  Those two answers differ, and that is fine *here*: a plain GET of the same URL
  already distinguishes the cases (a lock page for a locked document, the
  document itself for an open one), so this endpoint reveals nothing a visitor
  could not already see. The headless unlock endpoint is the one that has to
  answer identically, because there the GET is the thing being protected.
  """
  def unlock(conn, params) do
    path = local_path(Params.string(params, "path", ""))
    type = Params.string(params, "type", "")
    locale = Params.string(params, "locale", I18n.default_locale())
    ct = path && ContentTypes.get(type)

    with ct when not is_nil(ct) <- ct,
         {ct, record} when not is_nil(record) <- locked_at(conn, path, ct, locale) do
      verify_passphrase(conn, record, ct, path, params["passphrase"])
    else
      # No such type, an off-site path, or nothing locked there. Deliberately a
      # 404 through the normal funnel rather than a distinct error: an unlock
      # endpoint that answered differently for "not locked" than for "wrong
      # passphrase" would enumerate which documents are locked.
      _ -> not_found(conn, path || "/")
    end
  end

  defp verify_passphrase(conn, record, ct, path, passphrase) do
    if ContentPassword.verify(record.access_password_hash, passphrase) do
      conn
      |> ContentLock.grant(record.password_fingerprint)
      # 303, not 302: this is a POST whose result is a page to GET. It also means
      # the browser drops the form body, so a refresh on the document doesn't
      # re-submit the passphrase.
      |> put_status(:see_other)
      |> redirect(to: I18n.localized_path(conn.assigns[:path_locale], path))
    else
      render_lock(conn, record, ct, path, :invalid)
    end
  end

  # A submitted return path is only ever used as a local path. `//host` and
  # `/\\host` are protocol-relative URLs that a browser resolves off-site, so
  # "starts with a slash" is not enough of a check on its own.
  defp local_path("/" <> rest = path) do
    if String.starts_with?(rest, "/") or String.starts_with?(rest, "\\"), do: nil, else: path
  end

  defp local_path(_), do: nil

  # Render the passphrase form for a LOCKED published document (#496).
  #
  # Same shape as the paywall below, and the same guarantee: the read never
  # selects the block tree, and the record is projected onto `KilnCMSWeb.Teaser`
  # — a struct with no `blocks` field — before anything reaches a template. A
  # lock page describes a document precisely in order not to serve it.
  defp serve_lock(_conn, _path, nil), do: nil

  defp serve_lock(conn, path, ct) do
    case locked_record(conn, path, ct, locale(conn)) do
      nil -> nil
      record -> render_lock(conn, record, ct, path)
    end
  end

  # The locked document a submitted `path` names — by `path_alias` first, then by
  # slug, which is the order delivery itself resolves in.
  #
  # The alias branch is not optional: an aliased document's canonical URL has no
  # relationship to its slug, so deriving one from the last path segment (which
  # is all the slug branch can do) resolves the wrong document or none at all.
  # Without it the lock page for an aliased document would render and then refuse
  # every passphrase, which reads as "the passphrase is wrong".
  defp locked_at(conn, path, ct, locale) do
    audiences = reader_audiences(conn)
    org_id = current_org_id(conn)

    lookup = fn loc -> KilnCMS.CMS.Slugs.find_locked_by_alias(path, loc, org_id, audiences) end

    case lookup.(locale) || lookup.(I18n.default_locale()) do
      {_ct, _record} = found -> found
      nil -> {ct, locked_record(conn, path, ct, locale)}
    end
  end

  # The locked document at `path`, or `nil`. Shared by the interstitial and by
  # `unlock/2`, so the form and the check can never disagree about which document
  # a request is talking about.
  defp locked_record(conn, path, ct, locale) do
    slug = path |> String.split("/") |> List.last()

    # Delivery bypass (moduledoc): `:locked_by_slug` returns only a published,
    # in-audience, passphrase-locked record — the interstitial's inputs, never
    # the body — and `tenant:` scopes it to this site.
    fetch = fn loc ->
      ContentTypes.get_locked_by_slug(ct.type, slug, loc,
        audiences: reader_audiences(conn),
        not_found_error?: false,
        authorize?: false,
        tenant: current_org_id(conn)
      )
    end

    localized(fetch, locale)
  rescue
    # A content type compiled against an older macro has no locked read — no
    # lock page rather than a 500, exactly as the teaser path degrades.
    _ -> nil
  end

  defp render_lock(conn, record, ct, path, error \\ nil) do
    org = KilnCMSWeb.Tenant.current_org(conn)
    base_url = KilnCMSWeb.Tenant.base_url(org)
    url = record.canonical_url || locale_url(ct, record.slug, record.locale, base_url)
    # `KilnCMSWeb.Teaser.from_record/3` owns the split now (#1102): the `summary`
    # a locked-out reader READS stays the author's own words, while the meta tags
    # carry the type's #805 default. `ct` and `org` are passed rather than
    # re-derived — the alias funnel reaches the same renderer with a record whose
    # pinned select omits nothing needed to look them up, but paying a registry
    # scan per paywall render on a route that exists to keep queries off it would
    # be the wrong trade.
    teaser = KilnCMSWeb.Teaser.from_record(record, url, type: ct, org: org)

    conn
    # Never shared-cached, and no ETag: the same URL returns the lock page to one
    # visitor and the document to another, so a cache keyed on URL alone would
    # eventually serve the document to someone who never typed the passphrase.
    |> put_private_delivery_headers()
    # A lock page is an interstitial, not the document. `noindex` keeps it from
    # being indexed in the document's place — the canonical below still points at
    # the document's own URL, so nothing about it moves in an index.
    |> put_resp_header("x-robots-tag", "noindex, nofollow")
    |> put_status(:unauthorized)
    |> assign(:locale, teaser.locale)
    |> assign(:page_title, teaser.seo_title || teaser.title)
    |> assign(:meta_description, teaser.seo_description)
    |> assign(:og_image, teaser.seo_image)
    |> assign(:og_type, "article")
    |> assign(:canonical_url, teaser.url)
    |> assign(:json_ld, json_ld_script(StructuredData.teaser(teaser, org)))
    |> put_view(KilnCMSWeb.ContentHTML)
    |> render(:lock,
      teaser: teaser,
      unlock_path: path,
      unlock_type: to_string(ct.type),
      unlock_locale: record.locale,
      error: error
    )
  end

  # Render a paywall for a GATED published document the reader can't read.
  #
  # Only reached once the entitled lookup, the alias lookup and the redirect table
  # have all missed — so a reader who IS entitled never sees a paywall, and a
  # genuinely unknown slug still 404s. The read requires a non-public audience and
  # never selects the block tree; the record is then projected onto
  # `KilnCMSWeb.Teaser`, which has no `blocks` field at all.
  defp serve_teaser(_conn, _path, nil), do: nil

  defp serve_teaser(conn, path, ct) do
    slug = path |> String.split("/") |> List.last()
    locale = locale(conn)
    org_id = current_org_id(conn)

    # Delivery bypass (moduledoc): `:teaser_by_slug` selects only the teaser
    # fields of a published, audience-gated record (the marketing surface for a
    # reader outside the audience); `tenant:` scopes it to this site.
    fetch = fn loc ->
      ContentTypes.get_teaser_by_slug(ct.type, slug, loc,
        not_found_error?: false,
        authorize?: false,
        tenant: org_id
      )
    end

    case localized(fetch, locale) do
      nil -> nil
      record -> render_teaser(conn, record, ct)
    end
  rescue
    # A content type without a teaser interface (an overlay compiled against an
    # older macro) simply has no paywall — 404 as before rather than 500.
    _ -> nil
  end

  defp render_teaser(conn, record, ct) do
    org = KilnCMSWeb.Tenant.current_org(conn)
    base_url = KilnCMSWeb.Tenant.base_url(org)
    url = record.canonical_url || locale_url(ct, record.slug, record.locale, base_url)
    # `KilnCMSWeb.Teaser.from_record/3` owns the split now (#1102): the `summary`
    # a locked-out reader READS stays the author's own words, while the meta tags
    # carry the type's #805 default. `ct` and `org` are passed rather than
    # re-derived — the alias funnel reaches the same renderer with a record whose
    # pinned select omits nothing needed to look them up, but paying a registry
    # scan per paywall render on a route that exists to keep queries off it would
    # be the wrong trade.
    teaser = KilnCMSWeb.Teaser.from_record(record, url, type: ct, org: org)

    conn
    # Same rule as a member render: this body depends on who asked, and the same
    # URL returns the full document for an entitled reader — a shared cache keyed
    # on URL alone would eventually cross the two.
    |> put_private_delivery_headers()
    |> assign(:locale, teaser.locale)
    |> assign(:page_title, teaser.seo_title || teaser.title)
    |> assign(:meta_description, teaser.seo_description)
    |> assign(:og_image, teaser.seo_image)
    |> assign(:og_type, "article")
    # Canonical is the DOCUMENT's own URL, never the join page: a paywall that
    # canonicalised elsewhere would have search engines index the wrong URL.
    |> assign(:canonical_url, teaser.url)
    |> assign(:json_ld, json_ld_script(StructuredData.teaser(teaser, org)))
    |> put_view(KilnCMSWeb.ContentHTML)
    |> render(:teaser, teaser: teaser)
  end

  # 301 to a canonical (unprefixed) delivery path, restoring the locale prefix
  # the visitor arrived through — `/fr/old-slug` lands on `/fr/new-slug` rather
  # than dumping a French reader on the default locale's URL. Only a *path*
  # prefix is re-applied (`Plugs.SetLocale` strips it into `:path_locale`),
  # never a session preference: the destination has to stay a pure function of
  # the requested URL, since a 301 without `Vary` is cacheable by shared caches.
  defp moved_permanently(conn, path) do
    conn
    |> put_status(:moved_permanently)
    |> redirect(to: I18n.localized_path(conn.assigns[:path_locale], path))
  end

  # Render the published record whose `path_alias` is this path, through the
  # same payload pipeline as the flat routes (uncached: alias hits are already
  # the miss path, and slug-keyed cache busting can't see alias keys).
  defp serve_alias(conn, path) do
    locale = locale(conn)
    org_id = current_org_id(conn)

    audiences = reader_audiences(conn)
    unlocks = ContentLock.grants(conn)

    lookup = fn loc ->
      KilnCMS.CMS.Slugs.find_published_by_alias(path, loc, org_id, audiences, unlocks)
    end

    case lookup.(locale) || lookup.(I18n.default_locale()) do
      nil ->
        lock_alias(conn, path, locale, org_id, audiences) ||
          teaser_alias(conn, path, locale, org_id)

      {ct, record} ->
        payload = %{
          record: record,
          blocks: blocks(record, org_id, audiences),
          translations: translations(ct, record.slug, org_id, audiences)
        }

        serve(conn, alias_view(ct), to_string(ct.type), payload, ct, audiences)
    end
  end

  # An aliased document behind a passphrase: the lock form at the alias, so its
  # canonical URL doesn't silently 404 (#496).
  #
  # This mirrors the slug funnel deliberately. An aliased document is served
  # through `serve_alias/2` INSTEAD of `:public_by_slug`, so without this pair —
  # the lock clause on the lookup above and this interstitial — a locked page
  # that happened to carry a `path_alias` would have been served in full at its
  # canonical URL with no passphrase at all.
  defp lock_alias(conn, path, locale, org_id, audiences) do
    lookup = fn loc ->
      KilnCMS.CMS.Slugs.find_locked_by_alias(path, loc, org_id, audiences)
    end

    case lookup.(locale) || lookup.(I18n.default_locale()) do
      nil -> nil
      {ct, record} -> render_lock(conn, record, ct, path)
    end
  end

  # An aliased document that is gated for this reader: paywall at the alias, so a
  # canonical URL doesn't silently 404.
  defp teaser_alias(conn, path, locale, org_id) do
    lookup = fn loc -> KilnCMS.CMS.Slugs.find_teaser_by_alias(path, loc, org_id) end

    case lookup.(locale) || lookup.(I18n.default_locale()) do
      nil -> nil
      {ct, record} -> render_teaser(conn, record, ct)
    end
  end

  defp alias_view(%{type: :page}), do: :show_page
  defp alias_view(%{type: :post}), do: :show_post
  defp alias_view(_ct), do: :show

  # Posts shown per page on the public blog index. Bounds per-request memory/DB
  # load — the `:published` read is paginated and capped at its `max_page_size`.
  @blog_page_size 20

  def blog_index(conn, params) do
    locale = locale(conn)
    page = page_param(params)
    org = KilnCMSWeb.Tenant.current_org(conn)

    # No `count: true` — only `more?` is used, and a count adds a full
    # COUNT(*) over published posts to every request.
    #
    # Delivery bypass (moduledoc): `:published` filters published + unlocked
    # itself (audience-gated posts are listed on purpose, badged as such);
    # `tenant:` scopes it to this site.
    %Ash.Page.Offset{results: posts, more?: more?} =
      CMS.list_published_posts!(
        authorize?: false,
        tenant: org.id,
        query: [filter: [locale: locale]],
        page: [limit: @blog_page_size, offset: page * @blog_page_size]
      )

    conn
    |> put_resp_header("cache-control", "public, max-age=60, stale-while-revalidate=300")
    |> put_resp_header("vary", "Accept-Language")
    |> assign(:locale, locale)
    |> assign(:page_title, gettext("Blog"))
    |> assign(:meta_description, gettext("Latest posts."))
    |> assign(:locale_links, blog_locale_links(locale, KilnCMSWeb.Tenant.base_url(org)))
    |> assign(:json_ld, json_ld_script(StructuredData.blog(posts, org)))
    |> render(:blog_index, posts: posts, page: page, has_prev?: page > 0, has_next?: more?)
  end

  # The occurrence-sorted index for an event-shaped type (#766) — "what's on,
  # soonest first" at `/<plural>`, the HTML twin of
  # `KilnCMSWeb.EventIndexController`. `nil` when the segment names no such type,
  # which is what lets `show_page/2` try this and fall through.
  #
  # Not a route of its own: `/:slug` already owns single-segment delivery, and a
  # second route competing for it would have decided the page-vs-index
  # precedence in the router, where it is invisible. Here it is one branch, in
  # order, with the reason next to it.
  #
  # No `Cache.fetch`: `from`/`until`/`page` are caller-chosen, so a cache key
  # built from them is unbounded — see `EventIndexController`'s moduledoc. The
  # response's own `max-age` is what absorbs repeats.
  defp event_index(conn, segment, params) do
    org = KilnCMSWeb.Tenant.current_org(conn)

    case EventIndex.type_for(org.id, segment) do
      nil -> nil
      descriptor -> render_event_index(conn, org, descriptor, params)
    end
  end

  defp render_event_index(conn, org, descriptor, params) do
    locale = locale(conn)
    {from, until} = EventIndex.window(params)
    page = EventIndex.page(params)

    %{entries: entries, more?: more?} =
      EventIndex.fetch(descriptor, org, from: from, until: until, locale: locale, page: page)

    base = EventIndex.index_path(descriptor)

    conn
    |> put_resp_header("cache-control", "public, max-age=60, stale-while-revalidate=300")
    |> put_resp_header("vary", "Accept-Language")
    |> assign(:locale, locale)
    |> assign(:page_title, descriptor.label)
    |> assign(:meta_description, gettext("What's on, soonest first."))
    |> assign(:locale_links, index_locale_links(locale, base, KilnCMSWeb.Tenant.base_url(org)))
    |> render(:event_index,
      entries: entries,
      label: descriptor.label,
      base_path: base,
      # The window rides into the pagination links, or page 2 of a filtered
      # listing quietly drops the filter and shows something else entirely.
      window: window_params(params),
      page: page,
      has_prev?: page > 0,
      has_next?: more?
    )
  end

  # Only the bounds the caller actually sent, so an unfiltered index's "next"
  # link stays the bare `?page=2` it was before.
  defp window_params(params) do
    for key <- ["from", "until"],
        value = Params.string(params, key, ""),
        String.trim(value) != "",
        do: {key, value}
  end

  # Language-switcher links to a type's index in each supported locale.
  defp index_locale_links(current, base, base_url) do
    for locale <- I18n.locales() do
      prefix = if locale == I18n.default_locale(), do: "", else: "/#{locale}"
      %{locale: locale, href: "#{base_url}#{prefix}#{base}", current: locale == current}
    end
  end

  # Public on-site search (#149). Anonymous, so the read policy returns published
  # content only; locale-scoped to the active locale. Posts, pages and dynamic
  # entries (media isn't part of the public site).
  def search(conn, params) do
    locale = locale(conn)
    query = params |> Params.string("q", "") |> String.trim()
    # Scope search to the request's org (#336); content sections are per-site.
    org = KilnCMSWeb.Tenant.current_org(conn)
    org_id = org.id

    # Optional category facet (`?category=<slug>`): filters both hybrid legs.
    # An unknown slug matches nothing rather than silently unfiltering. Resolved
    # within the request org so a foreign site's category can't be referenced.
    category = category_filter(params["category"], org_id)

    filters =
      case category do
        %{id: id} -> %{category_id: id}
        :unknown -> %{category_id: Ecto.UUID.generate()}
        nil -> %{}
      end

    results =
      if query == "" do
        %{posts: [], pages: [], entries: []}
      else
        r =
          KilnCMS.Search.global(query,
            authorize?: true,
            tenant: org_id,
            locale: locale,
            limit: 20,
            filters: filters,
            # Exactly the three read below — not `content_sections/0`, which
            # would also sweep any other registered type this page never shows
            # (#960).
            sections: [:posts, :pages, :entries]
          )

        %{posts: r.posts, pages: r.pages, entries: entry_results(r.entries)}
      end

    # Category counts over the unfiltered match set — the sidebar shows the
    # full distribution to switch between (tag facets are API-only for now).
    facets =
      if query == "",
        do: [],
        else:
          KilnCMS.Search.facets(query, authorize?: true, tenant: org_id, locale: locale).categories

    # A sparse result set gets a trigram "did you mean" (published titles
    # only) — the fuzzy hybrid leg may have rescued a typo's hits, and the
    # suggestion then names the corrected term. Exact-match queries never
    # suggest (`Search.suggest/2` skips exact word matches).
    total = length(results.posts) + length(results.pages) + length(results.entries)

    suggestion =
      if query != "" and total < 3,
        do: KilnCMS.Search.suggest(query, authorize?: true, tenant: org_id, locale: locale)

    conn
    # Don't cache personalized/empty query result pages on shared caches.
    |> put_resp_header("cache-control", "private, no-cache")
    |> assign(:locale, locale)
    |> assign(:page_title, gettext("Search"))
    |> assign(:locale_links, search_locale_links(locale, query, KilnCMSWeb.Tenant.base_url(org)))
    |> render(:search,
      query: query,
      results: results,
      suggestion: suggestion,
      facets: facets,
      active_category: if(is_struct(category), do: category)
    )
  end

  # Resolve a `?category=` slug world-readably: nil when absent, the category
  # when known, `:unknown` otherwise.
  defp category_filter(slug, org_id) when is_binary(slug) and slug != "" do
    case KilnCMS.CMS.get_category_by_slug(slug, authorize?: true, tenant: org_id) do
      {:ok, category} -> category
      _not_found -> :unknown
    end
  end

  defp category_filter(_absent, _org_id), do: nil

  # Dynamic-entry hits as plain view maps: resolve each result's type through
  # the registry for its URL segment and label, dropping hits whose type no
  # longer resolves (archived between indexing and render). The registry is
  # per-org (#336), so each hit resolves against its OWN org rather than
  # `get_dynamic/1`'s default-org fallback.
  defp entry_results(entries) do
    Enum.flat_map(entries, fn entry ->
      case ContentTypes.get_dynamic(entry.type_name, entry.org_id) do
        %{path_segment: segment, label: label} ->
          [
            %{
              title: entry.title,
              excerpt: Map.get(entry, :excerpt),
              path: "/#{segment}/#{entry.slug}",
              type_label: label
            }
          ]

        _archived ->
          []
      end
    end)
  end

  # Language-switcher links to the search page (preserving the query) per locale.
  defp search_locale_links(current, query, base_url) do
    suffix = if query == "", do: "", else: "?q=#{URI.encode_www_form(query)}"

    for locale <- I18n.locales() do
      prefix = if locale == I18n.default_locale(), do: "", else: "/#{locale}"

      %{
        locale: locale,
        href: "#{base_url}#{prefix}/search#{suffix}",
        current: locale == current
      }
    end
  end

  # Highest zero-based page index we'll serve. Clamps `?page=N` so a huge value
  # can't force Postgres into a massive OFFSET + full COUNT scan (cheap DoS).
  @max_page 500

  # Zero-based page index from `?page=N` (1-based in the URL for humans).
  # Anything missing or invalid is page 0; anything beyond @max_page is clamped.
  defp page_param(%{"page" => raw}) when is_binary(raw) do
    case Integer.parse(raw) do
      {n, _} when n > 1 -> min(n - 1, @max_page)
      _ -> 0
    end
  end

  defp page_param(_params), do: 0

  # Language-switcher links to the blog index in each supported locale.
  defp blog_locale_links(current, base_url) do
    for locale <- I18n.locales() do
      prefix = if locale == I18n.default_locale(), do: "", else: "/#{locale}"
      %{locale: locale, href: "#{base_url}#{prefix}/blog", current: locale == current}
    end
  end

  # The requested locale (set by `KilnCMSWeb.Plugs.SetLocale`).
  defp locale(conn), do: conn.assigns[:locale] || I18n.default_locale()

  defp current_org_id(conn), do: KilnCMSWeb.Tenant.current_org_id(conn)

  # The gated audiences this reader holds (#337 Phase 2). The `:browser` pipeline
  # already runs `:load_from_session` on the delivery scope, so the signed-in user
  # is here for free — it was simply unused before.
  #
  # Filtered through `Audiences.valid?/1`: an audience dropped from
  # `config :kiln_cms, :audiences` could still sit on a user row, and passing a
  # stale atom into the action's `one_of` constraint would raise — a 500 on a
  # public page. Sorted so the value is stable.
  defp reader_audiences(conn) do
    case conn.assigns[:current_user] do
      %{audiences: audiences} when is_list(audiences) ->
        audiences |> Enum.filter(&KilnCMS.CMS.Audiences.valid?/1) |> Enum.uniq() |> Enum.sort()

      _other ->
        []
    end
  end

  # The `payload` cache namespace is the ANONYMOUS, `:public`-only shape, and it
  # stays that way: a reader with audiences bypasses it entirely.
  #
  # Bypassing rather than adding an audience axis to the key is deliberate. The
  # key is a string, so correctness would depend on canonically serialising a
  # SET — `[:member, :pro]` and `[:pro, :member]` are the same entitlement but
  # different strings — and any normalisation slip, or one caller forgetting the
  # component, would serve gated blocks to anonymous readers. Bypassing makes
  # that class of bug unreachable: gated payloads are never in the cache at all.
  # The cost is one query per gated page view, for the smallest and least
  # latency-sensitive slice of traffic.
  # Unlock grants (#496) bypass it for the same reason and by the same rule: the
  # cached shape is what an anonymous visitor may read, and a request carrying a
  # grant may read more. Bypassing on "carries ANY grant" rather than "this
  # document is locked" is deliberate — the cache is consulted before the record
  # is known, so the narrower test isn't available at the decision point, and the
  # wrong guess would file a locked body under the anonymous key. The cost lands
  # on the handful of visitors who unlocked something, for the life of the grant.
  defp fetch_payload(org_id, type, slug, locale, [], [], fun),
    do: Cache.fetch_published_payload(org_id, type, slug, locale, fun)

  defp fetch_payload(_org_id, _type, _slug, _locale, _audiences, _unlocks, fun), do: fun.()

  # The cached delivery payload: the published record, its media-enriched blocks,
  # and its published locale variants. All enrichment (the per-image media lookup
  # + `srcset`, and the `translations` lookup for hreflang/locale links) happens
  # here at cache-miss time, so a cache *hit* carries resolved media URLs and
  # translations and issues no further DB queries. Returns `nil` (not cached)
  # when nothing is found.
  defp payload(fetch, locale, ct, org_id, audiences) do
    case localized(fetch, locale) do
      nil ->
        nil

      record ->
        %{
          record: record,
          blocks: blocks(record, org_id, audiences),
          translations: translations(ct, record.slug, org_id, audiences)
        }
    end
  end

  # Fetch the record in `locale`, falling back to the default locale's version.
  defp localized(fetch, locale) do
    default = I18n.default_locale()

    case fetch.(locale) do
      nil when locale != default -> fetch.(default)
      record -> record
    end
  end

  # Assign SEO metadata (read by the root layout) and the pre-enriched blocks,
  # then render. `payload` is a `%{record, blocks}` map (see `payload/2`) and
  # `ct` its `ContentTypes` entry.
  defp render_content(
         conn,
         template,
         %{record: record, blocks: blocks, translations: translations},
         ct,
         audiences,
         variant
       ) do
    # Resolve the type's SEO patterns (#805) here, ahead of the cache headers,
    # so `etag/1` below hashes the values a visitor will actually be served.
    # Applied later, a pattern change was invisible to every client holding a
    # validator: `updated_at` and `published_version_id` do not move when only
    # the TYPE is edited, so a revalidating browser or CDN got a 304 and kept
    # the old `<title>` indefinitely.
    record = Patterns.apply_to(record, ct, KilnCMSWeb.Tenant.current_org(conn))

    # A render that depended on WHO asked must never be shared-cached. The public
    # headers carry `public, max-age=60, stale-while-revalidate=300`, so a CDN in
    # front would happily serve one member's gated render to every anonymous
    # visitor. ETag/304 is skipped for the same reason — a conditional hit would
    # revalidate against a body that isn't the same for everyone.
    # A variant render is private for the same reason a gated one is, and it is
    # worth spelling out because the failure is silent: with `public, max-age=60`
    # a CDN caches ONE variant and serves it to every visitor for the next
    # minute. The experiment then reports a 50/50 split that never happened.
    # `etag/1` has no variant dimension either, so a conditional request would
    # 304 a visitor into whichever arm the cache is holding.
    # A document behind a passphrase (#496) is private for the plainest reason of
    # the four: with `public, max-age=60` the first unlocked visitor populates a
    # shared cache, and the next sixty seconds of anonymous visitors read it
    # without ever seeing the lock page. A shared secret is weak access control;
    # a shared secret plus a shared cache is none.
    # And a `:content_view` goal document (#984) is private because the
    # conversion is counted at the ORIGIN: a CDN holding this page would swallow
    # every conversion after the first and report a fraction of the truth. See
    # `KilnCMS.Experiments.Delivery.goal_page?/1`.
    private? =
      audiences != [] or variant != nil or
        not is_nil(Map.get(record, :access_password_hash)) or
        Experiments.Delivery.goal_page?(conn)

    conn =
      if private?,
        do: put_private_delivery_headers(conn),
        else: put_delivery_cache_headers(conn, record)

    start = System.monotonic_time()

    result =
      if not private? and delivery_fresh?(conn, record) do
        send_resp(conn, :not_modified, "")
      else
        render_content_body(conn, template, record, blocks, translations, ct, variant)
      end

    # Delivery-render duration telemetry (#206), tagged by content type and
    # whether the response was a 304.
    :telemetry.execute(
      [:kiln_cms, :delivery, :render],
      %{duration: System.monotonic_time() - start, count: 1},
      %{type: to_string(ct.type), status: result.status}
    )

    result
  end

  # `record` and `blocks` stay CANONICAL through every assign below — the page
  # title, the meta description, the canonical URL and the schema.org graph are
  # all built from them. Only the final `render/3` sees the variant. That is
  # invariant 3 (`KilnCMS.Experiments`): a variant changes what a human reads,
  # never what a machine indexes.
  defp render_content_body(conn, template, record, blocks, translations, ct, variant) do
    org = KilnCMSWeb.Tenant.current_org(conn)
    base_url = KilnCMSWeb.Tenant.base_url(org)

    conn
    |> assign(:locale, record.locale)
    |> assign(:page_title, record.seo_title || record.title)
    |> assign(:meta_description, record.seo_description)
    |> assign(:meta_keywords, record.seo_keywords)
    |> assign(
      :canonical_url,
      record.canonical_url || locale_url(ct, record.slug, record.locale, base_url)
    )
    |> assign(:og_image, record.seo_image)
    |> assign(:og_type, "article")
    |> assign(:hreflang, hreflang_alternates(ct, translations, base_url))
    |> assign(:locale_links, locale_links(ct, translations, record.locale, base_url))
    |> assign(
      :feeds,
      feed_alternates(ct, org, base_url, record.locale) ++
        calendar_alternates(ct, org, base_url)
    )
    |> assign(:json_ld, json_ld_script(StructuredData.document(record, ct, org)))
    |> assign(:experiment_variant, variant && variant.id)
    |> render(template,
      record: Experiments.Assignment.apply_to_record(record, variant),
      blocks: variant_blocks(record, blocks, variant, org.id, conn)
    )
  end

  # Applying the patch to the STORED blocks and re-running the pipeline, rather
  # than patching the enriched output: the patch addresses blocks by their `_id`
  # in typed-union terms, and everything downstream — fragment expansion, the
  # legacy conversion, the batched media and form preloads — then sees an
  # ordinary tree with no idea experiments exist.
  #
  # That re-run is not cheap (fragment expansion plus the batched media and form
  # loads), and an experimented page is `no-store`, so nothing absorbs it. So it
  # is skipped entirely unless the variant actually patches a block — a headline
  # or excerpt test, which is the common case, reuses the blocks already built
  # for the canonical payload and costs nothing extra.
  defp variant_blocks(_record, blocks, nil, _org_id, _conn), do: blocks

  defp variant_blocks(record, blocks, variant, org_id, conn) do
    if Experiments.Assignment.patches_blocks?(variant) do
      patched = Experiments.Assignment.apply_to_blocks(record.blocks, variant)

      %{record | blocks: patched}
      |> blocks(org_id, reader_audiences(conn))
    else
      blocks
    end
  end

  # Feed autodiscovery (#486): the site-wide feed plus this type's own, so a
  # reader landing on a post can subscribe to just that type. Built from
  # `FeedController.feed_path/2` rather than spelled out here, so the advertised
  # URL and the routed one cannot drift. A type that doesn't syndicate
  # advertises only the site-wide feed; if nothing syndicates, nothing is
  # advertised at all.
  # Advertised in the locale of the page being read (#720). A French reader on a
  # French article was being pointed at the default-locale feed, which carries no
  # article they can read — and the locale feeds exist precisely so that reader
  # has one. Same reason the paths come from `FeedController`: the advertised URL
  # and the routed one cannot drift.
  # Whether this type syndicates and whether *anything* does are the same
  # question about the same site's policy (#719), so both are answered from one
  # resolved policy rather than two lookups that could disagree. `syndicated?/2`
  # rather than a membership test against the list: it is the predicate that owns
  # the answer, and it compares names as strings — a descriptor's `type` is an
  # atom for a compiled type and a string for a dynamic one.
  defp feed_alternates(ct, org, base_url, locale) do
    policy = Feeds.policy(org.id)

    case Feeds.syndicated_types(org.id, policy) do
      [] ->
        []

      _any ->
        site = KilnCMS.Branding.for_org(org.id).site_name
        scope = %{locale: locale, taxonomy: nil}

        types =
          if Feeds.syndicated?(ct, policy),
            do: [{nil, site}, {ct, "#{site} — #{ct.label}"}],
            else: [{nil, site}]

        for {descriptor, title} <- types,
            {format, mime} <-
              [{:atom, "application/atom+xml"}, {:json, "application/feed+json"}] do
          %{
            type: mime,
            title: title,
            href: base_url <> KilnCMSWeb.FeedController.scoped_path(descriptor, scope, format)
          }
        end
    end
  end

  # Calendar autodiscovery (#480), riding the same `rel="alternate"` block. Built
  # from `CalendarController.calendar_path/1` for the reason the feeds are: the
  # advertised URL and the routed one cannot drift.
  #
  # Without this the `.ics` routes exist and nothing links to them, so a visitor
  # can only reach an event calendar by guessing the URL — the inert-surface
  # shape a round-one review caught on #489.
  defp calendar_alternates(ct, org, base_url) do
    case KilnCMS.Events.calendar_types(org.id) do
      [] ->
        []

      types ->
        site = KilnCMS.Branding.for_org(org.id).site_name
        scope = Enum.find(types, &(to_string(&1.type) == to_string(ct.type)))

        [{nil, site} | if(scope, do: [{scope, "#{site} — #{scope.label}"}], else: [])]
        |> Enum.map(fn {descriptor, title} ->
          %{
            type: "text/calendar",
            title: title,
            href: base_url <> KilnCMSWeb.CalendarController.calendar_path(descriptor)
          }
        end)
    end
  end

  # Published locale variants of `slug`, scoped to the request's site (#336) so
  # hreflang/locale links never point at another org's content. Best-effort: a
  # content type without a translations interface simply yields none.
  #
  # Delivery bypass (moduledoc): `:published_translations` filters published +
  # audience + unlock itself (no unlocks are passed, so a locked variant is
  # simply not listed), and `tenant:` scopes it to this site.
  defp translations(ct, slug, org_id, audiences) do
    ContentTypes.list_translations(ct.type, slug,
      audiences: audiences,
      authorize?: false,
      tenant: org_id
    )
  rescue
    _ -> []
  end

  # `rel="alternate" hreflang` entries for every published locale variant, plus
  # an `x-default` pointing at the default locale.
  defp hreflang_alternates(ct, translations, base_url) do
    default = I18n.default_locale()

    alternates =
      for t <- translations,
          do: %{hreflang: t.locale, href: locale_url(ct, t.slug, t.locale, base_url)}

    case Enum.find(translations, &(&1.locale == default)) do
      nil ->
        alternates

      t ->
        alternates ++
          [%{hreflang: "x-default", href: locale_url(ct, t.slug, default, base_url)}]
    end
  end

  # Language-switcher links to each published translation of this record.
  defp locale_links(ct, translations, current, base_url) do
    translations
    |> Enum.map(
      &%{
        locale: &1.locale,
        href: locale_url(ct, &1.slug, &1.locale, base_url),
        current: &1.locale == current
      }
    )
    |> Enum.sort_by(& &1.locale)
  end

  # Absolute public URL for `slug` in `locale` (non-default locales are prefixed).
  defp locale_url(ct, slug, locale, base_url) do
    prefix = if locale == I18n.default_locale(), do: "", else: "/#{locale}"
    "#{base_url}#{prefix}#{ContentTypes.public_prefix(ct)}/#{slug}"
  end

  # Pre-render the JSON-LD as a safe <script> tag. HEEx doesn't interpolate
  # inside a literal <script> element, so the layout injects this with `{...}`.
  # `escape: :html_safe` escapes `<`/`>`/`&`, so the JSON can't break out of the
  # tag.
  defp json_ld_script(data) do
    json = Jason.encode!(data, escape: :html_safe)
    Phoenix.HTML.raw(~s(<script type="application/ld+json">#{json}</script>))
  end

  defp blocks(record, org_id, audiences) do
    # Blocks are stored as the typed union (Kiln v2); convert back to legacy block
    # structs so the existing media-enriching renderer (`BlockComponents`) is
    # unchanged. A `columns` block (#335) nests child blocks, so the tree is built
    # recursively and flattened once for the media/form preloads — a nested image
    # or form is loaded in the same batched query as a top-level one.
    #
    # Reusable fragments (#479) are inlined first, so everything after this line
    # — the media/form preloads included — sees the real tree. HTML delivery
    # renders live from the block tree rather than from the fired artifact, so
    # the expansion has to happen on this path too. `audiences` is the reader's,
    # and the payload cache is already keyed on it.
    tree = record |> expand_fragments(org_id, audiences) |> block_tree()
    flat = flatten_block_tree(tree)

    media = load_block_media(flat, org_id)
    forms = load_block_forms(flat, org_id)
    Enum.map(tree, &enrich_block(&1, media, forms))
  end

  defp expand_fragments(record, org_id, audiences) do
    record.blocks
    |> KilnCMS.CMS.TypedBlocks.to_typed()
    |> KilnCMS.CMS.Fragments.expand(org_id,
      audiences: audiences,
      # Seeded with the record itself: a page embedding *itself* would otherwise
      # inline its own body once before the cycle guard caught it a level down.
      ancestry: [{KilnCMS.Firing.Engine.public_type(record), record.id}]
    )
  end

  # Typed union → legacy `KilnCMS.CMS.Block` structs, recursing into `columns`
  # children so each nested block is itself a legacy struct the renderer handles.
  defp block_tree(blocks) do
    blocks
    |> KilnCMS.CMS.TypedBlocks.to_typed()
    |> KilnCMS.CMS.TypedBlocks.to_legacy()
    |> Enum.map(&struct(KilnCMS.CMS.Block, &1))
    |> Enum.map(&nest_columns/1)
  end

  defp nest_columns(%KilnCMS.CMS.Block{type: :columns, data: data} = block) do
    cols =
      for col <- data["columns"] || [] do
        %{"blocks" => col |> Map.get("blocks", []) |> block_tree()}
      end

    %{block | data: Map.put(data, "columns", cols)}
  end

  defp nest_columns(block), do: block

  # Depth-first block list, so the media/form preloads see nested blocks too.
  defp flatten_block_tree(blocks) do
    Enum.flat_map(blocks, fn
      %KilnCMS.CMS.Block{type: :columns, data: %{"columns" => cols}} = block ->
        [block | Enum.flat_map(cols, &flatten_block_tree(&1["blocks"] || []))]

      block ->
        [block]
    end)
  end

  # Batch-load the active forms referenced by form blocks (fields included),
  # keyed by slug — inactive/unknown slugs simply don't enrich.
  defp load_block_forms(blocks, org_id) do
    slugs =
      for b <- blocks,
          to_string(b.type) == "form",
          slug = b.data["form_slug"] || b.content,
          is_binary(slug) and slug != "",
          uniq: true,
          do: slug

    # Tenant-scoped so a page only embeds forms from its own site (#336).
    Map.new(slugs, &{&1, KilnCMS.Forms.get_active(&1, org_id)})
  end

  # Batch-load the media items referenced by image and gallery blocks (so we
  # render one query, not one per image).
  #
  # A gallery's ids live one level down, inside its `images` list, so collecting
  # only top-level `media_id` would leave every gallery image with no srcset, no
  # focal point and no intrinsic dimensions on the public site — a silent
  # degradation, since the stored url still renders (#482).
  defp load_block_media(blocks, org_id) do
    ids = blocks |> Enum.flat_map(&block_media_ids/1) |> Enum.uniq()

    case ids do
      [] ->
        %{}

      ids ->
        # Tenant-scoped so a page can only enrich media from its own site (#336);
        # `authorize?: false` is the delivery bypass (moduledoc), so the tenant
        # is the guard — and the ids come from blocks of a record delivery
        # already resolved as readable.
        CMS.list_media_items!(
          authorize?: false,
          tenant: org_id,
          query: [filter: [id: [in: ids]]]
        )
        |> Map.new(&{&1.id, &1})
    end
  end

  # Filtered to real uuids once, here, rather than in each clause.
  #
  # A blank `media_id` is the normal state of an image pasted in by URL — but
  # `media_id` is a free-text block field, so an importer or an API caller can
  # put anything in it, and `id` is a uuid column: Ash rejects a non-uuid at
  # query build, which means `list_media_items!` *raises* and the published page
  # 500s for every visitor. `KilnCMS.Firing.References` has guarded this since
  # it was written; delivery never did, and a gallery multiplies the exposure
  # from one id per block to N.
  defp block_media_ids(%{type: type, data: data}) do
    type |> to_string() |> media_ids_for(data) |> Enum.filter(&valid_media_id?/1)
  end

  defp block_media_ids(_block), do: []

  defp media_ids_for("image", data), do: [data["media_id"]]

  defp media_ids_for("gallery", data) do
    data["images"] |> List.wrap() |> Enum.filter(&is_map/1) |> Enum.map(& &1["media_id"])
  end

  defp media_ids_for(_type, _data), do: []

  defp valid_media_id?(id) when is_binary(id), do: match?({:ok, _}, Ecto.UUID.cast(id))
  defp valid_media_id?(_id), do: false

  defp enrich_block(block, media, forms) do
    base = %{type: to_string(block.type), content: block.content}

    cond do
      block.type == :columns ->
        enrich_columns(base, block, media, forms)

      block.type == :image && match?(%{}, media[block.data["media_id"]]) ->
        item = media[block.data["media_id"]]

        Map.merge(base, %{
          srcset: srcset(item),
          # Alternate encodings for `<picture>` (#473). Separate from `srcset`
          # on purpose — see `Media.Presentation`.
          sources: KilnCMS.Media.Presentation.sources(item),
          # The block's own alt wins, with the library row as the fallback
          # behind it. This used to take `item.alt` unconditionally, which put
          # this surface at odds with every other one: the fired `:web`
          # artifact, the pop-out preview and the in-context editor all render
          # the block's alt, and `Validations.MediaAltText` gates publishing on
          # the block's alt and says in as many words that it "is what ships".
          # It wasn't. An image block described for its placement, pointing at a
          # library row nobody had filled in, passed the gate and then shipped
          # `alt=""` on the live site — the one surface the gate exists to
          # protect (#403, #482).
          alt: presence(block.data["alt"]) || item.alt,
          width: item.width,
          height: item.height,
          focal: focal_style(item)
        })

      block.type == :gallery ->
        enrich_gallery(base, block, media)

      block.type == :form ->
        # nil form (inactive/unknown slug) → the component renders nothing.
        Map.put(base, :form, forms[block.data["form_slug"] || block.content])

      true ->
        enrich_geo(base, block)
    end
  end

  # Per-item media enrichment (#482), mirroring what the `image` branch does for
  # a single image. An item whose `media_id` resolved to nothing still renders
  # from its stored url — just without srcset/focal/dimensions — which is what
  # happens when media is deleted out from under a published document.
  defp enrich_gallery(base, block, media) do
    images =
      for image <- block.data["images"] || [], is_map(image) do
        gallery_image(image, media[image["media_id"]])
      end

    Map.merge(base, %{
      images: images,
      style: KilnCMS.Blocks.Gallery.layout_style(block.data["layout"])
    })
  end

  defp gallery_image(image, item) do
    %{
      url: image["url"],
      # The item's own alt wins: it is the one written *for this placement*,
      # and `MediaItem.alt` is the library-wide default behind it. Same
      # precedence #403 established for the single-image block.
      alt: presence(image["alt"]) || (item && item.alt),
      caption: image["caption"],
      srcset: item && KilnCMS.Media.Presentation.srcset(item),
      sources: (item && KilnCMS.Media.Presentation.sources(item)) || [],
      width: item && item.width,
      height: item && item.height,
      focal: item && KilnCMS.Media.Presentation.focal_style(item)
    }
  end

  defp presence(value) when is_binary(value) do
    case String.trim(value) do
      "" -> nil
      trimmed -> trimmed
    end
  end

  defp presence(_value), do: nil

  # Embed cards (#489). Without these fields an embed reaches `BlockComponents`
  # as `%{type, content}` and the card branch — which needs a title — renders
  # nothing at all: the fired artifact and every preview showed a card while the
  # public page, the one surface that matters, showed an empty div.
  defp enrich_geo(base, %{type: :embed} = block) do
    Map.merge(base, %{
      title: block.data["title"],
      author_name: block.data["author_name"],
      provider_name: block.data["provider_name"],
      thumbnail_url: block.data["thumbnail_url"],
      resolved_url: block.data["resolved_url"]
    })
  end

  # GEO blocks (#357): surface the data-side fields the renderer reads.
  defp enrich_geo(base, %{type: :faq} = block),
    do: Map.put(base, :items, block.data["items"] || [])

  defp enrich_geo(base, %{type: :accordion} = block) do
    Map.merge(base, %{
      panels: block.data["panels"] || [],
      first_open: block.data["first_open"] == true
    })
  end

  defp enrich_geo(base, %{type: :how_to} = block) do
    Map.merge(base, %{description: block.data["description"], steps: block.data["steps"] || []})
  end

  defp enrich_geo(base, %{type: :claim} = block) do
    Map.merge(base, %{
      source_title: block.data["source_title"],
      source_url: block.data["source_url"]
    })
  end

  defp enrich_geo(base, _block), do: base

  # Recursively enrich a columns block's nested children (each column's blocks go
  # through the same `enrich_block/3` a top-level block does), and attach the grid
  # style so `BlockComponents` lays the container out identically to firing.
  defp enrich_columns(base, block, media, forms) do
    cols =
      for col <- block.data["columns"] || [] do
        %{blocks: Enum.map(col["blocks"] || [], &enrich_block(&1, media, forms))}
      end

    Map.merge(base, %{
      columns: cols,
      style:
        KilnCMS.Blocks.Columns.grid_style(block.data["layout"], block.data["gap"], length(cols))
    })
  end

  # `srcset/1` and `focal_style/1` live in `KilnCMS.Media.Presentation` — the
  # gallery block (#482) is the second consumer, and `srcset`'s exclusion of
  # cropped variants is the kind of rule that gets reintroduced by someone
  # writing a second builder rather than finding the first.
  defp srcset(item), do: KilnCMS.Media.Presentation.srcset(item)
  defp focal_style(item), do: KilnCMS.Media.Presentation.focal_style(item)

  defp not_found(conn, path) do
    # Every HTML URL miss funnels through here, so this is where the aggregated
    # 404 counter is written (#472) — after the alias table, the redirect table
    # and the teaser have all missed, i.e. only for paths nothing can serve.
    # Off the request path and best-effort; see `KilnCMSWeb.MissedPathTracking`.
    #
    # `path` is the caller's, NOT `conn.request_path`: the two diverge (empty
    # segments collapse, `%xx` stays encoded in `request_path`), and this is the
    # exact string `Redirects.resolve/3` was just asked for. Recording anything
    # else would list a path whose one-click redirect could never fire.
    KilnCMSWeb.MissedPathTracking.track(path, locale(conn), current_org_id(conn))

    conn
    # A 404 may be an unpublished/draft slug — never let a CDN or browser cache
    # it (it would mask the page once published).
    |> put_resp_header("cache-control", "no-store")
    |> put_status(:not_found)
    |> put_view(KilnCMSWeb.ErrorHTML)
    # A title, so the tab reads "Page not found · Acme Docs" rather than the
    # bare brand name. The endpoint-level `render_errors` twin cannot be given
    # one — Phoenix builds those assigns itself — and renders the brand alone,
    # which is correct if less specific (#559).
    |> render(:"404", page_title: gettext("Page not found"))
  end

  # CDN/browser cache headers for published HTML: a short shared max-age with a
  # longer stale-while-revalidate window (the in-BEAM cache is single-node, so
  # these let a CDN absorb origin load), plus a content ETag for conditional GETs
  # and `Vary: Accept-Language` since delivery is locale-sensitive.
  # Personalised or paywalled HTML: never shared-cacheable. `Vary: Cookie` is a
  # belt (CDNs honour it unevenly); `no-store` is the actual control.
  defp put_private_delivery_headers(conn) do
    conn
    |> put_resp_header("cache-control", "private, no-store")
    |> put_resp_header("vary", "Cookie, Accept-Language")
  end

  defp put_delivery_cache_headers(conn, record) do
    conn
    |> put_resp_header("cache-control", "public, max-age=60, stale-while-revalidate=300")
    |> put_resp_header("vary", "Accept-Language")
    |> put_resp_header("etag", etag(record, current_org_id(conn)))
  end

  # The resolved SEO fields are part of the raw string, not just the record's
  # own timestamps: with a type-level pattern (#805) two responses can differ
  # while every column on the record is identical. `render_content/6` resolves
  # before this is called, so what is hashed is what is sent.
  #
  # Head generation (#1079) is the same idea for layout-facing settings: feed
  # autodiscovery, branding, code injection and calendar links live in `<head>`
  # but are not columns on the content row, so a settings save must move the
  # ETag or a revalidating client keeps a 304 body whose links are already wrong.
  defp etag(record, org_id) do
    raw =
      "#{record.id}:#{record.updated_at}:#{record.published_version_id}" <>
        ":#{record.seo_title}:#{record.seo_description}" <>
        ":#{KilnCMS.Cache.head_generation(org_id)}"

    digest = :sha256 |> :crypto.hash(raw) |> Base.encode16(case: :lower) |> binary_part(0, 16)
    ~s("#{digest}")
  end

  defp delivery_fresh?(conn, record) do
    match?([_ | _], get_req_header(conn, "if-none-match")) and
      etag(record, current_org_id(conn)) in get_req_header(conn, "if-none-match")
  end
end
