alias KilnCMS.Media.ImageTransform

key = "kiln-test-signing-key"

photo = %{"id" => "8a5b8e4e-7b8f-4a57-9a5e-2f3a1c9d0b11", "url" => "/uploads/3f2a9c01-5b6d-4e1f-8a2b-7c9d0e1f2a3b.jpg",
          "focal_x" => 0.3, "focal_y" => 0.62, "width" => 2400, "height" => 1600}
centred = %{"id" => "0c0ffee0-0000-4000-8000-000000000001", "url" => "https://cdn.example.com/media/ab12.png",
            "focal_x" => nil, "focal_y" => nil, "width" => 900, "height" => 1200}
unicode = %{"id" => "11111111-2222-4333-8444-555555555555", "url" => "/uploads/café-über.webp",
            "focal_x" => 0.5, "focal_y" => 0.5, "width" => 640, "height" => 480}
no_url = %{"id" => "22222222-3333-4444-8555-666666666666"}
edge_focal = %{"id" => "33333333-4444-4555-8666-777777777777", "url" => "/uploads/x.jpg",
               "focal_x" => 0.1235, "focal_y" => 0.9995, "width" => 5000, "height" => 1000}

tie_focal = %{"id" => "44444444-5555-4666-8777-888888888888", "url" => "/uploads/tie.png",
              "focal_x" => 0.0625, "focal_y" => 0.4375, "width" => 1600, "height" => 900}

media = %{"tie_focal" => tie_focal, "photo" => photo, "centred" => centred, "unicode" => unicode, "no_url" => no_url, "edge_focal" => edge_focal}

to_opts = fn o ->
  Enum.flat_map(o, fn
    {"width", v} -> [width: v]
    {"height", v} -> [height: v]
    {"aspect_ratio", v} -> [aspect_ratio: v]
    {"dpr", v} -> [dpr: v]
    {"fit", v} -> [fit: String.to_atom(v)]
    {"crop", v} -> [crop: String.to_atom(v)]
    {"format", v} -> [format: String.to_atom(v)]
    {"quality", v} -> [quality: v]
  end)
end

url_cases = [
  {"unsigned width snaps up", "photo", %{"width" => 800}, nil},
  {"unsigned width on the ladder", "photo", %{"width" => 640}, nil},
  {"unsigned width past the top rung", "photo", %{"width" => 5000}, nil},
  {"unsigned tiny width", "photo", %{"width" => 1}, nil},
  {"unsigned aspect ratio", "photo", %{"width" => 1080, "aspect_ratio" => "16:9"}, nil},
  {"unsigned everything", "photo", %{"width" => 300, "height" => 300, "dpr" => 2, "fit" => "contain", "crop" => "top", "format" => "auto", "quality" => 75}, nil},
  {"unsigned height only", "centred", %{"height" => 500}, nil},
  {"unsigned format only", "centred", %{"format" => "webp"}, nil},
  {"unsigned no options", "unicode", %{}, nil},
  {"unsigned without a url has no v", "no_url", %{"width" => 256}, nil},
  {"signed keeps exact sizes", "photo", %{"width" => 801, "height" => 451}, key},
  {"signed aspect ratio and quality", "photo", %{"width" => 1234, "aspect_ratio" => "21:9", "quality" => 63, "format" => "avif"}, key},
  {"signed everything", "edge_focal", %{"width" => 333, "height" => 222, "dpr" => 3, "fit" => "cover", "crop" => "focal", "format" => "jpg", "quality" => 90}, key},
  {"signed no options", "unicode", %{}, key},
  {"signed without a url", "no_url", %{"width" => 10}, key},
  {"rounding ties round half away from zero", "tie_focal", %{"width" => 640, "aspect_ratio" => "1:1"}, nil}
]

urls =
  for {name, m, o, k} <- url_cases do
    item = media[m]
    opts = to_opts.(o) ++ if(k, do: [sign: true, key: k], else: [sign: false])
    %{"name" => name, "media" => m, "options" => o, "key" => k, "expected" => ImageTransform.url(item, opts)}
  end

srcset_cases = [
  {"unsigned default widths", "photo", nil, %{}, nil},
  {"unsigned default widths, narrow source", "unicode", nil, %{}, nil},
  {"unsigned custom widths snap and dedupe", "photo", [300, 500, 640, 700], %{}, nil},
  {"unsigned aspect ratio caps at the window", "centred", [256, 640, 1080, 1920], %{"aspect_ratio" => "16:9", "format" => "auto"}, nil},
  {"signed exact widths", "photo", [300, 600, 1200, 2400, 4000], %{"quality" => 70}, key},
  {"signed aspect ratio wider than the source", "edge_focal", [500, 1000, 2000], %{"aspect_ratio" => "1:1"}, key},
  {"no dimensions gives nil", "no_url", [256], %{}, nil}
]

srcsets =
  for {name, m, widths, o, k} <- srcset_cases do
    item = media[m]
    opts = to_opts.(o) ++ if(k, do: [sign: true, key: k], else: [sign: false])
    %{"name" => name, "media" => m, "widths" => widths, "options" => o, "key" => k,
      "expected" => ImageTransform.srcset(item, widths, opts)}
  end

versions =
  for {m, item} <- Enum.sort(media) do
    %{"media" => m, "expected" => if(Map.has_key?(item, "url"), do: ImageTransform.version(item))}
  end

doc = %{
  "_comment" => "Shared test vectors for image transform URLs. Generated by scripts/generate_image_transform_vectors.exs (MIX_ENV=test mix run --no-start scripts/generate_image_transform_vectors.exs). Asserted by the server (test/kiln_cms/media/image_transform_vectors_test.exs), the JS SDK (clients/js/test/transform.test.ts) and the Elixir client (clients/elixir/kiln_client/test/kiln_client/image_test.exs). Regenerate only after a deliberate change mirrored in all three.",
  "signing_key" => key,
  "sizes" => ImageTransform.sizes(),
  "media" => media,
  "versions" => versions,
  "urls" => urls,
  "srcsets" => srcsets
}

File.write!("clients/js/test/fixtures/image_transform_vectors.json", Jason.encode!(doc, pretty: true) <> "\n")
IO.puts("ok")
