/**
 * TypeScript emitter over Kiln's exported JSON Schema — the `kiln-types`
 * generator.
 *
 * Reads the schema document served by `GET /api/schema`
 * (`KilnCMS.SchemaExport`) and emits declarations for the `:json`
 * fired-artifact shape: every block, the `_type`-discriminated `KilnBlock`
 * union, one interface per content type — compiled types *and* admin-defined
 * dynamic ones, custom fields included — and the `KilnDocument` union.
 *
 * A faithful port of the server-side emitter
 * (`KilnCMS.SchemaExport.TypeScript`), so the two produce the same
 * declarations for the same document — fetch from a live site with the
 * `kiln-types` CLI instead of vendoring a copy that goes stale the moment an
 * admin adds a custom field.
 *
 * Anything the emitter cannot express — `format`, `minimum`, `default` — is
 * dropped rather than approximated. A declaration that lies about a
 * constraint is worse than one that is merely loose about it.
 */

interface JsonSchema {
  $ref?: string;
  oneOf?: JsonSchema[];
  type?: string | string[];
  const?: unknown;
  enum?: unknown[];
  items?: JsonSchema;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  additionalProperties?: boolean | JsonSchema;
  description?: string;
  [keyword: string]: unknown;
}

export interface SchemaDocument {
  $defs?: Record<string, JsonSchema>;
  "x-kiln"?: { artifact_format_version?: unknown; [key: string]: unknown };
  [keyword: string]: unknown;
}

/** Emit TypeScript declarations for a schema document from `GET /api/schema`. */
export function emitTypes(document: SchemaDocument): string {
  const defs = document.$defs ?? {};
  const entries = Object.entries(defs);

  const blockDefs = entries.filter(([name]) => name.startsWith("block_"));
  const contentDefs = entries.filter(([name]) => name.startsWith("content_"));
  const sharedDefs = entries.filter(
    ([name]) => !name.startsWith("block_") && !name.startsWith("content_"),
  );

  const sections = [
    header(document),
    section("Shared", declarations(sharedDefs.filter(([, schema]) => !isUnion(schema)))),
    section("Blocks", declarations(blockDefs.filter(([, schema]) => !isUnion(schema)))),
    section("Block union", [unionAlias("KilnBlock", defs.block)]),
    section("Documents", declarations(contentDefs)),
    section("Document union", [documentUnion(contentDefs.map(([name]) => name))]),
  ];

  return sections.filter((text) => text !== "").join("\n");
}

function header(document: SchemaDocument): string {
  const version = document["x-kiln"]?.artifact_format_version ?? "unknown";
  return (
    "// Generated by `kiln-types`. Do not edit.\n" +
    "//\n" +
    "// The `:json` fired-artifact shape served by\n" +
    "// `GET /api/content/:type/:slug?surface=json`.\n" +
    "//\n" +
    `// Artifact format version: ${String(version)}\n`
  );
}

function section(title: string, decls: string[]): string {
  const kept = decls.filter((decl) => decl !== "");
  if (kept.length === 0) return "";
  const rule = "-".repeat(Math.max(0, 60 - title.length));
  return `\n// -- ${title} ${rule}\n\n` + kept.join("\n\n") + "\n";
}

function declarations(defs: [string, JsonSchema][]): string[] {
  return defs
    .slice()
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([name, schema]) => emitInterface(typeName(name), schema));
}

function isUnion(schema: JsonSchema): boolean {
  return schema.oneOf !== undefined;
}

// A document with no block union at all (a hand-assembled `$defs`, or a
// partial export) simply has no alias to emit.
function unionAlias(name: string, schema: JsonSchema | undefined): string {
  if (schema?.oneOf === undefined) return "";
  const members = schema.oneOf.map((ref) => typeName(refTarget(ref))).join("\n  | ");
  return `export type ${name} =\n  | ${members};`;
}

function documentUnion(names: string[]): string {
  if (names.length === 0) return "";
  const members = names.slice().sort().map(typeName).join("\n  | ");
  return `export type KilnDocument =\n  | ${members};`;
}

function emitInterface(name: string, schema: JsonSchema): string {
  const properties = schema.properties;

  // A schema with no `properties` (a lone `const`, an open object) has no
  // interface to write — alias it to `unknown` rather than emitting `{}`,
  // which TypeScript treats as "anything but null".
  if (properties === undefined) {
    return `${docComment(schema)}export type ${name} = unknown;`;
  }

  const required = new Set(schema.required ?? []);
  const body = Object.entries(properties)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([key, value]) => {
      const optional = required.has(key) ? "" : "?";
      return `  ${propertyKey(key)}${optional}: ${tsType(value)};`;
    })
    .join("\n");

  const extra = schema.additionalProperties === false ? "" : "\n  [k: string]: unknown;";

  return `${docComment(schema)}export interface ${name} {\n${body}${extra}\n}`;
}

function docComment(schema: JsonSchema): string {
  const description = schema.description;
  if (description === undefined) return "";
  return `/** ${description.replace(/\*\//g, "*\\/")} */\n`;
}

// ── type mapping ────────────────────────────────────────────────────────────

function tsType(schema: JsonSchema): string {
  if (schema.$ref !== undefined) return typeName(refTarget(schema));

  if (schema.oneOf !== undefined) {
    return schema.oneOf.map((ref) => typeName(refTarget(ref))).join(" | ");
  }

  // Ahead of `const`/`enum`, not after. A nullable enum carries both keywords,
  // and matching the value clause first would emit `"free" | "pro"` for a
  // `["string", "null"]` field — telling a consumer that `?.` is redundant on
  // a value delivery really does send as null.
  if (Array.isArray(schema.type)) {
    const nulls = schema.type.filter((t) => t === "null");
    const rest = schema.type.filter((t) => t !== "null");
    const members = rest.map((t) => tsType({ ...schema, type: t }));
    return members.concat(nulls.map(() => "null")).join(" | ");
  }

  if ("const" in schema) return literal(schema.const);

  if (schema.enum !== undefined) return schema.enum.map(literal).join(" | ");

  if (schema.type === "array") return `Array<${tsType(schema.items ?? {})}>`;

  if (schema.type === "object") {
    const properties = schema.properties;
    if (properties === undefined) return "Record<string, unknown>";
    return inlineObject(properties, new Set(schema.required ?? []));
  }

  switch (schema.type) {
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "string":
      return "string";
    case "null":
      return "null";
    default:
      return "unknown";
  }
}

function inlineObject(properties: Record<string, JsonSchema>, required: Set<string>): string {
  const body = Object.entries(properties)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([key, value]) => {
      const optional = required.has(key) ? "" : "?";
      return `${propertyKey(key)}${optional}: ${tsType(value)}`;
    })
    .join("; ");
  return `{ ${body} }`;
}

function literal(value: unknown): string {
  if (typeof value === "string") return `"${escapeString(value)}"`;
  return String(value);
}

// Custom-field names and `:select` options are admin input with no charset
// validation, so a backslash or a newline in one would otherwise emit a
// declaration that silently changes meaning (`C:\reports` → `C:reports`) or
// does not parse at all. Backslash first, or it would re-escape the escapes.
function escapeString(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

// ── naming ──────────────────────────────────────────────────────────────────

function refTarget(schema: JsonSchema): string {
  const parts = (schema.$ref ?? "").split("/");
  return parts[parts.length - 1] ?? "";
}

// `block_rich_text` → `RichTextBlock`, `content_post` → `PostDocument`,
// `portable_text_block` → `PortableTextBlock`, `block` → `KilnBlock`.
function typeName(name: string): string {
  if (name === "block") return "KilnBlock";
  if (name.startsWith("block_")) return pascal(name.slice("block_".length)) + "Block";
  if (name.startsWith("content_")) return pascal(name.slice("content_".length)) + "Document";
  return pascal(name);
}

function pascal(name: string): string {
  return name
    .split(/[_-]/)
    .filter((word) => word !== "")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

// A key that is not a plain identifier has to be quoted, or the declaration
// will not parse. Custom-field names are admin input, so this is not
// hypothetical.
function propertyKey(key: string): string {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)) return key;
  return `"${escapeString(key)}"`;
}
