defmodule KilnCMS.SchemaExport do
  @moduledoc """
  Machine-readable schema for the headless `:json` delivery surface (#430).

  The last unshipped "one definition fans out" item from the v2 plan. A block
  definition already produces an embedded resource, a union member, an editor
  input and four serializers; this produces the artifact typed clients were
  missing — a JSON Schema (and a `.d.ts` on top of it, see
  `KilnCMS.SchemaExport.TypeScript`) describing exactly what
  `GET /api/content/:type/:slug?surface=json` returns.

  ## What it covers

    * every registered block, derived from its `Kiln.Block` declaration
      (`Kiln.Block.JsonSchema`), including plugin-contributed ones;
    * the `_type`-discriminated union over them, recursing into container
      blocks;
    * one document schema **per content type** — compiled types *and* the
      admin-defined dynamic ones, whose custom fields are rows rather than
      code, read at export time.

  That last part is why this is not a compile-time artifact and why the export
  is per-organization: two sites on one deployment have different dynamic types
  and different custom fields, so they have different schemas. `org_id` is
  therefore an argument everywhere here, defaulting to the sole org.

  ## Where it comes out

    * `mix kiln.export.schema` — a file or stdout, for a build step;
    * `GET /api/schema` — the live schema for the requesting site, so a client
      can fetch rather than vendor it.

  ## What it deliberately does not cover

  The **authoring** shape. The write API (#330) accepts the stored block tree,
  not the fired projection, and that surface is already described by the
  OpenAPI document at `/api/json/open_api`. Conflating the two would produce a
  schema that is wrong for both.
  """

  alias Kiln.Block.JsonSchema
  alias KilnCMS.CMS
  alias KilnCMS.CMS.ContentTypes
  alias KilnCMS.CMS.FieldTypes

  @dialect "https://json-schema.org/draft/2020-12/schema"

  @typedoc """
  Options for `json_schema/1`.

    * `:org_id` — the site whose dynamic types and custom fields are described
      (default: the sole org);
    * `:types` — restrict to these content-type names (strings or atoms);
      unknown names raise, so a typo in a build script fails loudly;
    * `:base_url` — origin used for the document `$id`;
    * `:blocks_only` — skip content types entirely (no database read).
  """
  @type option ::
          {:org_id, Ash.UUID.t()}
          | {:types, [atom() | String.t()]}
          | {:base_url, String.t() | nil}
          | {:blocks_only, boolean()}

  @doc """
  The full JSON Schema document.

  Its root is a `oneOf` over the document schemas, so a fired `:json` artifact
  validates against the document as-is; individual pieces are addressable under
  `$defs` (`#/$defs/block`, `#/$defs/content_post`) for a consumer that wants
  one of them.
  """
  @spec json_schema([option()]) :: map()
  def json_schema(opts \\ []) do
    model = model(opts)

    content_defs =
      Map.new(model.content_types, fn ct -> {content_def_name(ct.type), content_schema(ct)} end)

    root_refs =
      Enum.map(model.content_types, &%{"$ref" => "#/$defs/#{content_def_name(&1.type)}"})

    %{
      "$schema" => @dialect,
      "title" => "Kiln CMS delivery schema",
      "description" =>
        "The `:json` fired-artifact shape served by `GET /api/content/:type/:slug`. " <>
          "Generated by `mix kiln.export.schema` / `GET /api/schema`.",
      "x-kiln" => %{
        "surface" => "json",
        "artifact_format_version" => KilnCMS.Firing.Engine.format_version(),
        "content_types" => Enum.map(model.content_types, &to_string(&1.type)),
        # From the same filtered list `$defs` uses, not the raw registry scan:
        # `Blocks.modules/0` is duck-typed on `render/2`, so a module that
        # implements the renderer behaviour without `use Kiln.Block` is in the
        # list but has no DSL, and `Info.name/1` raises on it. Reading the raw
        # list here would 500 the endpoint on exactly the module `$defs` was
        # careful to skip.
        "blocks" => Enum.map(model.block_modules, &to_string(Kiln.Block.Info.name(&1)))
      },
      "$defs" => Map.merge(JsonSchema.defs(model.block_modules), content_defs)
    }
    |> put_id(Keyword.get(opts, :base_url))
    |> put_root(root_refs)
  end

  # What `json_schema/1` resolves before it formats anything: the block modules,
  # and the content types with their custom-field definitions loaded.
  defp model(opts) do
    org_id = Keyword.get_lazy(opts, :org_id, &KilnCMS.Accounts.default_org_id/0)
    types = Keyword.get(opts, :types)

    content_types =
      if Keyword.get(opts, :blocks_only, false) do
        # Still validate the names. `--blocks-only --type typo` would otherwise
        # write a silently-wrong artifact, and the endpoint would answer 200 to
        # `?blocks=only&type=nope` while documenting that unknown names are 400.
        if types, do: resolve_types(org_id, types)
        []
      else
        org_id |> resolve_types(types) |> Enum.map(&describe(&1, org_id))
      end

    %{
      org_id: org_id,
      block_modules: JsonSchema.block_modules(KilnCMS.Blocks.modules()),
      content_types: content_types
    }
  end

  @doc "The `$defs` key for a content type (`:post` → `content_post`)."
  @spec content_def_name(atom() | String.t()) :: String.t()
  def content_def_name(type), do: "content_" <> String.replace(to_string(type), "-", "_")

  # ── content types ───────────────────────────────────────────────────────────

  defp resolve_types(org_id, nil), do: ContentTypes.all() ++ ContentTypes.dynamic_all(org_id)

  defp resolve_types(org_id, names) do
    all = resolve_types(org_id, nil)
    index = Map.new(all, &{to_string(&1.type), &1})

    # Deduplicated, and that is correctness rather than tidiness: `content_defs`
    # is a map and collapses a repeat, but the root `oneOf` is a list and does
    # not — and `oneOf` means *exactly one*, so `?type=post,post` would publish
    # a document that rejects every post it describes. Deduping also caps the
    # per-name `field_definitions` read, which an unbounded `?type=` list would
    # otherwise multiply into one query per repetition on a public endpoint.
    wanted = names |> Enum.map(&to_string/1) |> Enum.uniq()

    case Enum.reject(wanted, &Map.has_key?(index, &1)) do
      [] ->
        # Preserve the caller's order, so `--type post,page` reads back that way.
        Enum.map(wanted, &Map.fetch!(index, &1))

      unknown ->
        raise ArgumentError,
              "unknown content type(s): #{Enum.join(unknown, ", ")}. " <>
                "Known: #{Enum.map_join(all, ", ", &to_string(&1.type))}"
    end
  end

  # Definitions are registry metadata for a type the caller already named, and
  # the export runs outside any actor's session (a mix task has none), so the
  # read is unauthorized under the export's own org — the same posture firing
  # takes in `KilnCMS.Firing.CustomFields`.
  defp describe(%{source: :dynamic, definition: definition} = ct, org_id) do
    Map.put(
      ct,
      :field_definitions,
      CMS.field_definitions_for_definition!(definition.id, authorize?: false, tenant: org_id)
    )
  end

  defp describe(%{type: type} = ct, org_id) do
    Map.put(
      ct,
      :field_definitions,
      CMS.field_definitions_for!(type, authorize?: false, tenant: org_id)
    )
  end

  defp content_schema(ct) do
    %{
      "type" => "object",
      "title" => document_title(ct.type),
      "description" => "A published `#{ct.label}` as fired to the `:json` surface.",
      "x-kiln-content-type" => to_string(ct.type),
      "x-kiln-content-type-source" => to_string(ct.source),
      "properties" => %{
        "id" => %{"type" => "string", "format" => "uuid"},
        "type" => %{"const" => to_string(ct.type)},
        "title" => %{"type" => ["string", "null"]},
        "slug" => %{"type" => ["string", "null"]},
        "locale" => %{"type" => ["string", "null"]},
        "custom_fields" => custom_fields_schema(ct.field_definitions),
        "blocks" => %{"type" => "array", "items" => JsonSchema.block_ref()}
      },
      "required" => ["blocks", "custom_fields", "id", "locale", "slug", "title", "type"],
      "additionalProperties" => false
    }
  end

  # **Open**, though firing's own path is closed. `Firing.CustomFields.resolve/3`
  # projects onto the current definitions with a `Map.take` — but only on its
  # `recompute?: true` branch. Point-in-time delivery fires
  # `custom_fields: :as_stored` and returns the stored map whole, and
  # `?as_of=` is served from the very route this schema describes. So a field
  # deleted last month still reaches a historical read, and a closed object
  # would make that legitimately-published document validate against nothing.
  #
  # Nothing is `required`, including definitions marked required. A definition
  # added after existing content was last saved has no stored value, and firing
  # does not invent one — so "required" describes the editor, not the payload.
  defp custom_fields_schema(definitions) do
    %{
      "type" => "object",
      "description" =>
        "Admin-defined custom fields (`KilnCMS.CMS.FieldDefinition`). Open: a " <>
          "point-in-time read (`?as_of=`) serves the values stored at that " <>
          "instant, which may include fields since removed from the registry.",
      "properties" => Map.new(definitions, &{&1.name, custom_field_schema(&1)}),
      "additionalProperties" => true
    }
  end

  defp custom_field_schema(definition) do
    base_custom_field_schema(definition.field_type, definition)
  end

  defp base_custom_field_schema(:integer, _d), do: %{"type" => ["integer", "null"]}
  defp base_custom_field_schema(:float, _d), do: %{"type" => ["number", "null"]}
  defp base_custom_field_schema(:boolean, _d), do: %{"type" => ["boolean", "null"]}

  defp base_custom_field_schema(:date, _d),
    do: %{"type" => ["string", "null"], "format" => "date"}

  defp base_custom_field_schema(:datetime, _d),
    do: %{"type" => ["string", "null"], "format" => "date-time"}

  defp base_custom_field_schema(:url, _d), do: %{"type" => ["string", "null"], "format" => "uri"}

  # Deliberately **not** an `enum` of the definition's options, for two
  # independent reasons. It would be wrong: `ApplyCustomFields` keeps an
  # untouched key as-is and firing never re-coerces, so narrowing or renaming an
  # option leaves every already-published document carrying a value outside the
  # new list — and an `enum` alongside `["string", "null"]` also forbids the
  # `null` that same type admits. And it would disclose: the option list is
  # admin-authored editorial vocabulary, which this endpoint has no reason to
  # publish anonymously.
  defp base_custom_field_schema(:select, _d), do: %{"type" => ["string", "null"]}

  defp base_custom_field_schema(:media, _d) do
    %{
      "type" => ["object", "null"],
      "description" => "Write-time snapshot of the picked media item."
    }
  end

  defp base_custom_field_schema(:reference, _d) do
    %{
      "type" => ["object", "null"],
      "description" => "Write-time snapshot of a referenced record."
    }
  end

  defp base_custom_field_schema(type, _d) when type in [:string, :text],
    do: %{"type" => ["string", "null"]}

  # Everything else is a `Kiln.FieldType` — a built-in (geolocation, computed,
  # the event pair) or a plugin's. Ask the module: it may declare its delivered
  # JSON shape outright, and otherwise we infer one from its editor widget.
  defp base_custom_field_schema(type, definition) do
    case FieldTypes.get(type) do
      nil -> %{}
      module -> field_type_schema(module, definition)
    end
  end

  # `Code.ensure_loaded?` before every probe: `FieldTypes.get/1` returns a module
  # atom out of a compile-baked literal map and never loads it, so under
  # interactive mode (which is how `mix kiln.export.schema` runs) an untouched
  # field-type module answers `false` to `function_exported?` and silently
  # exports as a bare string instead of its real shape.
  defp field_type_schema(module, definition) do
    loaded? = Code.ensure_loaded?(module)

    cond do
      loaded? and function_exported?(module, :json_schema, 1) ->
        module.json_schema(definition)

      # Branch on the parts themselves, not on whether the callback exists:
      # `use Kiln.FieldType` defaults `input_parts/1` to `[]`, so every scalar
      # type exports the callback too and probing for it would type them all as
      # empty objects.
      loaded? and parts(module, definition) != [] ->
        composite_schema(module.input_parts(definition))

      true ->
        %{"type" => [input_json_type(module, loaded?), "null"]}
    end
  end

  @doc """
  `module`'s declared composite input parts for `definition`, or `[]` if it
  doesn't implement `c:Kiln.FieldType.input_parts/1`.

  Public for the same reason `html_input_json_type/1` is: so `mix
  kiln.plugins.doctor` (#937) can ask "is this composite, and what are its
  parts" the same way this module does, rather than reimplementing the guard.
  """
  @spec parts(module(), struct()) :: [Kiln.FieldType.input_part()]
  def parts(module, definition) do
    if function_exported?(module, :input_parts, 1), do: module.input_parts(definition), else: []
  end

  # No `required`: `input_part.required?` means "carries the *definition's*
  # required flag", which is an editor concern — the same reason nothing in
  # `custom_fields` is required at all.
  defp composite_schema(parts) do
    %{
      "type" => ["object", "null"],
      "properties" =>
        Map.new(parts, fn part ->
          {part.key, %{"type" => html_input_json_type(Map.get(part, :type, "text"))}}
        end)
    }
  end

  defp input_json_type(module, true) do
    if function_exported?(module, :input_type, 0),
      do: html_input_json_type(module.input_type()),
      else: "string"
  end

  defp input_json_type(_module, false), do: "string"

  @doc """
  The JSON type an HTML input type implies (`"number"` → `"number"`, etc).

  Public so `mix kiln.plugins.doctor` (#937) can compare a plugin field
  type's `cast/2` output against what its editor widget implies, rather than
  reimplementing this table.
  """
  @spec html_input_json_type(String.t()) :: String.t()
  def html_input_json_type("number"), do: "number"
  def html_input_json_type("range"), do: "number"
  def html_input_json_type("checkbox"), do: "boolean"
  def html_input_json_type(_), do: "string"

  # ── document assembly ───────────────────────────────────────────────────────

  defp put_id(document, nil), do: document

  # `String.trim_trailing`: `$id` is the base every relative `$ref` resolves
  # against, and `--base-url https://example.com/` would otherwise publish
  # `https://example.com//api/schema`.
  defp put_id(document, base_url),
    do: Map.put(document, "$id", String.trim_trailing(base_url, "/") <> "/api/schema")

  # A blocks-only export has no document to be `oneOf` — leaving an empty
  # `oneOf` in would produce a schema nothing can satisfy.
  defp put_root(document, []), do: document
  defp put_root(document, refs), do: Map.put(document, "oneOf", refs)

  defp document_title(type), do: JsonSchema.pascal(type) <> "Document"
end
