// Generated by `kiln-types`. Do not edit.
//
// The `:json` fired-artifact shape served by
// `GET /api/content/:type/:slug?surface=json`.
//
// Artifact format version: 2


// -- Shared ------------------------------------------------------

export interface GeoPoint {
  lat: number;
  lng: number;
  zoom?: number | null;
}

export type OpaqueMarker = unknown;

/** One Portable Text node. Open by design. */
export interface PortableTextBlock {
  _key?: string;
  _type?: string;
  [k: string]: unknown;
}


// -- Blocks ------------------------------------------------------

export interface CallToActionBlock {
  _type: "call_to_action";
  label: string;
  priority?: number;
  style?: "primary" | "ghost";
  url?: string | null;
}

/** A container block: recurses into the block union. */
export interface ColumnsBlock {
  _type: "columns";
  columns: Array<{ blocks: Array<KilnBlock>; span?: number }>;
}

/** Portable Text body. Watch the *\/ escape. */
export interface RichTextBlock {
  _id?: string;
  _type: "rich_text";
  body: Array<PortableTextBlock>;
}


// -- Block union -------------------------------------------------

export type KilnBlock =
  | RichTextBlock
  | ColumnsBlock
  | CallToActionBlock;


// -- Documents ---------------------------------------------------

export interface LandingPageDocument {
  hero?: Record<string, unknown>;
  title: string;
  type: "landing_page";
}

/** A published post's fired `:json` artifact. */
export interface PostDocument {
  blocks: Array<KilnBlock>;
  custom_fields?: { badge?: "say \"hi\"" | "C:\\reports" | "line\nbreak\tand tab"; rating?: number | null; "weird key!"?: string };
  featured?: boolean;
  location?: GeoPoint;
  slug: string;
  tier?: "free" | "pro" | null;
  title: string;
  type: "post";
  word_count?: number;
  [k: string]: unknown;
}


// -- Document union ----------------------------------------------

export type KilnDocument =
  | LandingPageDocument
  | PostDocument;
